### ISSUE TITLE
Spending TXOut received in new transaction to an HD Wallet

### ISSUE THREAD

**Issue by chriswhellams** [dgarage/NBXplorer#100]
Hi,

Is it possible to spend the TXOut received to an HD wallet derived address using just the NewTransactionEvent object data and master key ?

Looking at the HD wallet example from Nicolas' book a query is made to NBXplorer to get UTXOs and there is a helper method to get the private Keys 

```
var coins = utxos.GetUnspentCoins();
var keys = utxos.GetKeys(userExtKey);
TransactionBuilder builder = new TransactionBuilder();
builder.AddCoins(coins);
builder.AddKeys(keys);
....
```

This makes life very easy - but if I just have the NewTransactionObject from NBXplorer  on a machine that is not connected to NBXplorer can I use the transaction builder to build a signed transaction which I could then use somewhere else e.g. BlockCypher raw transaction sender ?

**Comment by chriswhellams** [comment]
OK , I figured this out myself by looking at the NBitcoin and NBXlporer code. There are probably other ways to do this too.

In the NewTransactionEvent object (`NBXplorer.Models.NewTransactionEvent`) that NBXplorer outputs when you have registered a derivation strategy there is an Outputs List of KeyPathInformation

`NewTransactionEvent.Outputs`

The List will contain the derived KeyPaths that NBXplorer has found in your transaction - `KeyPathInformation` contains numerous useful properties - in particular for this case the `ScriptPubKey ` and `KeyPath`.

Build a dictionary of these e.g.
```
var keyPaths = new Dictionary<Script, KeyPath>();
foreach (var keyPathInfo in NewTranEvent.Outputs)
{
   keyPaths.TryAdd(keyPathInfo.ScriptPubKey, keyPathInfo.KeyPath);
}
```

THen get the TXOuts from the NewTransactionEvent 

`NewTranEvent.TransactionData.Transaction.Outputs;`

Then loop through your TXOuts and compare against your KeyPathInformation. Where the scriptpubkey in TXOut matches with KeyPathInfo then you have found an output that belongs to your MasterKey (HD Wallet). 

```
ICoin[] coins = new ICoin[1];
            Key[] keys = new Key[1];

            foreach (var txout in receivedCoins)
            {
                KeyPath kp;
                keyPaths.TryGetValue(txout.ScriptPubKey, out kp);

                if (kp == null)
                    continue;

                var signkey = masterKey.Derive(kp).PrivateKey;
                keys[0] = signkey;
                Coin c = new Coin(transaction, txout);
                coins[0] = c;
            }

```
You will now have an array of coins and keys that you can use in the TransactionBuilder

```
var destAddr = BitcoinAddress.Create(myaddress, mynetwork);
            builder
                .AddCoins(coins)
                .AddKeys(keys)
                .Send(destAddr.ScriptPubKey, amount)
.....
```
Hope that helps someone out ! If @NicolasDorier  could comment on this approach (good/bad/ugly!) I think that would be helpful.

**Comment by NicolasDorier** [comment]
Why you don't want to use the helper methods? It seems to me it will help you.
The objects with the helper method are easily (de)serializable in json, so you can save them in DB or whatever.

**Comment by chriswhellams** [comment]
If you run the node+ nbxplorer in a DMZ with only MQ / Service bus as the comms channel then you cannot call the REST Api of NBXplorer as its firewalled - the only messages are new block / new transaction.   I could use a proxy on the node machine to pump messages up/down the service bus to get UTXOs I suppose - and that probably would be a better, or then we just open up the port and talk to NBXplorer - of course, its possible to create VPN / VNETs etc but then things get complicated with networking and I have tried to follow the Martin Fowler microservice / de-coupled approach using light weight messaging https://www.martinfowler.com/articles/microservices.html.

**Comment by NicolasDorier** [comment]
Why not adding the helper methods to the events?

**Comment by chriswhellams** [comment]
Both approaches would work - another option is to move NBXplorer inside the firewall and then setup networking to the nodes running in DMZ....but for us it would then be better to run NBXplorer as a WebApp in Azure to avoid VMs and I think that would then need some refactoring to also use something like Azure SQL or Cosmos as the data store . So many choices.....

**Comment by sigHash** [comment]
@chriswhellams No sure if it's your priority right now, but if you like to contribute to [IRepository](Refactor Repository to IRepository), let me know so we can make it happen.

**Comment by NicolasDorier** [comment]
@chriswhellams You can set up NBXplorer as a webapp. But you need to keep it private.

**Comment by chriswhellams** [comment]
> @chriswhellams Not sure if it's your priority right now, but if you like to contribute to [IRepository](https://github.com/dgarage/NBXplorer/pull/114), let me know so we can make it happen.

YES - I noticed the discussion for this. I am totally maxxed out right now so I don't think I can help much with the interface implementation, but if you can get an initial version out then I will do the Azure SQL adapter for sure. Much as I like the approach @NicolasDorier has taken with this lib I would feel much more comfortable with the data in a more robust datastore  that is easy to query.
