### ISSUE TITLE
Azure Message Broker - MessageId issue

### ISSUE THREAD

**Issue by chriswhellams** [dgarage/NBXplorer#101]
In `\NBXplorer\MessageBrokers\AzureBroker.cs`

Line 36

```csharp
message.MessageId = $"{transactionEvent.DerivationStrategy.GetHash()}-{transactionEvent.TransactionData.Transaction.GetHash()}-{(transactionEvent.TransactionData.BlockId?.ToString
```
According to the Azure C# Service Bus client library: **Message ID cannot be null/empty and max length is 128**

```csharp
private static void ValidateMessageId(string messageId)
        {
            if (string.IsNullOrEmpty(messageId) ||
                messageId.Length > Constants.MaxMessageIdLength)
            {
                // TODO: throw FxTrace.Exception.Argument("messageId", SRClient.MessageIdIsNullOrEmptyOrOverMaxValue(Constants.MaxMessageIdLength));
                throw new ArgumentException("MessageIdIsNullOrEmptyOrOverMaxValue");
            }
        }

public const int MaxMessageIdLength = 128;
```

https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/Constants.cs

https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/Message.cs

I will take a look at how to fix this and submit a PR

**Comment by chriswhellams** [comment]
@NicolasDorier PR sent - I didn't have time to come up with anything fancy to solve this so I just take a hash of the message id to shorten it and then run the generated hash through a validator.

**Comment by NicolasDorier** [comment]
Seems good. Thanks for that. Just wondering why the tests did not caught that.

**Comment by chriswhellams** [comment]
In the test the length of the message Id must be within limits - I am **guessing** that hash lengths are shorter during the test than in the real world ?

**Comment by chriswhellams** [comment]
@NicolasDorier sorry for delay - a busy week. PR sent.
