### ISSUE TITLE
fail: Configuration:  BCH: Unhandled in Waiter loop

### ISSUE THREAD

**Issue by chriswhellams** [dgarage/NBXplorer#105]
I am having an issue getting NBXplorer to work with BCH. 

My node is fully sync'd and NBXplorer is able to make a connection to the node and handshae, however I then get the error

```
fail: Configuration:  BCH: Unhandled in Waiter loop
System.OperationCanceledException: Loading the chain from the node timed out
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation)
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token)
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick)
```
It's a similar problem to this [issue 56](https://github.com/dgarage/NBXplorer/issues/56)

Any ideas much appreciated otherwise I'll have to start debugging the src.

**Comment by NicolasDorier** [comment]
hey, have you tried to whitelist your node on the deamon with `--whitelist=127.0.0.1` ?

**Comment by chriswhellams** [comment]
Hi , ok so I got BCH working using whitelist suggestion above , I turned off BTC and LTC and also set bch.startheight=-1   + bch.rescan=1 which was great...but now when I tried to re-enable BTC (which has been working perfectly) it stopped working with the same error !

**Comment by NicolasDorier** [comment]
@chriswhellams I think the problem is that bch have the same p2p port as bitcoin.
For NBX use `--bch.nodeendpoint=127.0.0.1:3828`, in bch config use `port=3828`. Then blame BCH for being to lazy to pick their own default :/

**Comment by chriswhellams** [comment]
arghhhh ! yep, makes sense. Ok I will try it and report back. 

I don't think it's lazy BCH developers - it's like a religion, they are the one true Bitcoin so those ports "belong" to them ...you can join the conversation here https://github.com/Bitcoin-ABC/bitcoin-abc/issues/25
;-)

**Comment by chriswhellams** [comment]
@NicolasDorier many thanks - the port change worked. BTC and BCH happily working together now
