### ISSUE TITLE
GetTransactions() pagination

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#109]
Hi @NicolasDorier , Long time no nag... :-P 
Until now I was getting *all* transactions, and doing the pagination myself. But I think this is not efficient in case of large volumes.

Is pagination supported for `GetTransactions`?
From what i understand in the code, there is no "limit" for `GetTransactions`, and all transactions will be returned for a given derivation.
From the `Repository`:
```csharp
...
var transactions = _Engine.Do(tx =>
{
    var table = GetTransactionsIndex(tx, pubkey);
    tx.ValuesLazyLoadingIsOn = false;
    var result = new List<TransactionMatchData>();
    foreach (var row in table.SelectForwardSkip(0))
    {
    ...
```

Am i right about my observation?

**Comment by NicolasDorier** [comment]
Yes, would be nice to have pagination.

**Comment by bazooka70** [comment]
Just to be sure, if I set `SelectForwardSkip(limit)` job is done? 
How to approach this new feature?
Will the response have to report how many *total* transactions there are? 
Any thoughts?

**Comment by NicolasDorier** [comment]
I don't remember you have to test.

**Comment by bazooka70** [comment]
OK. Thank you.

**Comment by bazooka70** [comment]
Oh, and i meant something like:
`SelectForwardSkip(page * tx_per_page).Take(limit)`

**Comment by NicolasDorier** [comment]
yes, should work

**Comment by NicolasDorier** [comment]
@bazooka70 just pinging you here since you developped the `rescan a transaction` feature before.

I just released https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#scan-utxo-set which work only on bitcoin core 0.17.0. With this, you don't restore the whole transaction history, but you get back the balance of your wallet, as well as your UTXOs.

**Comment by bazooka70** [comment]
@NicolasDorier , Thanks! this looks like a great new feature. : +1:

**Comment by NicolasDorier** [comment]
@bazooka70 in both, GetTransactions and GetUTXOs I depends on fetching everything in memory first. So last 2 weeks I instead spent time to make it possible to prune history so that even a big wallet stays efficient if it has few UTXOs.
