### ISSUE TITLE
Why does GetUTXOs expects my ex private key?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#11]
Why can't we query public addresses such as "mkE9yyrgdttSRY7UYQLVUHVY9g7Saqh2Qv"?

**Comment by NicolasDorier** [comment]
It expect your HD PUBLIC key.

It does not support address querying, NBXplorer has been done to track wallet funds, not individual addresses (for this you need qbit).

If you only need to receive on a wallet and send from though, NBXplorer fit the goal.

**Comment by bazooka70** [comment]
OK, I guess that makes sense. and I missed the fact that CreateDirectDerivationStrategy expects an `ExtPubKey `. Can I use old HD public (before I run first NBXplorer ) since the `btc.startheight=-1` will it catch up older transactions?

**Comment by NicolasDorier** [comment]
yes but you can but I think it will be slow.
