### ISSUE TITLE
Invalid Derivation Scheme Exception with GetTransactionsAsync

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#111]
GetTransactionsAsync theows with msg invalid derivation scheme, the dv scheme I set to P2PKH and also tried P2WPKH (Segwit) , I am calling NBXClient.Track(NBXDerivation) before attempting this. 

GetTransactionsResponse txs = Task.Run(async () =>
            {
                return await NBXClient.GetTransactionsAsync(NBXTrackingStrategy, null, false);
            }).Result;
 
   getting:
 
One or more errors occurred. (Invalid derivation scheme)
 
Stack:
 
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at BTCLib.BTCCore.QueryTransactions()
   at BTCLib.BTCCore.ReceiveConfirmedTransactions()
 
Tried 2 schemes:
 
case DERIVATION_TYPES.DVTYPE_P2PKH:
                        opts = new DerivationStrategyOptions { Legacy = true, P2SH = false };
                        NBXTrackingStrategy = NBXNetwork.DerivationStrategyFactory.CreateDirectDerivationStrategy(sfe.ExtKey.Neuter(), opts) as DirectDerivationStrategy;
                        break;
case DERIVATION_TYPES.DVTYPE_P2WPKH:
                        opts = new DerivationStrategyOptions { Legacy = false, P2SH = false };
                        NBXTrackingStrategy = NBXNetwork.DerivationStrategyFactory.CreateDirectDerivationStrategy(sfe.ExtKey.Neuter(), opts) as DirectDerivationStrategy;
                        break;
 
Thanks
Appreciated

**Comment by NicolasDorier** [comment]
I need repeatable code. It may happen because you are using a Mainnet string in a Testnet environment or vis versa

**Comment by NicolasDorier** [comment]
Have you check your `NBXNetwork` is correct? Can you tell me what `NBXTrackingStrategy` is equal to?

**Comment by NicolasDorier** [comment]
```
GetTransactionsResponse txs = Task.Run(async () =>
        {
            return await NBXClient.GetTransactionsAsync(NBXTrackingStrategy, null, false);
        }).Result;

```

wtf is that?

```
private async Task<GetTransactionsResponse> QueryTransactions()
    {
        GetTransactionsResponse txs = await NBXClient.GetTransactionsAsync(NBXTrackingStrategy, null, false);

        return txs;
    }
```

**Comment by sixjac** [comment]
"wtf is that?" works also, check it

**Comment by NicolasDorier** [comment]
I know, it is just very very ugly code which might lead to deadlock under the load.

**Comment by sixjac** [comment]
"Can you tell me what NBXTrackingStrategy is equal to?" What data from that do you want exactly?

**Comment by NicolasDorier** [comment]
`NBXTrackingStrategy`

**Comment by sixjac** [comment]
It is of type DerivationStrategyBase

 case DERIVATION_TYPES.DVTYPE_P2WPKH:
                         opts = new DerivationStrategyOptions { Legacy = false, P2SH = false };
                        NBXTrackingStrategy = NBXNetwork.DerivationStrategyFactory.CreateDirectDerivationStrategy(sfe.ExtKey.Neuter()) ;

**Comment by NicolasDorier** [comment]
`Console.Write(NBXTrackingStrategy);`

**Comment by sixjac** [comment]
NBXplorer seems to be throwing in DestinationModelBinder.cs:

    try
			{
				var data = new 
    DerivationStrategy.DerivationStrategyFactory(network.NBitcoinNetwork).Parse(key); // Here
				if(!bindingContext.ModelType.IsInstanceOfType(data))
				{
					throw new FormatException("Invalid destination type");
				}
				bindingContext.Result = ModelBindingResult.Success(data);
			}
			catch { throw new FormatException("Invalid derivation scheme"); } // HERE

Even I just create basic strategy on mainnet with:
    DerivationStrategyBase    NBXTrackingStrategy = 
    NBXNetwork.DerivationStrategyFactory.CreateDirectDerivationStrategy(new 
    ExtKey().Neuter()); // As per NBitcoin book example


    This line: DerivationStrategy.DerivationStrategyFactory(network.NBitcoinNetwork).Parse(key); causes 
    exception

Please try to reproduce by creating basic strategy with new ExtKey().Neuter() on main net BTC chaincode and call Client.Track(Strategy);

Thanks

**Comment by NicolasDorier** [comment]
give me a repro, something I can copy paste.

**Comment by sixjac** [comment]
Looks like i resolved it
