### ISSUE TITLE
Loading the chain from the node timed out

### ISSUE THREAD

**Issue by enorrmann** [dgarage/NBXplorer#118]
Running bitcoind 0.17 from linux  4.15.0-36 x84 64 on TESTNET
I get this trace

enorrmann@enorrmann-cx:~/git/NBXplorer$ ./run.sh --testnet
info: Configuration:  Data Directory: /home/enorrmann/.nbxplorer/TestNet
info: Configuration:  Configuration File: /home/enorrmann/.nbxplorer/TestNet/settings.config
info: Configuration:  Network: Testnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Testnet
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Testing RPC connection to http://localhost:18332/
info: Configuration:  Starting Azure Service Bus Message Broker
Hosting environment: Production
Content root path: /home/enorrmann/git/NBXplorer/NBXplorer/bin/Release/netcoreapp2.1/
Now listening on: http://127.0.0.1:24445
Application started. Press Ctrl+C to shut down.
info: Configuration:  BTC: RPC connection successfull
info: Configuration:  BTC: Full node version detected: 170000
info: Configuration:  BTC: Loading chain from node (127.0.0.1:18333)...
fail: Configuration:  BTC: Unhandled in Waiter loop
System.OperationCanceledException: Loading the chain from the node timed out
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /home/enorrmann/git/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 376
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /home/enorrmann/git/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 284
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /home/enorrmann/git/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 197

**Comment by enorrmann** [comment]
seems to be same as https://github.com/dgarage/NBXplorer/issues/105

**Comment by enorrmann** [comment]
sorry, not closed .. now it connects to bitcoind, but times out after a few seconds

**Comment by NicolasDorier** [comment]
ah maybe try to add 

`bind=127.0.0.1:18333`

**Comment by enorrmann** [comment]
> ah maybe try to add
> 
> `bind=127.0.0.1:18333`

yes ! adding bind=127.0.0.1:18333 to bitcoin.conf did the trick
thank you very much
