### ISSUE TITLE
Not getting Transaction information

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#119]
Still unable to receive transaction information back with remote connection to NBXplorer server, code below:

    var src = TrackedSource.Create(ActiveReceiveAddress);
    NBXClient.TrackAsync(src).GetAwaiter().GetResult();
    GetTransactionsResponse txs = NBXClient.GetTransactions(NBXTrackingStrategy, null);

Just using static address for this, generating with following method:

    public string ReceiveAddress()
    {
        if( sfe != null )
        {
            PubKey pk = sfe.GetPubKey(0, HdPathType.Receive, null);

             if (pk != null)
             {
                BitcoinPubKeyAddress addr = pk.GetAddress(sfe.Network);

                if (addr != null)
                {
                    ActiveReceiveAddress = addr;
                    return addr.ToString();
                }
            }
        }
        return "";
    }

GetTransactionsResponse always returning 0 count for confirmed and unconfirmed transactions even when BTC was sent to the tracking address via coinfaucet.eu on testnet, I have also rebuilt client with NBXplorer latest updates.

Any clue? Thanks

**Comment by NicolasDorier** [comment]
NBXplorer only know about transactions from the time you called `TrackAsync` and don't know anything about the past.

**Comment by sixjac** [comment]
But isn't it correct if I set rescan = 1 in settings.conf file or call RescanAsync from API NBXplorer will rescan chain to get previous history transactions?

I attempted to get transactions confirmed & unconfirmed just 5-10 minutes after sending the testnet BTC to my testnet addrerss.....

Thanks

**Comment by NicolasDorier** [comment]
You need `rescan = 1` but as well as `btcstartheight=SOMEHEIGHT`

It will be very very slow though, you should not do this.
I am working on a better solution that we can use thanks to bitcoin core 0.17.0

**Comment by sixjac** [comment]
Thanks for the quick reply, what btcstartheight value for the chains base (1st mined block).

The solution you are working on sounds interesting, how far off do you estimate?

Thanks

**Comment by NicolasDorier** [comment]
Something between 2 days and 2 months

**Comment by sixjac** [comment]
Ok, please keep me posted, thanks

**Comment by sixjac** [comment]
Hi Nicolas,

Are you still going with these updates or are they done?

Thanks

Regards,
Sean Ryan

________________________________

**Comment by NicolasDorier** [comment]
I actually did in latest version https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#scan-utxo-set

**Comment by sixjac** [comment]
Thanks Nicolas

Regards,
Sean Ryan

________________________________
