### ISSUE TITLE
bitcoind 0.16 removed getinfo RPC

### ISSUE THREAD

**Issue by djpnewton** [dgarage/NBXplorer#12]
It looks like nbxplorer needs to be updated to use one of the new replacement RPCs

**Comment by nopara73** [comment]
There is a new `-getinfo` (not the old `getinfo`) which may be used here. I bumped into it: https://github.com/bitcoin/bitcoin/pull/12540

**Comment by djpnewton** [comment]
It looks like getinfo might only be used to get the version number (https://github.com/dgarage/NBXplorer/blob/66a82d27b685c077e5a929224685d394327ce157/NBXplorer/Configuration/RPCArgs.cs#L136) if so it can probably easily be replaced with a new RPC

**Comment by NicolasDorier** [comment]
indeed, will fix today.
