### ISSUE TITLE
Can't connect to my local Bitcoin Core

### ISSUE THREAD

**Issue by danbadjar** [dgarage/NBXplorer#122]
Hello,
I'm testing NBXplorer but I have this error:

info: Configuration:  BTC: Testing RPC connection to http://127.0.0.1:8332/
fail: Configuration:  BTC: Error connecting to RPC server The remote server returned an error: (401) Unauthorized.

On my bitcoin.con I have:

rpcuser=user
rpcpassword=password
rpcport=8332

On my NBXplorer settings.conf I have:

btc.rpc.url=http://127.0.0.1:8332/
btc.rpc.user=user
btc.rpc.password=password

Is this an issue or should I check other?
Thanks in advice

**Comment by NicolasDorier** [comment]
very often this error is because you are runnning another bitcoind on your machine on the same port or bitcoin.conf is not read by your bitcoind for some reason.

**Comment by danbadjar** [comment]
Hi and thanks for your response.
I have just one instance of bitcoin on my machine and my local open ports are 8333 and 8332
Do you have any other idea?

**Comment by danbadjar** [comment]
If I user bitcoind .cookie it works!

**Comment by ArduinoMasterInfernal** [comment]
hello, same error for me did you solve it ?
