### ISSUE TITLE
ExplorerClient.Network.SupportEstimatesSmartFee not available in 1.0.3.3 | Breaks BTCPayServer 

### ISSUE THREAD

**Issue by sigHash** [dgarage/NBXplorer#124]
Hi there! 
I bumped NBXplorer version for BTCPayServer and realized SupportEstimatesSmartFee is no longer available. Not sure it's a bug or not, just wanted to mention.

**Comment by NicolasDorier** [comment]
Not a bug. If EstimatesSmartFee is not supported, I fallback on EstimateFee at nbxplorer level, so nobody should care about it.
