### ISSUE TITLE
Can't find transaction

### ISSUE THREAD

**Issue by amirh-esmz** [dgarage/NBXplorer#125]
```
            var network = new NBXplorerNetworkProvider(NetworkType.Testnet).GetBTC();

            var client = new ExplorerClient(network);

            client.WaitServerStarted();

            var txResult = client.GetTransaction(new uint256("0acb6e97b228b838049ffbd528571c5e3edd003f0ca8ef61940166dc3081b78a"));
```
cant find tx and txResult  is null
Am i doing something wrong?

**Comment by NicolasDorier** [comment]
NBXplorer know only transactions which satisfy both:

1. Have been confirmed after the node got online for the first time
2. Is matching an address that you are tracking

**Comment by amirh-esmz** [comment]
Is there a way to find tx without tracking address?

**Comment by amirh-esmz** [comment]
is NBXplorer Suitablefor using in a web wallet?
can it handle thousands of addresses?
where does NBXplorer  hold tracked data , in ram or file?

**Comment by NicolasDorier** [comment]
Yes. NBXplorer is suitable for tracking a web wallet.

NBXplorer tracks only your addresses and the transactions that involve an address you are tracking inside a embedded file database.

**Comment by sixjac** [comment]
> Yes. NBXplorer is suitable for tracking a web wallet, even big one if you activate `--autopruning=x`
> 
> NBXplorer tracks only your addresses and the transactions that involve an address you are tracking inside a embedded file database.
> 
> In case you restore an old wallet, NBXplorer will not show past transaction nor the correct balance. You need to call Scan UTXO as documented in the API to get back your UTXOs and some of the transactions.

So if restore old wallet call ScanUTXOsAsync to dig up missing transactions and balance then after that do need to call Client.RescanAsync(new RescanRequest{Transaction}) to get all missing transactional information?????????????

Thanks

**Comment by NicolasDorier** [comment]
`Client.Rescan` is not well named. It basically allow you to manually input in NBXplorer database transactions and blocks from the history. But if you do this you need to be sure you are not missing any transaction or your balance will be corrupted.

**Comment by sixjac** [comment]
ScanUTXOsAsync gets balance for restored wallet but not old transaction information, how t get old transaction information in addition to balance?

Thanks

**Comment by NicolasDorier** [comment]
You need to use this call https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#rescan-a-transaction to manually restore all your old transactions.
