### ISSUE TITLE
Persisting the docker volume and having NBXplorer get re-deployed frequently 

### ISSUE THREAD

**Issue by sigHash** [dgarage/NBXplorer#127]
Hi @NicolasDorier 

Can I make NBXplorer reuse a docker volume (assuming that I have a way of making that volume persist regardless of the life cycle of the container) if it gets built and redeployed frequently?

**Comment by sigHash** [comment]
Cool! I wanna use REX-Ray. Any comment?

**Comment by NicolasDorier** [comment]
no idea what that is

**Comment by sigHash** [comment]
It's basically a driver that abstracts away the persistent storage from docker. Thanks anyway.
