### ISSUE TITLE
Address tracking limits

### ISSUE THREAD

**Issue by eabz** [dgarage/NBXplorer#128]
Hey @NicolasDorier 
I was testing the NBXplorer, I was trying to see how much HD wallets derivated address is capable of tracking, I created a `m/44'/5'/0'/0/2000`derivated address and the NBXplorer doesn't detect. Do you know what are the limits?

**Comment by NicolasDorier** [comment]
`--help` check mingaplimit

**Comment by eabz** [comment]
Got it, thanks!
By the way, are you planing to update NBitcoin Nuget soon?

**Comment by NicolasDorier** [comment]
I did already

**Comment by eabz** [comment]
Yes. But I need the Nbitcoin.Altcoin Nuget to integrate the PR you merged 5
6 days ago.

**Comment by eabz** [comment]
Thanks!

**Comment by sigHash** [comment]
So If I need to track all the children of a derivation scheme,  I have to set --maxgap size to 2^32 -1?

In my use case, the derivation scheme is tracked by NBXplorer but addresses are generated offline without making call to NBXplorer and I have no  control on which child is currently in use.

**Comment by eabz** [comment]
I don't know, but seems NBXplorer is not capable of creating a new address. I just use this endpoint https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#get-a-new-unused-address and get the "keyPath" to create an address locally. The NBXplorer will move normally when an address is used if you are tracking the derivation. 
I think you should avoid tracking single address, I saw some tools using them, and they are a real pain.

**Comment by sigHash** [comment]
@eabz I see! Is there any limit when it comes to address generation? Let's say I wanna create a million addresses on a derivation scheme

**Comment by eabz** [comment]
@sigHash Is not recommended to just create addresses because NBXplorer won't track them. It will only track the next 20 addresses since the last unused, the recomended procedure is to generate a unused address until the user uses it. When the user creates it the NBXplorer will give you a new path.

**Comment by sigHash** [comment]
@eabz Got it. So NBXplorer will detect whether the address is used or not

**Comment by eabz** [comment]
@sigHash seems you are correct, but I didn't see it on the last version.

**Comment by sigHash** [comment]
@eabz I just wanna be able to generate new addresses on-demand and whiteout working about loosing track of them.

Also, Imagine you have a derivation scheme tracked by NBXplorer. You make calls to NBXplorer and after a while you have generated let's say 10,000 addresses. Now If for some reason you loose your NBXplorer datadir and want to start fresh, how would you recover? Would making a Track call on the derivation scheme be enough for NBXplorer to detect all those utxos?

Maybe @NicolasDorier can help us understand

**Comment by eabz** [comment]
I already faced that problem. 
I think Nicolas just added a rescan endpoint on NBXplorer (https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#scan-utxo-set), so far I tested with BTC, but other nodes lack of the RPC call to use it. I run NBXplorer with: BTC, LTC, DASH, POLIS and BCH but only BTC is capable of rescan the wallet. 
To prevent it you can keep a list of xPub derivations and backup it each time you start tracking them.

**Comment by sigHash** [comment]
@eabz  yeah, I just looked at Scan UTXO Set route. I do have a backup of all my derivation schemes. What's the solution for other coins which don't support utxoscan?

**Comment by eabz** [comment]
You can on a fresh install using the post route to add all the derivations for tracking and then run NBXplorer with the --COINrescan option with the --COINstartheight=BLOCK where to start scanning. 
All node will usually do the rescan fast, except BCH and LTC.

**Comment by NicolasDorier** [comment]
@sigHash  When you call `GetUnusudAddress` you can pass a flag `reserve`. It will mark this address as used.

**Comment by NicolasDorier** [comment]
@sigHash the solution is for you to contribute to the coins not supporting it, and add the scanutxoset RPC call.

**Comment by eabz** [comment]
@NicolasDorier Do you know if `scanutxoset`is just a RPC call or it involves db reestructure on a full node? I can give a hand adding support on request if needed.

**Comment by NicolasDorier** [comment]
I don't think it requires restructure.

**Comment by sigHash** [comment]
> @sigHash When you call `GetUnusudAddress` you can pass a flag `reserve`. It will mark this address as used.

If I don't set the `reserve` flag, will the address automatically be marked as "used" as soon as NBXplorer receives a new transaction event on that keyPath?
