### ISSUE TITLE
Connecting from another machine in the same network?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#13]
I am trying to connect to NBXplorer which runs fine on localhost and listens on ports 24444 and 24445 (testnet). Everything works fine from inside this machine on localhost. Now trying to run from a machine in the same network.

```
var _network = new NBXplorerNetworkProvider(ChainType.Main).GetBTC();
Uri _uri = new Uri(@"http://83.100.110.50:24444"); 
ExplorerClient client = new ExplorerClient(_network, _uri);
var fee = client.GetFeeRate(6); // <-- exception here

```
I have set `noauth=1` in the config and also tried running with `--noauth` switch but when trying to connect from  other machine  I get an exception `SocketException: No connection could be made because the target machine actively refused it 83.100.110.50:24444`. Trying to connect via `telnet 83.100.110.50  24444` also fails.

The firewall is disabled and I don't see anything wrong. What could be casing this?

Thanks a million!

**Comment by NicolasDorier** [comment]
use `-bind 0.0.0.0` I don't advise to run nbxplorer open on internet, you might get DDoS

**Comment by bazooka70** [comment]
@NicolasDorier, Thanks! it works now.
regarding DDoS, Our firewall only allows incoming requests from inside the network.

**Comment by NicolasDorier** [comment]
--noauth remove authentication. By default nbxplorer requires the client to know a username/password which is generated into a cookie file at startup.

If you are in a secure environment you can put `--noauth`
