### ISSUE TITLE
NBXplorer randomly exits

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#132]
NBXplorer randonly shuts itself off, cant see any logs, running with Bitcoin Full Node Ubuntu with args:

./run.sh --chains btc --network testnet --btcrpcuser user--btcrpcpassword pass --noauth

NBXplorer Setting.config and screenshot attached
<img width="495" alt="untitled" src="https://user-images.githubusercontent.com/4453138/48411990-9dbc7980-e743-11e8-8d26-c3ef12947b8e.png">
[settings_example.txt](https://github.com/dgarage/NBXplorer/files/2576131/settings_example.txt)

**Comment by NicolasDorier** [comment]
mmh that's bad. Taking a look at it.

**Comment by sixjac** [comment]
Appreciate it

**Comment by NicolasDorier** [comment]
Are you connecting via websocket while it is running? Are you using the latest version?

**Comment by NicolasDorier** [comment]
Are you using queues?

**Comment by sixjac** [comment]
It is running on Ubuntu vps server, I connect:

    NBXClient = new ExplorerClient(NBXNetwork, new Uri("address:24445"));

From mobile app

Yes deleted old version, pulled new and rebuilt

**Comment by sixjac** [comment]
> Are you using queues?

No

**Comment by NicolasDorier** [comment]
are you using the notifications?

**Comment by NicolasDorier** [comment]
I pushed a new commit. Maybe it will solve it, or at least, not crashing. Can you try again?

**Comment by sixjac** [comment]
> are you using the notifications?

No

**Comment by sixjac** [comment]
> I pushed a new commit. Maybe it will solve it, or at least, not crashing. Can you try again?

Will try now

**Comment by sixjac** [comment]
Ok seems to have fixed it, closing for now. Not sure if NuGet push is also needed... Thanks

**Comment by NicolasDorier** [comment]
No exception going on in the logs?

**Comment by sixjac** [comment]
I could not see any logs, perhaps cannot find folder, there is also something weird happening like a call to:

    NBXClient.GetStatusAsync().GetAwaiter().GetResult();

never returns and throws an exception in my client, this never used to happen, not sure if anything to do with new build or not

**Comment by sixjac** [comment]
Crashed again, can ypu tell me where the logs get dumped to by default?

**Comment by NicolasDorier** [comment]
might it be killed by OOM killer because you don't have enough RAM?

**Comment by sixjac** [comment]
> might it be killed by OOM killer because you don't have enough RAM?

- HDD space 500 GB

- memory usage (RAM) 6 GB

- CPU 2 cores

**Comment by NicolasDorier** [comment]
can you monitor how the RAM goes? It seems you are rescanning lots of block with NBXplorer. NBXplorer is not made for doing big rescan, so this might be the issue.

**Comment by sixjac** [comment]
> can you monitor how the RAM goes? It seems you are rescanning lots of block with NBXplorer. NBXplorer is not made for doing big rescan, so this might be the issue.

Ok yes I will but as I said in the past I need to rescan (-txindex=1) to get past transactions from all time ie: block 1 to current block height

**Comment by eabz** [comment]
I don't know if is related. But I experience the same when I was resyncing a Bitcoin Cash node. The solution was solved by increased the number of Cores on the VPS. I think the process crashed because if CPU overload.

**Comment by sixjac** [comment]
> I don't know if is related. But I experience the same when I was resyncing a Bitcoin Cash node. The solution was solved by increased the number of Cores on the VPS. I think the process crashed because if CPU overload.

Thanks eabz, something for me to monitor. Cheers

**Comment by NicolasDorier** [comment]
NBX itself should not rescan. It is not made for this. But well, I can try to fix it if we identifiy where is the problem.

**Comment by sixjac** [comment]
> NBX itself should not rescan. It is not made for this. But well, I can try to fix it if we identifiy where is the problem.

Ok will keep open and let you know

**Comment by eabz** [comment]
The problem is only with BTC and BCH rescan those blockchains are very big. Maybe you can disable BTC rescan, with the scanutxoset, you don't need the rescan. And for BCH, maybe I can make a PR to include that RPC

**Comment by sixjac** [comment]
> The problem is only with BTC and BCH rescan those blockchains are very big. Maybe you can disable BTC rescan, with the scanutxoset, you don't need the rescan. And for BCH, maybe I can make a PR to include that RPC

But apparently if I do not rescan I cannot query any arbitrary transaction which will render a wallet basically useless

**Comment by sixjac** [comment]
@eabz what do you mean exactly by "make a PR to include that RPC"


Thanks

**Comment by eabz** [comment]
I think Nicolas integrated a new endpoint on NBX that will scan a unique HD wallet. I think is a good alternative to full rescan. But that endpoint is base on a RPC command integrated on Bitcoin Core 0.17. No other coin has it. I am working to backport it on Polis. But other coins dev process is not that fast.

**Comment by sixjac** [comment]
> I think Nicolas integrated a new endpoint on NBX that will scan a unique HD wallet. I think is a good alternative to full rescan. But that endpoint is base on a RPC command integrated on Bitcoin Core 0.17. No other coin has it. I am working to backport it on Polis. But other coins dev process is not that fast.

@eabz Ok thanks

@NicolasDorier is the docs on this "new endpoint on NBX that will scan a unique HD wallet"? Thanks

**Comment by eabz** [comment]
https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#scan-utxo-set

**Comment by sixjac** [comment]
@eabz cheers

**Comment by sixjac** [comment]
> https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#scan-utxo-set

@NicolasDorier @eabz anymore information on use case for this?

I use:
    NBXClient.GetScanUTXOSetInformationAsync(NBXTrackingStrategy).GetAwaiter().GetResult().Status;

and the output on my VPS server scans which is fine but I always get back 0 UTXOs, the testnet address I use is recent and sent funds there 2 days ago from coinfaucet.eu

Pointers appreciated, not the C++ kind ;)

**Comment by NicolasDorier** [comment]
can you share your `NBXTrackingStrategy` ?

**Comment by NicolasDorier** [comment]
and the address

**Comment by sixjac** [comment]
// P2PKH
NBXTrackingStrategy = NBXNetwork.DerivationStrategyFactory.CreateDirectDerivationStrategy(_key);
NBXClient.TrackAsync(NBXTrackingStrategy).GetAwaiter();

Testnet address:
mvME4ueW3ZPcr2VFLDHP8yPr3Pvdidn347

Then when scan status is completed I fire event that calls:
NBXClient.GetTransactions(NBXTrackingStrategy, null);
To get transactions information, confirmed, unconfirmed and bookmarked always 0

**Comment by NicolasDorier** [comment]
I need NBXTrackingStrategy

**Comment by sixjac** [comment]
> I need NBXTrackingStrategy

is not specific so the attached is what I interpreted you wanted......
<img width="758" alt="untitled" src="https://user-images.githubusercontent.com/4453138/48625609-090a8380-e9b0-11e8-81a5-68b3af02d9ba.png">

**Comment by NicolasDorier** [comment]
please copy paste here.

**Comment by NicolasDorier** [comment]
anyway, the testnet address does not correspond to this derivation scheme. Your address is P2SH your derivation scheme is segwit.

**Comment by NicolasDorier** [comment]
Please, use NBXplorer to derive correctly the addresses with GetUnused.

**Comment by sixjac** [comment]
> please copy paste here.

tpubD8MVf5PASUAuHwtMHKas7pCvgbhsiH2MJeP5ZqavT3G52eiuY7K1dPq8ARUNgFtCdnSHYrDjtkfjLewao6PHHjELybEr2pTMvEYtRaZHXbr

**Comment by sixjac** [comment]
> Please, use NBXplorer to derive correctly the addresses with GetUnused.

You mean GetUnused instead of GetTransactions??

The docs are not clear enough to know how to use 100% correctly

**Comment by sixjac** [comment]
> anyway, the testnet address does not correspond to this derivation scheme. Your address is P2SH your derivation scheme is segwit.

I will try this

**Comment by sixjac** [comment]
> Please, use NBXplorer to derive correctly the addresses with GetUnused.

A small code example on how to get Transaction info would be great 

ie: Transaction ID, receiver address, Utxo's and inputs, etc...

since I do not yet know how to use NBXplorer 100% correctly

**Comment by NicolasDorier** [comment]
https://programmingblockchain.gitbook.io/programmingblockchain/wallet/web-api

**Comment by sixjac** [comment]
> https://programmingblockchain.gitbook.io/programmingblockchain/wallet/web-api

Thanks but this does not change anything, calling GetUTXOs still gives me nothing, as I said before I am using ScanUTXOSetAsync to try and get all transaction history for a given address and that is not working....

What is the point of having a block explorer that cannot get all transaction information for a given BTC address??????????????????????

**Comment by sixjac** [comment]
Ok I get it now, NBXplorer has to be tracking a given address before a transaction happens and will not track any transactions that happened before tracked....

**Comment by NicolasDorier** [comment]
it does with ScanUTXOSetAsync if your address is part of your derivationScheme, this is not your case.
