### ISSUE TITLE
Wrong headers not matching RPC or missing HeaderPayload

### ISSUE THREAD

**Issue by eabz** [dgarage/NBXplorer#133]
Hello.
I am having two issues. 
1. Trying to sync a coin named COLX, seems the node doesn't send HeaderPaylod (https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/Protocol/Node.cs#L1250). I think that's normal on old coins (Old DASH and PIVX forks) Is there another approach? Maybe I can try to setup a RPC call for total Blocks and get the headers on a loop. 
2. Trying to sync a new coin named GIN. Seems that headers from RPC and headers calculated, doesn't match. That may be something based on the algorithms used.

**Comment by NicolasDorier** [comment]
no header first sync, no NBX support. There is no workaround. You need to fix the altcoin tests at NBitcoin level.
