### ISSUE TITLE
how NbXplorer works

### ISSUE THREAD

**Issue by amirh-esmz** [dgarage/NBXplorer#134]
hi
this is not a issue 
I just want to know how NBXplorer knows a address (or Script) is derived from ExtPubKey?

**Comment by NicolasDorier** [comment]
It generates them using BIP32 as explained https://programmingblockchain.gitbook.io/programmingblockchain/key_generation/bip_32 . Then save in DB. When a tx come that match a script in the DB, it mark it as part of the wallet.

**Comment by amirh-esmz** [comment]
But how it detects childs of a tracked ExtPubKey?

**Comment by NicolasDorier** [comment]
It looks in the DB if the scriptPubKey is attached to a ExtPubKey.

**Comment by NicolasDorier** [comment]
* Derive the scriptPubKey from master
* Save scriptPubKey in DB
* lookup every scriptPubKeys in transactions if it exists in DB

**Comment by amirh-esmz** [comment]
So must save 2^31 scriptPubKeys for every master key

**Comment by amirh-esmz** [comment]
i track masterKey like this
```
            var network = new NBXplorerNetworkProvider(NetworkType.Testnet).GetBTC();
            var client = new NBXplorer.ExplorerClient(Nnetwork);

            var masterKey = new ExtKey();
            var userDerivationScheme = Nnetwork.DerivationStrategyFactory.CreateDirectDerivationStrategy(masterKey.Neuter()
            ,new DerivationStrategyOptions()
            {
                Legacy = true
            });
            client.Track(userDerivationScheme);

```
and when i receive money on 
`masterKey.Derive(1).ScriptPubKey`
nbxplorer can detect it .
My question is how NbXplorer can detect derived addresses when i only track masterKey?

**Comment by NicolasDorier** [comment]
> So you have to save 2^31 scriptPubKeys for every key with 1 depth

@amirh-esmz this is where the concept of "gap limit" comes into play. You can configure `mingapsize` and `maxgapsize`.

I generate addresses of the xpub on 3 branches, "0/x", "1/x" and "x". I generate `maxgapsize` of them and put them in the DB. Everytimes one got marked used (either seen on the chain, or reserved), I check how many I am still tracking ahead. If it goes below `mingapsize`, I generate until I have `maxgapsize` ahead. By default `mingapsize=20` and `maxgapsize=30`

**Comment by amirh-esmz** [comment]
Ok
Now it makes sense 
Thanks for your time

**Comment by NicolasDorier** [comment]
Also, I replaced the concept of Xpub with "DerivationScheme" which is more flexible (you can have multisig/segwit/p2sh or whatever kind of wallet you want)
