### ISSUE TITLE
If you use `nxplorer.GetUTXOs` NBXplorer gives you the keypaths you need to use for spending each coin it returns.

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#136]
[Can see an example here](https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html).

`var keys = utxos.GetKeys(userExtKey);` basically read those KeyPath and derive `userExtKey` to extract all the keys required to sign.

_Originally posted by @NicolasDorier in https://github.com/dgarage/NBXplorer/issues/76#issuecomment-408603919_

**Comment by sixjac** [comment]
> [Can see an example here](https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html).

Link does not go to the exact example
> 
> `var keys = utxos.GetKeys(userExtKey);` basically read those KeyPath and derive `userExtKey` to extract all the keys required to sign.
> 
> _Originally posted by @NicolasDorier in [#76 (comment)](https://github.com/dgarage/NBXplorer/issues/76#issuecomment-408603919)_

Where does userExtKey come from, I am using my Safe.ExtKey with utxos.GetKeys and nullreference exception somewhere in NBitcoin..... So that is why i ask "where is "userExtKey coming from??

Thanks

**Comment by NicolasDorier** [comment]
No idea what `Safe.Extkey` is. Extkey comes from your wallet, read about BIP32 and BIP39 on https://programmingblockchain.gitbook.io/programmingblockchain/key_generation/bip_32

**Comment by sixjac** [comment]
Sorry no matter what ExtKey i give to UTXOS.GetKeys(ExtKey) it throws null reference exception, stack trace:

at NBitcoin.ExtKey.Derive(KeyPath derivation)
   at NBXplorer.Models.UTXOChanges.<>c__DisplayClass24_0.<GetKeys>b__0(UTXO u)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at BTCLib.BTCCore.BuildAndSend(String address, Double amount, Double feesats)

I am obviously missing something here..... my ExtKey is NOT null

**Comment by NicolasDorier** [comment]
how do you get `UTXOS`

**Comment by NicolasDorier** [comment]
My guess: You are trying to use `Track` on single address, and spend from HD keys. You should not do this.
Use proper `derivationScheme` to `Track` and use `GetUTXOs` with it. Do not use individual addresses.

**Comment by sixjac** [comment]
Yes was using single address, now changed to derivation scheme.

Thanks
