### ISSUE TITLE
Ignore Derivation Tracking

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#138]
I generate my wallets and keys in a different API not via Derivation Scheme so they are not tracked because of this, I can use NBXplorer functions fine with TrackedSource feeding it BitcoinAddress however not all functions support feeding TrackedSource instead on DerivationStrategy such as: GetKeyInformationsAsync which is now depricated.

Can I use NBXplorer without using DerivationScheme? KeyPath information on a valid address with UTXOs comes back null when not using Derivation Tracking

**Comment by chriswhellams** [comment]
I had a similar scenario and similar issues. @NicolasDorier has done a great job with NBXplorer but  it is fundamentally designed a certain way and trying to work against that will lead to much frustration. I'm using HD wallets and the solution I found in the end was to use the NBExplorer API to request address and put in the index key of the address I already created or walk the addresses forward in the API by incrementing the key and request the address. Any address you request from NBXplorer will be tracked. If you go through the source code you'll find that the tracked keys are written to the database so another method would be to directly write to the database - but you will then need to bounce (re-start) NBXplorer I think. Hope that makes sense.

**Comment by sixjac** [comment]
Thanks for the reply @chriswhellams I will need to look into it, as long as I can use my wallets format NBitcoin Key it should work out. Cheers

**Comment by sixjac** [comment]
@chriswhellams thanks, would have been easier if I had of not tried to figure ways around it :)

Using GetUnusedAsync(NBXTrackingStrategy, DerivationFeature.Direct).GetAwaiter().GetResult() indeed solves my issue, I do have a question though, each time the above is called a new key is generated, how do I get the same one as previously generated instead of a unique new one? Thanks

**Comment by sixjac** [comment]
Nevermind, figured it out i think: 
    NBXTrackingStrategy.Root.PubKey.GetAddress(NBXNetwork.NBitcoinNetwork);

**Comment by chriswhellams** [comment]
> Nevermind, figured it out i think:
> NBXTrackingStrategy.Root.PubKey.GetAddress(NBXNetwork.NBitcoinNetwork);

Good. Always remember that the 'D' in HD wallet is deterministic - so if you use a library like NBitcoin and ask for the address for a given pubkey and you supply the same path then you always get the same address. You don't have to ask NBXplorer. I recommend reading @NicolasDorier's book https://programmingblockchain.gitbook.io/programmingblockchain if you haven't already as there are very good explanations .

**Comment by sixjac** [comment]
Hi yes I read the book back in July, maybe need a refresher but most of my questions were figuring out with NBXplorer. Thanks for your help again

**Comment by NicolasDorier** [comment]
`GetUnusedAsync(NBXTrackingStrategy, DerivationFeature.Direct).GetAwaiter().GetResult()`

Does not generate new address, it just give you the next unused. If you want to get a new address and consider it "used" even if it is not, you need to pass `reserve: true`.

`GetKeyInformationsAsync is obsolete` but `GetKeyInformationAsync` (no s) is not. You can use `GetKeyInformation` if you only want a way to get an address from xpub/keypath. It is more like a tool.

**Comment by NicolasDorier** [comment]
Also, as `chriswhellams` said: You need to use HD everywhere. Do not pass single addresses to NBXplorer. 

Passing single address to NBXplorer is ONLY needed for some complex scenario like atomic swap, where you need to monitor some transactions. For everything else, you need to use derivation schemes.

**Comment by sixjac** [comment]
@NicolasDorier ok thanks for the information

**Comment by sixjac** [comment]
Really I do not know why I cannot do something like the following:

    ActiveBitcoinAddress = 
    NBXTrackingStrategy.Root.ScriptPubKey.GetDestinationAddress(NBXNetwork.NBitcoinNetwork);
    NBXClient.TrackAsync(TrackedSource.Create(ActiveBitcoinAddress));

     ActiveKeyPath = NBXClient.GetKeyInformationAsync(NBXTrackingStrategy, 
     ActiveBitcoinAddress.ScriptPubKey).GetAwaiter().GetResult(); // Makes Null KeyPathInfo

I do not want to make a GetUnused all the time and I especially do not want to give out a public key to someone to receive payment, I want to derive an address from a pub key and reuse the same address unless the user wants to generate another new address

THX

**Comment by NicolasDorier** [comment]
please please please @sixjac do not use `TrackedSource.Create(ActiveBitcoinAddress)`. Forget that you can do this at all, it is not meant to be used for what you want to use it.

Just track the `NBXTrackingStrategy`, and use `GetUnused(NBXTrackingStrategy)` to get the next usable address.

**Comment by sixjac** [comment]
But every time the user starts the wallet even same keys a new "unused" address will be created everytime, this is wasteful and not necessary the way I look at it.....

**Comment by sixjac** [comment]
With GetUnused if I can mark address as "used/reserve" is there a way to get used addresses also?

**Comment by NicolasDorier** [comment]
@sixjac no it won't if the reserve flag is to false, the next GetUnused will return same address if not used.

**Comment by NicolasDorier** [comment]
If you don't want to waste addresses, why are you reserving it??

**Comment by sixjac** [comment]
> If you don't want to waste addresses, why are you reserving it??

I am not reserving it, it was just a question

**Comment by sixjac** [comment]
> @sixjac no it won't if the reserve flag is to false, the next GetUnused will return same address if not used.

I leave reserve at false but still get new aadresses each time GetUnused called:
tb1qfyudvkk5n3v9qgeewddfjgpku9n35ee728knda
and
tb1qdr7mmxyq7qq45vg89aurllwl0pzapepq4pgyfr

same keys and derivation

**Comment by sixjac** [comment]
A nevermind, I needed to use Deposit not Change address to keep same one.

Thanks

**Comment by sixjac** [comment]
Nope still generating new addresses....

**Comment by sixjac** [comment]
> No, if `reserve` is `false` then you don't get a new address until the address is actually receiving money.
> 
> Check you code again.

"don't get a new address until the address is actually receiving money." this explains it, how can I NOT get a new address regardless of receiving money?

**Comment by NicolasDorier** [comment]
@sixjac NBX will make your life hard to do this. NBX is built under the model that you don't have address reuse. (Do not receive money twice on the same address)

If you go against this model, not only you hurt your own privacy, but you will need more code to achieve your objectives.

**Comment by sixjac** [comment]
GetUnused returns null result when using xpub-[legacy] scheme
    
    GetUnused(Scheme, Derivation.Deposit);

Works fine with Segwit, do you know the reason?

**Comment by NicolasDorier** [comment]
@sixjac it returns null only if you have not `Track(Scheme)` once before.
