### ISSUE TITLE
Subscribing to Notifications in C# API

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#139]
Hi, is there an object existing in C# API to easily subscribe to notifications or do I need to do this manually via Websocket and parsing JSON?

Was looking at something like but is as far as i got, no subscribers:

    var notificationSession = NBXClient.CreateWebsocketNotificationSession();
                        
     notificationSession.ListenDerivationSchemesAsync(new DirectDerivationStrategy[] { 
     NBXTrackingStrategy });

**Comment by NicolasDorier** [comment]
`var evt = await notificationSession.WaitEvent();`

**Comment by sixjac** [comment]
There is no WaitEvent only NextEvent…..

Regards,
Sean Ryan

________________________________

**Comment by NicolasDorier** [comment]
then `nextevent`

**Comment by sixjac** [comment]
Thanks

Regards,
Sean Ryan

________________________________

**Comment by sixjac** [comment]
Hi,

cannot find C# API reference on how to properly subscribe to notification session, it seems straight forward:

    var session = NBXClient.CreateWebsocketNotificationSession();

however this never returns, it is NOT awaitable and does not immediately seem to be an async method going by the function name.

Please how does this work?

**Comment by sixjac** [comment]
CreateWebsocketNotificationSessionAsync() never returns.... more detail on how it works please?

    var notificationSession = NBXClient.CreateWebsocketNotificationSessionAsync().GetAwaiter().GetResult();

**Comment by NicolasDorier** [comment]
Probably nothing to do with nbx, read https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by sixjac** [comment]
NotificationSession has just 2 listeners:
1.) ListenNewBlockAsync
2.) ListenDerivationSchemesAsync

The API spec implies that there is a subscriber "subscribetransaction" and does not say anything about DerivationScheme notifications.......

I am interpreting it it just a refactoring/naming issue and ListenDerivationSchemesAsync actually subscribes to and listens for new transactions as in the API spec? Correct?

Thanks

**Comment by NicolasDorier** [comment]
If you issue is that 

```
 NBXClient.CreateWebsocketNotificationSessionAsync().GetAwaiter().GetResult();
```
never returns, the problem is not about NBXplorer at all but able you using `.GetAwaiter().GetResult()` and provoking a deadlock because of  https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by sixjac** [comment]
No this is not the issue, you have methods "ListenDerivationSchemesAsync" but "ListenDerivationSchemesAsync" is not mentioned anywhere in you're docs, besides new block subscription only the following is mantioned:

{
  "type": "subscribetransaction",
  "data": {
    "cryptoCode": "BTC",
    "derivationSchemes": [
      "tpubD6NzVbkrYhZ4YL91Ez5fdgaBPQbFhedFdn5gQL4tSCJn1usmHsV1L6VokzLbgcqzh9hiBnfnQANp5BYW15QdFGRKspZVSW1v2QY917RDs1V-[legacy]"
    ]
  }
}

**Comment by NicolasDorier** [comment]
example of use

```csharp

				using (var connected = tester.Client.CreateWebsocketNotificationSession())
				{
					connected.ListenAllDerivationSchemes();
                                        connected.ListenNewBlock();  
					tester.SendToAddress(tester.AddressOf(pubkey, "0/1"), Money.Coins(1.0m));

					var txEvent = (Models.NewTransactionEvent)connected.NextEvent(Cancel);
					Assert.Equal(txEvent.DerivationStrategy, pubkey);
					Assert.NotNull(txEvent.Outputs.First().Address);
				}
```

**Comment by sixjac** [comment]
Thanks

**Comment by NicolasDorier** [comment]
Look the tests in NBXplorer, it will teach you how to use the lib.

**Comment by sixjac** [comment]
Ah that is where it is, ok
