### ISSUE TITLE
utxos.GetUnspentCoins returns no coins

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#14]
NBXplorer testnet is running and connected to my node. all seems ok.
I transferred some funds to an address in my wallet (mx4mDjVXkbccko3JseXrjExwUgphPedT7m).
https://live.blockcypher.com/btc-testnet/address/mx4mDjVXkbccko3JseXrjExwUgphPedT7m/

But `utxos.GetUnspentCoins` returns nothing. from the little doc I found here:
https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html

I used this code:
```
// mx4mDjVXkbccko3JseXrjExwUgphPedT7m
string m = "delay into trade deal exile effort badge install wheel despair attitude bike";  
Mnemonic mnemonic = new Mnemonic(m);
ExtKey extMasterKey = mnemonic.DeriveExtKey();
ExtPubKey extPubKey = extMasterKey.Neuter();

Console.WriteLine(extPubKey.GetWif(Network.TestNet)); // tpubD6NzVbkrYhZ4YWoMAvoe58N3rnm7SpBBR7NpVZY75JLo7gBUGLZPrMECFL2jDYGGJ8DrNCZiVPYT7qQV9xc5MFewWNDJphoX2G5ppdsMWmY

// lets check what is my public key:
Key privateKey = extMasterKey.PrivateKey;
BitcoinSecret bitcoinPrivateKey = privateKey.GetWif(Network.TestNet);
BitcoinPubKeyAddress publicAddress = bitcoinPrivateKey.GetAddress(); 
Console.WriteLine(publicAddress); // mx4mDjVXkbccko3JseXrjExwUgphPedT7m

var _network = new NBXplorerNetworkProvider(ChainType.Test).GetBTC();
Uri uri = new Uri(@"http://127.0.0.1:24445");
ExplorerClient client = new ExplorerClient(_network, uri);

DerivationStrategyOptions derivationStrategyOptions = new DerivationStrategyOptions
{                
  Legacy = true // Use non-segwit
};
var userDerivationScheme = _network.DerivationStrategyFactory.CreateDirectDerivationStrategy(extPubKey, derivationStrategyOptions);

client.Track(userDerivationScheme); // do I need this???
var utxos = client.GetUTXOs(userDerivationScheme, null, false);            
var coins = utxos.GetUnspentCoins();
Console.WriteLine(coins.Length); // 0 
foreach (var coin in coins.OrderByDescending(x => x.Amount))
{                
  Console.WriteLine(coin.Amount);
}
```
`coins.Length` retuns 0, although BitconNinja client reports correct balance of 0.004 BTC
What am I doing wrong?

**Comment by NicolasDorier** [comment]
You need to use the correct derivation strategy.

From which wallet are you getting this address above?

**Comment by NicolasDorier** [comment]
Ok track instead

```
"xpub....-[legacy]"
```

Then try again.

**Comment by NicolasDorier** [comment]
Your code seems correct. Checking this a moment.

**Comment by bazooka70** [comment]
I am using the above derivation strategy (as explained in your book) - I might so familiar with this subject yet. so I create a ExtKey and derive the private key and public address from it. I guess there are better derivation strategies. 

```
have you called
client.Track(userDerivationScheme);
Before receiving the money? NBXplorer starts tracking only when you called this.
```

I'm not sure, but I 99% think I did because I was excepting such issue.
As you can see I did call `client.Track(userDerivationScheme);`.

So I sent another funds **now** of 0.005 BTC but still NBXplorer does not see any coins.
https://live.blockcypher.com/btc-testnet/address/mx4mDjVXkbccko3JseXrjExwUgphPedT7m/

While Qbit see correct balance.

**Comment by NicolasDorier** [comment]
@bazooka70 I documented all API here, it might interest you https://github.com/dgarage/NBXplorer/blob/master/docs/API.md

Please copy paste your derivation scheme, I can take a look

**Comment by NicolasDorier** [comment]
Ah sorry I just saw you already copied, I am checking

**Comment by NicolasDorier** [comment]
Ah your problem is here

```
BitcoinPubKeyAddress publicAddress = bitcoinPrivateKey.GetAddress(); 
Console.WriteLine(publicAddress); // mx4mDjVXkbccko3JseXrjExwUgphPedT7m
```

This is not the correct address.

The first address is 

```
var publicAddress = userDerivationScheme.Derive(new KeyPath("0/0")).ScriptPubKey.GetDestinationAddress(Network.TestNet);
```

You should use `NBXplorerClient.GetUnusedAddress` to get an address though. It makes sure you don't reuse twice the same one for the wallet.

**Comment by bazooka70** [comment]
@NicolasDorier , Thanks. I did figured that something was wrong with my derivation  scheme.

I my existing code I used:

ExtKey extKey0 = extMasterKey.Derive(0);
privateKey = extKey0.PrivateKey;
BitcoinPubKeyAddress publicAddress = bitcoinPrivateKey.GetAddress(); 
Console.WriteLine(publicAddress); 
...

And It worked. I could see the balance after sending funds to that public key.

But I'm not sure if this is correct approach. 
When using your:
`var publicAddress = userDerivationScheme.Derive(new KeyPath("0/0")).ScriptPubKey.GetDestinationAddress(Network.TestNet);`

I get a **different** first Public key. Why is that? should I be using your derivation scheme instead of mine?

> You should use NBXplorerClient.GetUnusedAddress to get an unused address though. It makes sure you don't reuse twice the same one for the wallet.


Currently we use only **one** public key in our wallet and reusing this address (for change also). but we want it to be HD ready for later.... I know its considered a privacy issue, but this is not my depression.

**Comment by NicolasDorier** [comment]
> Currently we use only one public key in our wallet and reusing this address (for change also). but we want it to be HD ready for later.... 

Well it is a shame because NBXplorer make it possible to do the right things for free. It is not harder to use HD than to not use it. (contrary to QBitNinja which make it hard to use HD)

As I specified on https://github.com/dgarage/NBXplorer/blob/master/docs/API.md NBXplorer is tracking key paths `x`, `0/x` and `1/x` which mean that

```
var publicAddress = userDerivationScheme.Derive(0).ScriptPubKey.GetDestinationAddress(network);
```
will be tracked (it is `x`), but also 
```
var publicAddress = userDerivationScheme.Derive(new KeyPath("0/0")).ScriptPubKey.GetDestinationAddress(Network.TestNet);
```
Which is  (`0/x`).

Once again, consider to not have address reuse, it is a shame to not use it when NBXplorer make it so easy to use HD.

**Comment by NicolasDorier** [comment]
Last thing, take a look at [this chapter](https://programmingblockchain.gitbooks.io/programmingblockchain/wallet/web-api.html) I show a clean example about how to spend from your wallet even my using multiple addresses.

**Comment by NicolasDorier** [comment]
@bazooka70 so normally you have `0/x` for public addresses and `1/x` for change addresses. `x` is for legacy purpose.

QBitNinja is complicated in the HD case because if your wallet have 100 addresses, then you need 100 requests to get your balance... but one request with NBXplorer!

QBitNinja is nice, but hard to make it start compared to NBXplorer as you can see :p

**Comment by bazooka70** [comment]
> QBitNinja is complicated in the HD case because if your wallet have 100 addresses, then you need 100 requests to get your balance... but one request with NBXplorer!

This is a very good point that I completely forgot about.
When I stared with bitcoin, a couple of weeks ago, I took this example:
[Build your own Bitcoin wallet](https://www.codeproject.com/Articles/1115639/Build-your-own-Bitcoin-wallet)
And now I see that client in the code is actually making a request for each address in the HD wallet to calculate the balance, but since I was focusing on a single re-usable address I forgot about this issue.
