### ISSUE TITLE
Send to multiple outputs

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#141]
Hi,

Transaction builder does not seem to support sending miltiple outputs, ie: multiple recipients and changeAddress with mining fee in 1 transaction so I was just looking at Transaction.Create where I can add the outputs but what about change address and sending mining fees? They only exist in Transaction builder....

Thanks

**Comment by NicolasDorier** [comment]
It does. Just call TransactionBuilder.Send several time

**Comment by sixjac** [comment]
Ahh,

So:

    TransactionBuilder builder = NBXNetwork.NBitcoinNetwork.CreateTransactionBuilder();
    Transaction tx = builder.AddCoins(unspent)
                                  .AddKeys(keys)
                                  .Send(recipient, recipAmount)
                                  .Send(commissionAddr, commAmount)
                                  .SetChange(changeAddr.ScriptPubKey)
                                  .SendEstimatedFees(fees)
                                   .BuildTransaction(true);

       bool verified = builder.Verify(tx);

Regards,
Sean Ryan

________________________________

**Comment by NicolasDorier** [comment]
yes
