### ISSUE TITLE
Change NBXplorer folder creation path

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#147]
Hi,

I need to change the default folder directory from: "C:\Users\<user>\AppData\Roaming" to an "ms-appx:///" folder for UWP due to those platform requirements. I looked through the NBXplorer project but failed to find where "C:\Users\<user>\AppData\Roaming\NBXplorer" was explicitly being set so I could change it.

Where is it? Thanks

**Comment by sixjac** [comment]
Hi Nicolas,

I need to know the file/dB that gets created to track schemes what's it's max size and resource consumption?

Could be a problem with central server and 500k wallet users as an example so that's why each device should have its own local server

Thanks

Regards,
Sean Ryan
On 25 Dec 2018, at 07:22, Nicolas Dorier <notifications@github.com<mailto:notifications@github.com>> wrote:

--datadir option you can change it.

**Comment by NicolasDorier** [comment]
I think 500k wallet is not a problem, you need to stress test yourself though.

**Comment by sixjac** [comment]
NBXplorer seems to be defaulting to C:\Windows\System32 root directory instead of the executing directory when I give it just a relative folder name in --datadir arg, this is an issue.

**Comment by NicolasDorier** [comment]
It should not default to it, please show me the logs.

**Comment by sixjac** [comment]
Access to the path 'C:\Windows\system32\NBXplorer' is denied.

system32 path getting prepended when I only give a folder name as --datadir

<img width="973" alt="pathIssueWithDataDir" src="https://user-images.githubusercontent.com/4453138/54072321-9896b380-4279-11e9-8d1a-15b29bf9d6c3.png">

**Comment by NicolasDorier** [comment]
Can you give me stack trace? Console logs?

**Comment by sixjac** [comment]
at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at StandardConfiguration.DefaultConfiguration.CreateConfiguration(String[] args)
   at NBXplorer.Program.Main(String[] args)


Program does not even make it to logfile output

**Comment by NicolasDorier** [comment]
Can you give me your command line?

**Comment by sixjac** [comment]
--datadir NBXplorer --chains btc --network testnet

note that NBXplorer is being launched via a fullTrustProcess as part of a UWP package and the above args is what is being passed.

--datadir NBXplorer  should be relative to the executing Directory.GetCurrentDirectory()\NBXplorer and not C:\Windows\System32\NBXplorer

Thanks

**Comment by sixjac** [comment]
I guess it is happening in CreateConfiguration(args) but cannot find function definition

**Comment by NicolasDorier** [comment]
the problem is probably that `Directory.GetCurrentDirectory()` is `C:\Windows\System32`.

**Comment by sixjac** [comment]
But it should not be, Directory.GetCurrentDirectory() should be the exe directory, my app is not running in System32. Anyway i will look into it, cheers.

**Comment by NicolasDorier** [comment]
I am not the one controlling `Directory.GetCurrentDirectory()` search how to make UWP use something else.

**Comment by sixjac** [comment]
Yes I realize that you do not control a .Net functions implementation
