### ISSUE TITLE
Running default bitcoin.conf but still cant connect to NBX

### ISSUE THREAD

**Issue by Freefromchainz** [dgarage/NBXplorer#149]
![btc payserv4](https://user-images.githubusercontent.com/8317700/50738471-8e7d0980-1191-11e9-8a3c-da1e268c7354.PNG)
this is what i get when i try to connect after a success build

here are the bitcoin and nbx conf setttings
![nbx issue1](https://user-images.githubusercontent.com/8317700/50738611-25969100-1193-11e9-8859-5f36a74a87ca.PNG)
![nbx issue2](https://user-images.githubusercontent.com/8317700/50738618-38a96100-1193-11e9-8a3e-2e9f5e8984a4.PNG)

**Comment by NicolasDorier** [comment]
You need to remove the # in front of the line. This is commenting the line.

**Comment by Freefromchainz** [comment]
So Far so good, I knew it was commented with #s but when I took out the comments first time I was still getting errors then i put them back in. then I realized how the conf file was setup bettter! modified mine like this but its still running with default btc.conf like stated in the instructions.  thanks for the help you can close this issue!
![nbx issue3](https://user-images.githubusercontent.com/8317700/50787882-ed677f00-1274-11e9-9f6a-c2771cd5cd10.PNG)

![nbx running good](https://user-images.githubusercontent.com/8317700/50787936-1a1b9680-1275-11e9-88a0-58e99aefe603.PNG)

**Comment by NicolasDorier** [comment]
And please, do what the `warning` tells you.
