### ISSUE TITLE
GetEstimatedFees

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#153]
How to I get the estimated fee value before building the actual transaction, yes GetEstimatedFees return 1 sat per byte as an example so how do I know the total bytes of the transaction? Do I have to build it (a dummy one) 1st?

**Comment by NicolasDorier** [comment]
Use `SendEstimatedFee` at the end of the transaction building step.

**Comment by sixjac** [comment]
No I want to get an estimation of fees I will have to pay for the transaction before I proceed with the transaction, this information to display to the user how much will cost to send transaction.

**Comment by NicolasDorier** [comment]
`var fee = tbuilder.EstimateFees(feeRate);`

**Comment by NicolasDorier** [comment]
`var fee = txBuilder.EstimateFees(tx, feeRate);`

**Comment by sixjac** [comment]
Ok so that means yes, I have to build a whole transaction like a dummy transaction before estimating fees.

Thanks

**Comment by NicolasDorier** [comment]
No

**Comment by NicolasDorier** [comment]
If you are building the transaction, use `var tx = txBuilder.BuildTransaction(false);` then `txBuilder.EstimateFees(tx, feeRate);`

**Comment by sixjac** [comment]
Ok thanks

**Comment by NicolasDorier** [comment]
`builder.EstimateFees(tx, new FeeRate("1"));` means that you want to pay 1 BTC per byte.

**Comment by sixjac** [comment]
Do the fee values differ between Testnet and Mainnet? I ask this because the Estimated fees I get from NBXplorer testnet seem to be low compared to what I see online, even with legacy address.

Thanks

**Comment by NicolasDorier** [comment]
Testnet fees are not reliable.

**Comment by sixjac** [comment]
Ok cool, thanks for the info.
