### ISSUE TITLE
 BTC: NBXplorer could not complete the handshake with the remote node.

### ISSUE THREAD

**Issue by adiadore** [dgarage/NBXplorer#154]
Hello, so im running bitcoind & lnd on raspberry#1(192.168.1.177) und btcpayserver on raspberry#2(192.168.1.178) locally on the same network and followed this guide [https://goo.gl/KnTzLu](url)
isolated they run fine but when i try to use raspb#1 as backend for raspb#2 im kinda stuck now

- i added the lines into the btc config

#bitcoind configuration

#mainnet/testnet
testnet=0

#Bitcoind options
server=1
daemon=1
txindex=1
disablewallet=0
addresstype=p2sh-segwit

#Connection settings
rpcuser=raspibolt
rpcpassword=xxx
rpcport=8332
rpcallowip=127.0.0.1
rpcallowip=192.168.1.0/24
**rpcallowip=192.168.1.178/255.255.255.0**
**whitelist=192.168.1.178**
#rpcbind=127.0.0.1:8332
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

#Raspberry Pi optimizations
dbcache=100
maxorphantx=10
maxmempool=50
maxconnections=20
maxuploadtarget=1

datadir=/mnt/hdd/bitcoin

- added the ufw agruments
8332                       ALLOW       Anywhere                   # btc rpc api
28333                      ALLOW       Anywhere                   # btc rpc api

- then i start NBXplorer with ./run.sh --datadir /opt/NBXplorer/.nbxplorer --btcrpcuser raspibolt --btcrpcpassword xxx --btcrpcurl http://192.168.1.177:8332/ --btcnodeendpoint 192.168.1.177:8332 &

starts fine but then.. any idea what i'm missing? I feel like i tried like every combination of whitelist, rpcallowip

info: Configuration:  BTC: Testing RPC connection to http://192.168.1.177:8332/
info: Configuration:  BTC: RPC connection successfull
info: Configuration:  BTC: Full node version detected: 170001
info: Configuration:  BTC: Loading chain from node (192.168.1.177:8332)...
**info: Explorer:       BTC: TCP Connection succeed, handshaking...
warn: Explorer:       BTC: NBXplorer could not complete the handshake with the remote node. This is probably because NBXplorer is not whitelisted by your node.
      You can use "whitebind" or "whitelist" in your node configuration. (typically whitelist=127.0.0.1 if NBXplorer and the node are on the same machine.)
      This issue can also happen because NBXplorer do not manage to connect to the P2P port of your node at all.
warn: Explorer:       BTC: The initial hanshake failed, your NBXplorer server might not be whitelisted by your node, if your bitcoin node is on the same machine as NBXplorer, you should add "whitelist=127.0.0.1" to the configuration file of your node. (Or use whitebind)**
fail: Configuration:  BTC: Unhandled in Waiter loop
System.OperationCanceledException: Loading the chain from the node timed out ---> System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take(CancellationToken cancellationToken)
   at NBitcoin.Protocol.PollMessageListener`1.ReceiveMessage(CancellationToken cancellationToken)
   at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload](CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(NodeRequirement requirements, CancellationToken cancellationToken)
   at NBXplorer.BitcoinDWaiter.LoadChainFromNode(CancellationToken cancellation)
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /root/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 372
   --- End of inner exception stack trace ---
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /root/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 376
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /root/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 283
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /root/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 197

**Comment by NicolasDorier** [comment]
Are you fully synched?

**Comment by NicolasDorier** [comment]
Your RPC connection is correctly setup. I bet on your not being fully synched.

**Comment by adiadore** [comment]
you mean on raspberry#1? i am https://i.imgur.com/EqxtLdV.jpg

**Comment by NicolasDorier** [comment]
I don't know, your node `192.168.1.177` is it fully synched?

**Comment by NicolasDorier** [comment]
ah sorry yes you are

**Comment by NicolasDorier** [comment]
I think you can remove `rpcallowip=192.168.1.178/255.255.255.0` because `RPC connection successfull`.

**Comment by NicolasDorier** [comment]
Ah your problem is ` Loading chain from node (192.168.1.177:8332)...` this is not RPC here

**Comment by NicolasDorier** [comment]
` --btcnodeendpoint 192.168.1.177:8333` and add port 8333 to the firewall

**Comment by adiadore** [comment]
of course that was the problem, --btcnodeendpoint 192.168.1.177 is enough, dont even needs the port i guess

thank you

**Comment by vincentyycheung** [comment]
HI adiadore,  I  want to run a btcpay server on AWS,  with a BTC&LND full node build by raspiblitz. Can you show more details how to setup the NBxplorer and btcpay server.  My BTCpay server show:NBxplorer BTC: NotConnected =>Syncing. Is that right or not? but my node full synced. I think my full-synced node should connect with btcpay server, which is no need to sync again. How you make your btcpay server running with a settled raspiblitz raspiberrypi ?

**Comment by vincentyycheung** [comment]
info: Configuration:  BTC: Explorer url is http://127.0.0.1:24445/
info: Configuration:  BTC: Cookie file is /home/vincent/.nbxplorer/Main/.cookie
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
info: Configuration:  Listening on http://0.0.0.0:23001
info: PayServer:      0 pending payment requests being checked since last run
info: Events:         NBXplorer BTC: NotConnected => Synching

![btcpay and nbxplorer](https://user-images.githubusercontent.com/48667188/54508964-d040e200-4982-11e9-8f00-d4066e7fa549.png)

**Comment by NicolasDorier** [comment]
@vincentyycheung Can you can try `docker restart generated_nbxplorer_1`?

**Comment by NicolasDorier** [comment]
What show the main page?
