### ISSUE TITLE
BIP44 conformity

### ISSUE THREAD

**Issue by alexb5dh** [dgarage/NBXplorer#159]
I'm quite new to this so please correct me if I'm wrong.

From what I found HD wallet are expected to follow BIP44 standard which means BTC accounts wallets should have path `44/0/{account}/0`. In that case tracking all accounts with single deriviation scheme seems not possible with NBXplorer as it won't track any transaction falling into `44/**` path.

I tried to use xpub under `44/0` as root but it doesn't help as any accounts after 1st (`44/0/2/0`, `44/0/3/0`, etc.) won't be filtered.

Is NBXplorer intended to be used with BIP44? Maybe I can modify pathes tracked via some configuration tweaks?

**Comment by alexb5dh** [comment]
OK, think I found the answer (here)[https://github.com/dgarage/NBXplorer/issues/65#issuecomment-403199076]

**Comment by NicolasDorier** [comment]
yes, NBXplorer can't do anything about BIP44. This is up to the signer wallet to know about it.
