### ISSUE TITLE
How to spend only confirmed coins?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#16]
From the docs:
https://programmingblockchain.gitbooks.io/programmingblockchain/wallet/web-api.html

If you want to spend those UTXOs:
```
var coins = utxos.GetUnspentCoins();
var keys = utxos.GetKeys(userExtKey);
TransactionBuilder builder = new TransactionBuilder();
builder.AddCoins(coins);
builder.AddKeys(keys);
builder.Send(new Key(), Money.Coins(0.5m));
builder.SetChange(changeAddress.ScriptPubKey);

// Set the fee rate
var fallbackFeeRate = new FeeRate(Money.Satoshis(100), 1);
var feeRate = tester.Client.GetFeeRate(1, fallbackFeeRate).FeeRate;
builder.SendEstimatedFees(feeRate);
/////

var tx = builder.BuildTransaction(true);
Console.WriteLine(client.Broadcast(tx));
```
If I understand correctly this will spend **unconfirmed** coins also.
how do I get only the confirmed coins (and the number of confirmations) from:
`var coins = utxos.GetUnspentCoins();`

Also, how to get Balance of confirmed  and unconfirmed coins, same as `QBitNinjaClient.GetBalanceSummary`?

**Comment by NicolasDorier** [comment]
I just pushed `1.0.1.11` to nuget, which add a parameter to `GetUnspentCoins` to specify if you want only what is confirmed or not.
For the balance use `coins.Select(c => c.Amount).Sum()`.

**Comment by bazooka70** [comment]
@NicolasDorier Thanks! Do I also need to recompile the server?
Also, shouldn't  the `onlyConfirmed` parameter needs to be added to the `var keys = utxos.GetKeys(extMasterKey);` also?

BTW, for now I resolved this problem like this:
```

            List<Coin> coinsConfirmed = new List<Coin>();
            Console.WriteLine("utxoConfirmed");
            var utxoConfirmed = utxos.Confirmed.UTXOs;            
            foreach (var utx in utxoConfirmed)
            {
                coinsConfirmed.Add(utx.AsCoin());
                Console.WriteLine($"utx.Value-> {utx.Value.ToUnit(MoneyUnit.BTC)} utx.Confirmations-> {utx.Confirmations}");                
            }
            var balanceConfirmed = coinsConfirmed.Sum(x => x.Amount.ToDecimal(MoneyUnit.BTC));
            Console.WriteLine($"balanceConfirmed-> {balanceConfirmed}");

            var balanceUnConfirmed = balance - balanceConfirmed;
            Console.WriteLine($"balanceUnConfirmed-> {balanceUnConfirmed}");
```

**Comment by bazooka70** [comment]
for now I added an extension:

        // https://github.com/dgarage/NBXplorer/blob/master/NBXplorer.Client/Models/UTXOChanges.cs
        public static Key[] GetKeys(this UTXOChanges utxos, ExtKey extKey, bool onlyConfirmed = false)
        {
            return utxos.GetUnspentUTXOs(onlyConfirmed).Select(u => extKey.Derive(u.KeyPath).PrivateKey).ToArray();
        }

But I'm not sure it is correct to pass the GetUnspentCoins(true) and GetKeys(true) to the transaction builder. will it resolve the correct Keys for the TxIn e.g.?

```
var coins = utxos.GetUnspentCoins(true);
var keys = utxos.GetKeys(userExtKey, true);
TransactionBuilder builder = new TransactionBuilder();
builder.AddCoins(coins);
builder.AddKeys(keys);
```

**Comment by NicolasDorier** [comment]
Recompile the server yes, I added some info inside GetStatus as well.

Good point for GetKeys. Can you make a PR ?

Yes it will resolve things just fine.

**Comment by bazooka70** [comment]
Just to be sure, If I use` GetUnspentCoins(onlyConfirmed: true);`
I need to use my extension `utxos.GetKeys(..., onlyConfirmed: true)`, or it does not matter?

> Can you make a PR ?

If you mean a pull request, I'm not sure how to do it... I can give it a try :)

**Comment by NicolasDorier** [comment]
You need to use your extension.

**Comment by NicolasDorier** [comment]
One question though: with `onlyConfirmed:true` do you want to remove UTXOs which has been spent on an unconfirmed transaction?

**Comment by NicolasDorier** [comment]
I pushed GetKeys with onlyconfirmed (1.0.1.13).

If onlyConfirmed is true, just remember that anything unconfirmed is completely ignored.

**Comment by bazooka70** [comment]
> One question though: with onlyConfirmed:true do you want to remove UTXOs which has been spent on an unconfirmed transaction?

Good question. 
I do not allow to spend any unconfirmed transactions. not even for testing. so "anything unconfirmed is completely ignored" is good for me.

**Comment by NicolasDorier** [comment]
no, this change is client only.

**Comment by bazooka70** [comment]
Thanks!

**Comment by NicolasDorier** [comment]
Can you closed the issues you opened that has been responded and which are still open?
