### ISSUE TITLE
Upgrade to DotNetCore 3.0

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#160]
DotNetCore 3.0 is release, can the project be updated to this? This will help compatibility with **UWP** and therefore enhance cross-platform compatibility.

**Comment by NicolasDorier** [comment]
.NET Core 3.0 is still in beta version. I think the final releaase is scheduled for july/september 2019.

**Comment by sixjac** [comment]
Ok, I thought it release along side VS2019 next month, but maybe not.

Cheers

**Comment by NicolasDorier** [comment]
I am looking forward.
Wikipedia says
```
.NET Core 3 was announced on May 7, 2018, at Microsoft Build. The first public preview was released on December 4, 2018,[13] the second public preview was released on February 1, 2019.[14] An official release is planned for 2019.[15] With .NET Core 3 the framework will get support for development of desktop application software, artificial intelligence/machine learning and IoT apps.[16]
```
