### ISSUE TITLE
Connect NBXplorer to remote Node

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#162]
Looked through previous issues on here but could not find anything exact, how to configure NBXplorer to connect to BTC Node on remote server different network?

Args:
--chains btc --network testnet --btcrpcurl http://127.0.0.1:8333 --btcnodeendpoint my.ip.alias
--btcrpcuser user--btcrpcpassword pass

<img width="742" alt="Untitled3" src="https://user-images.githubusercontent.com/4453138/54077561-6fe2de00-42ba-11e9-8dab-a7ad2964505e.png">

**Comment by NicolasDorier** [comment]
` --btcrpcurl http://127.0.0.1:8333` is not my definition of "remote".

**Comment by NicolasDorier** [comment]
I advise against running nbx and bitcoin on different machine though.

**Comment by sixjac** [comment]
Do you have an example of what all the config flags are for?

**Comment by sixjac** [comment]
I guess my remote IP is not whitelisted in the bitcoin.conf file so connection is being actively refused

**Comment by NicolasDorier** [comment]
I don't know why you can't connect to the other machine. Look your firewall and if bitcoind is listening the right interface. As the message says, your bitcoin machine is not listening.

**Comment by sixjac** [comment]
No the message does not say "your bitcoin machine is not listening" it says target machine, being the server. actively refused connection
