### ISSUE TITLE
Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JObject'.

### ISSUE THREAD

**Issue by ArduinoMasterInfernal** [dgarage/NBXplorer#167]
hi everybody, i got this error when i try to setup NBXplorer over Electrum Wallet

Rpc work Fine but instant crash after auth:

vmusertest@localvmbench:~/PROJECT/NBxplorer$ ./run.sh --testnet
info: Configuration:  Data Directory: /home/vmusertest/.nbxplorer/TestNet
info: Configuration:  Configuration File: /home/vmusertest/.nbxplorer/TestNet/settings.config
info: Configuration:  Network: Testnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Testnet
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Testing RPC connection to http://127.0.0.1:18332/
Hosting environment: Production
Content root path: /home/vmusertest/PROJECT/NBxplorer/NBXplorer/bin/Release/netcoreapp2.1/
Now listening on: http://127.0.0.1:24445
Application started. Press Ctrl+C to shut down.
fail: Configuration:  BTC: Error connecting to RPC server Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JObject'.
fail: Configuration:  BTC: Unhandled in Waiter loop
NBXplorer.Configuration.ConfigException
   at NBXplorer.Configuration.RPCArgs.TestRPCAsync(NBXplorerNetwork networkInfo, RPCClient rpcClient, CancellationToken cancellation) in /home/vmusertest/PROJECT/NBxplorer/NBXplorer/Configuration/RPCArgs.cs:line 132
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /home/vmusertest/PROJECT/NBxplorer/NBXplorer/BitcoinDWaiter.cs:line 263
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /home/vmusertest/PROJECT/NBxplorer/NBXplorer/BitcoinDWaiter.cs:line 200

How can i fix this ?

Thanks

**Comment by ArduinoMasterInfernal** [comment]
electrum wallet daemon used for this try

**Comment by ArduinoMasterInfernal** [comment]
anyone have setup NBXplorer over Electrum ? 

Every times i got : 

fail: Configuration:  BTC: Error connecting to RPC server Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JObject'.
fail: Configuration:  BTC: Unhandled in Waiter loop
NBXplorer.Configuration.ConfigException


i dont understand what im doing wrong

with bitcoin core it works fine

**Comment by NicolasDorier** [comment]
NBXplorer over Electrum does not make any sense. NBXplorer need to connect to a bitcoin node, not electrum.

**Comment by ArduinoMasterInfernal** [comment]
https://github.com/btcpayserver/btcpayserver-doc

They said to use, electrum or ledger for automatic generate invoices with nbxplorer

Bitcoin Core cannot use xpub

**Comment by NicolasDorier** [comment]
This doc is for BTCPayServer not for NBXplorer.
NBXplorer can track an electrum xpub key, but can't talk to an electrum server.

**Comment by ArduinoMasterInfernal** [comment]
yes I know, I opened an issue here because the trouble came from nbxplorer with electrum.

it seems that I did not understand the operation to automate the creation of invoices oon btcpayserver

**Comment by NicolasDorier** [comment]
Check the videos on https://www.youtube.com/channel/UCpG9WL6TJuoNfFVkaDMp9ug closing this as I think it is unrelated to what you want to do.
