### ISSUE TITLE
connection problem on TestNet

### ISSUE THREAD

**Issue by H-Moradof** [dgarage/NBXplorer#168]
Hi, At first let me thanks for developing NBXplorer and say sorry to give your time.
I've read a lot of documentation and issues but I couldn't solve my problem.

I ran bitcoin core full node on my windows server with command `.\bitcoind.exe -server -testnet`
this is my bitcoin config file:
server=1
testnet=1
rpcuser=test
rpcpassword=123456

Then I try to run NBXplorer with command `./run.ps1 -testnet` and `dotnet run -testnet` (as you said to another issuer)
this is my NBXplorer config file (testnet cofig file)

btc.rpc.url=http://127.0.0.1:18333/
btc.rpc.user=test
btc.rpc.password=123456

the bitcoin core seems good:
![1](https://user-images.githubusercontent.com/12098419/55286948-caea8b00-53b7-11e9-9856-d0f5db83a99c.jpg)

but I got error when running NBXplorer:
![2](https://user-images.githubusercontent.com/12098419/55286995-73005400-53b8-11e9-9526-869ab63406ca.jpg)

(I added allow rules for 18333 and 8333 in my firewall in both inbound and outbound)

I ran successfully NBXplorer in regtest yesterday but today my try was failed for testnet.

**Comment by H-Moradof** [comment]
Sometimes I see this error on my node :
`socket send error An established connection was aborted by the software in your host machine.  (10053)`
Is it connecting to my problem ?

**Comment by NicolasDorier** [comment]
is the port for P2P connection, 18333 you need to use the RPC port, not the P2P one.
Alternatively just run everything without commandline parameters, it will connect properly.

**Comment by NicolasDorier** [comment]
See https://docs.btcpayserver.org/deployment/manualdeployment

**Comment by H-Moradof** [comment]
in mainnet everything is OK.
It seems there is a problem with testnet.
thanks for your advise.

**Comment by NicolasDorier** [comment]
I can see "RPC: testing connection on port 18333" but 18333 is the network port, not the RPC port.

**Comment by H-Moradof** [comment]
Hi, I have a problem with disc space,
I have a server with 500G disc space but only after about 2 weeks since I start NBXplorer, my disc space is full !
the question is, how mush disc space it needs ?
Whats your suggestion about server (to decrease server costs) ?

thanks for you help.

**Comment by NicolasDorier** [comment]
This is probably unrelated to NBXplorer, check how to prune your bitcoin core full node.
