### ISSUE TITLE
Connection unexpectedly failed: Unexpected exception while connecting to socket

### ISSUE THREAD

**Issue by bereska** [dgarage/NBXplorer#170]
bitcoind, lnd on raspiblitz + BTCPay Server
it was working fine for a few days and now I get this this:

admin@bereskaLND:~ $ sudo systemctl status nbxplorer
● nbxplorer.service - NBXplorer daemon
   Loaded: loaded (/etc/systemd/system/nbxplorer.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-04-19 01:32:00 BST; 16h ago
 Main PID: 10248 (dotnet)
   CGroup: /system.slice/nbxplorer.service
           └─10248 /usr/local/bin/dotnet /home/admin/NBXplorer/NBXplorer/bin/Release/netcoreapp2.1/NBXplorer.dll -c /home/admin/.nbxplorer/Main/settings.config

Apr 19 18:19:57 bereskaLND dotnet[10248]: info: Explorer:       BTC: Handshaked node
Apr 19 18:20:24 bereskaLND dotnet[10248]: fail: Explorer:       BTC: Connection unexpectedly failed: Unexpected exception while connecting to socket
Apr 19 18:20:24 bereskaLND dotnet[10248]: info: Explorer:       BTC: Starting scan at block 572322
Apr 19 18:20:25 bereskaLND dotnet[10248]: info: Explorer:       BTC: Handshaked node
Apr 19 18:20:27 bereskaLND dotnet[10248]: fail: Explorer:       BTC: Connection unexpectedly failed: Unexpected exception while connecting to socket
Apr 19 18:20:28 bereskaLND dotnet[10248]: info: Explorer:       BTC: Starting scan at block 572322
Apr 19 18:20:29 bereskaLND dotnet[10248]: info: Explorer:       BTC: Handshaked node
Apr 19 18:20:30 bereskaLND dotnet[10248]: fail: Explorer:       BTC: Connection unexpectedly failed: Unexpected exception while connecting to socket
Apr 19 18:20:30 bereskaLND dotnet[10248]: info: Explorer:       BTC: Starting scan at block 572322
Apr 19 18:20:31 bereskaLND dotnet[10248]: info: Explorer:       BTC: Handshaked node

please help

**Comment by bereska** [comment]
and a few hours later without actually doing anything I see this:

admin@bereskaLND:~ $ sudo systemctl status nbxplorer
● nbxplorer.service - NBXplorer daemon
   Loaded: loaded (/etc/systemd/system/nbxplorer.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-04-19 01:32:00 BST; 21h ago
 Main PID: 10248 (dotnet)
   CGroup: /system.slice/nbxplorer.service
           └─10248 /usr/local/bin/dotnet /home/admin/NBXplorer/NBXplorer/bin/Release/netcoreapp2.1/NBXplorer.dll -c /home/admin/.nbxplorer/Main/settings.config

Apr 19 21:41:39 bereskaLND dotnet[10248]: info: Events:         BTC: New block 00000000000000000002671d1e3bf6ad6870ceae4db96b4102b21c35e8e9e291 (572375)
Apr 19 21:54:33 bereskaLND dotnet[10248]: info: Events:         BTC: New block 0000000000000000000814ad2363857d25bdaf940866e87144d0b924291b0499 (572376)
Apr 19 21:58:27 bereskaLND dotnet[10248]: info: Events:         BTC: New block 0000000000000000000a15e90a0709d0952fe9a5a5d50473e510175a8ef52b0d (572377)
Apr 19 22:13:24 bereskaLND dotnet[10248]: info: Events:         BTC: New block 00000000000000000006c5d7b0feb80939a9e318fa52bf564dc4fbd14066b3ca (572378)
Apr 19 22:32:23 bereskaLND dotnet[10248]: info: Events:         BTC: New block 0000000000000000001798c1f101839e3c8477e7cc6d5913108a02b492546a9b (572379)
Apr 19 22:34:07 bereskaLND dotnet[10248]: info: Events:         BTC: New block 0000000000000000001d964b855c965f81812299ad6c1deca6fe0c4921471928 (572380)
Apr 19 22:46:45 bereskaLND dotnet[10248]: info: Events:         BTC: xpub6CeeYb...U5HfV2dooGjt2-[p2sh] matching unconfirmed transaction d2481e...416ff4 (0/7)
Apr 19 22:53:07 bereskaLND dotnet[10248]: info: Events:         BTC: xpub6CeeYb...U5HfV2dooGjt2-[p2sh] matching confirmed transaction d2481e...416ff4 (0/7)
Apr 19 22:53:07 bereskaLND dotnet[10248]: info: Events:         BTC: New block 0000000000000000002bda0e9b760b4438a05358b80325dcee14343fe79fae04 (572381)
Apr 19 22:56:12 bereskaLND dotnet[10248]: info: Events:         BTC: New block 0000000000000000001c04282077410bf63e9e99bfb2cd60777f7a3126c278e8 (572382)

Looks like it just fixed itself but I would like to make my BTCPay Server more stable and reliable
please help to find where to dig and what to do
thank you

**Comment by bereska** [comment]
getting "Your Nodes are syncing" warning on https://btcpay.bereska-lnd.duckdns.org from time to time
looks like NBXplorer is struggling to catch up with the mainnet and falls behind
is it because rpi 3+ 1 Gb RAM is too little for this stack?
I see bitcoind and lnd take up to 30% of memory each
please somebody more knowledgable help me figure it out
i am really proud of my Raspiblitz + BTCPay stack on rpi and want to keep it running for other people to connect their on-line stores
More details on the stack:
Raspiblitz 1.1 with:
lnd version 0.5.2-beta commit=v0.5.2-beta
Bitcoin Core Daemon version v0.17.0.1
Manually installed:
dotnet 2.1.505
NBXplorer latest
BTCPay server v.1.0.3.92

thank you

**Comment by NicolasDorier** [comment]
Do you use `opt-save-memory` ?

**Comment by NicolasDorier** [comment]
Ah you don't use docker. Well, you need to configure bitcoind to use less memory. Or just use the docker deploy.

**Comment by bereska** [comment]
thanks for prompt reply)
will something like this work?
https://gist.github.com/laanwj/efe29c7661ce9b6620a7

**Comment by bereska** [comment]
since it is Raspiblitz my bitcoind is sort of pre-optimized for rpi:
# Raspberry Pi optimizations
dbcache=100
maxorphantx=10
maxmempool=50
maxconnections=40
maxuploadtarget=5000

this is what the memory usage looks like:
admin@bereskaLND:~ $ sudo free -h
              total        used        free      shared  buff/cache   available
Mem:           927M        723M         29M        4.1M        174M        146M
Swap:          1.0G        377M        646M

**Comment by NicolasDorier** [comment]
this is not really NBXplorer problem, I think your bitcoind get killed by OOM.

You can configure this through: https://stackoverflow.com/questions/624857/finding-which-process-was-killed-by-linux-oom-killer

I suspect LND being memory hungry. Are you running 0.6?

**Comment by NicolasDorier** [comment]
`maxconnections=40` is a log as well.

**Comment by bereska** [comment]
actually NO process was killed by OOM so far
LND 0.5.2 eats up about 15% of memory
can I configure bincond like this without breaking anything?
-blocksonly -dbcache=20 -maxsigcachesize=4 -maxconnections=4 -rpcthreads=1

**Comment by NicolasDorier** [comment]
mmmh this is strange. 

So the other potential problem is that NBXplorer is not whitelisted and there is no connection slot available on your node. Though if it was the case I would have expected a proper error message.

When you got those errors, bitcoind was working fine?

**Comment by bereska** [comment]
yes, I have whitelist=127.0.0.1 in /mnt/hdd/bitcoin/bitcoin.conf
bitcoind seems to be working fine no matter what, though it is the biggest CPU and memory user
LND is catching up, too. I suppose it will outplay bitcoind with the network growth. Can it it be optimized for rpi as well?

**Comment by NicolasDorier** [comment]
I don't know about LND.
Might it be your `maxuploadtarget` which disconnect the P2P connection?

**Comment by NicolasDorier** [comment]
mmh actually I don't think this is `maxuploadtarget`.

**Comment by NicolasDorier** [comment]
I will try to simplify my code. I don't know the root cause but given your log I don't think there is anything wrong on your side.

**Comment by bereska** [comment]
my only guess is that rpi sometimes struggles to pull off bitcoind, lnd and btcpayserver together
but it would be great if your code could keep this stack on rpi
so far this is the cheapest way to run your own btcpayserver)

**Comment by NicolasDorier** [comment]
I will make a commit soon, (20min) if you can test it it would be awesome

**Comment by bereska** [comment]
sure, fire up

**Comment by NicolasDorier** [comment]
Almost there running the tests....

**Comment by NicolasDorier** [comment]
Can you give a try to the updated master branch https://github.com/dgarage/NBXplorer/commit/5ef7fa1709221d65f826205aef96d01d43ae6d32 ?

**Comment by bereska** [comment]
running like a charm now)

admin@bereskaLND:~/NBXplorer $ sudo systemctl status nbxplorer
● nbxplorer.service - NBXplorer daemon
   Loaded: loaded (/etc/systemd/system/nbxplorer.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-04-22 06:07:25 BST; 8min ago
 Main PID: 7559 (dotnet)
   CGroup: /system.slice/nbxplorer.service
           └─7559 /usr/local/bin/dotnet /home/admin/NBXplorer/NBXplorer/bin/Release/netcoreapp2.1/NBXplorer.dll -c /home/admin/.nbxplorer/Main/settings.config

Apr 22 06:07:40 bereskaLND dotnet[7559]: info: Explorer:       BTC: Chain loaded
Apr 22 06:07:40 bereskaLND dotnet[7559]: info: Explorer:       BTC: NBXplorer is correctly whitelisted by the node
Apr 22 06:07:40 bereskaLND dotnet[7559]: info: Configuration:  BTC: Height: 572722
Apr 22 06:07:40 bereskaLND dotnet[7559]: info: Configuration:  BTC: Saving chain to cache...
Apr 22 06:07:42 bereskaLND dotnet[7559]: info: Configuration:  BTC: Chain cached
Apr 22 06:07:42 bereskaLND dotnet[7559]: info: Explorer:       BTC: Handshaked node
Apr 22 06:07:43 bereskaLND dotnet[7559]: info: Explorer:       BTC: Starting scan at block 572722
Apr 22 06:07:43 bereskaLND dotnet[7559]: info: Events:         BTC: Node state changed: NotStarted => NBXplorerSynching
Apr 22 06:07:43 bereskaLND dotnet[7559]: info: Events:         BTC: Node state changed: NBXplorerSynching => Ready
Apr 22 06:13:51 bereskaLND dotnet[7559]: info: Events:         BTC: New block 0000000000000000001e17373bf0317bb064f9cfcca933771dfade20900de465 (572723)

admin@bereskaLND:~/NBXplorer $ sudo systemctl status btcpayserver
● btcpayserver.service - BtcPayServer daemon
   Loaded: loaded (/etc/systemd/system/btcpayserver.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-04-22 05:48:02 BST; 27min ago
 Main PID: 9189 (dotnet)
   CGroup: /system.slice/btcpayserver.service
           ├─9189 /usr/local/bin/dotnet run --no-launch-profile --no-build -c Release -p /home/admin/btcpayserver/BTCPayServer/BTCPayServer.csproj --
           └─9236 dotnet exec /home/admin/btcpayserver/BTCPayServer/bin/Release/netcoreapp2.1/BTCPayServer.dll

Apr 22 06:07:32 bereskaLND dotnet[9189]:    at NBXplorer.WebsocketNotificationSession.ConnectAsyncCore(String uri, CancellationToken cancellation)
Apr 22 06:07:32 bereskaLND dotnet[9189]:    at NBXplorer.WebsocketNotificationSession.ConnectAsync(CancellationToken cancellation)
Apr 22 06:07:32 bereskaLND dotnet[9189]:    at NBXplorer.ExplorerClient.CreateWebsocketNotificationSessionAsync(CancellationToken cancellation)
Apr 22 06:07:32 bereskaLND dotnet[9189]:    at BTCPayServer.Payments.Bitcoin.NBXplorerListener.Listen(BTCPayWallet wallet) in /home/admin/btcpayserver/BTCPayServer/Payments/Bitcoin/NBXplorerLis
Apr 22 06:07:40 bereskaLND dotnet[9189]: info: Events:         NBXplorer BTC: Ready => Synching
Apr 22 06:07:50 bereskaLND dotnet[9189]: info: Events:         NBXplorer BTC: Synching => Ready
Apr 22 06:07:51 bereskaLND dotnet[9189]: info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
Apr 22 06:07:51 bereskaLND dotnet[9189]: info: PayServer:      BTC: 0 payments happened while offline
Apr 22 06:07:51 bereskaLND dotnet[9189]: info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
Apr 22 06:13:51 bereskaLND dotnet[9189]: info: Events:         BTC: New block

**Comment by NicolasDorier** [comment]
@bereska does the problem was reproductible or it was always working after your few hour later?

**Comment by bereska** [comment]
it was intermittent with rpc disconnection errors
and it took a longer time for it sync after restart
now it is up in seconds
no errors so far

**Comment by bereska** [comment]
memory usage is stabilized, too
admin@bereskaLND:~ $ sudo free -h
              total        used        free      shared  buff/cache   available
Mem:           927M        583M         31M         23M        311M        265M
Swap:          1.0G        153M        870M

**Comment by NicolasDorier** [comment]
Awesome!

**Comment by bereska** [comment]
Thank you)

**Comment by MajdajkD** [comment]
I also ran into this with my own code, which uses NBitcoin. The problem was that there was no free connection slot on the node. Took a while to figure it out, the DisconnectReason was "No more bytes to read". I wonder, what is the best solution to make free connection slot on my own node (I'm running it locally). Maybe connect with RPC and drop some connections?

**Comment by NicolasDorier** [comment]
@MajdajkD when you start NBXplorer, it tells you to whitelist your node if that's not already done.
Whitelisting your node (via whitebind or whitelist in bitcoind config) make sure you can always connect to it. It also make sure that transactions are forwarded as soon as your node receive it.

**Comment by MajdajkD** [comment]
Sorry, I was not clear. I am not using NBXplorer, I am making my own solution for tracking wallet balances using NBitcoin. The exception was thrown by NBitcoin, because my node already reached the maximum amount of connections. (Same error the author had. After I drop some connections it works fine.)
Just wanted to tell, that a node with no available connection (eg.: "maxconnections=10" param with 10 active connections) can cause this problem too.

**Comment by NicolasDorier** [comment]
@MajdajkD my comment hold the same. You need to whitelist the connection you use to connect to your node.
