### ISSUE TITLE
Get currently tracked addresses

### ISSUE THREAD

**Issue by djpnewton** [dgarage/NBXplorer#173]
How can I get a list of the tracked addresses (and their key paths) for a derivation scheme?

**Comment by NicolasDorier** [comment]
You can't, but why would you need it? An address should be shown only for depositing money.

**Comment by djpnewton** [comment]
Perhaps I dont really need it.. i have some wallet data (my own wallet) that was created with a different instance of NBXplorer. I need to initialize the tracked addresses to match my wallet addresses.

At the moment I am trying just reserving addresses with NBXplorer until the keypath return is at least as high as the highest in my wallet metadata

**Comment by NicolasDorier** [comment]
@djpnewton in this case just use https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#scan-utxo-set

It will look in the UTXO Set and restore the balance of your wallet.

**Comment by djpnewton** [comment]
it seemed like the rescan API did not work until I had 'registered' all my addresses using the 'GetUnused' API with 'reserve=true'

I will test again

**Comment by djpnewton** [comment]
ok.. i must have made a mistake in my testing earlier. thanks!

**Comment by NicolasDorier** [comment]
@djpnewton well this API is only finding about the highest keypath you used that is still unspent. So this is possible you need to do some more `reserve=true` on top of it. But normally it should take you very near the end.

**Comment by NicolasDorier** [comment]
(Reopen if not solved)
