### ISSUE TITLE
Unconfirmed UTXO not showing confirmation

### ISSUE THREAD

**Issue by Silverwizard80** [dgarage/NBXplorer#179]
Hi, I am running NBXplorer on linux using a modified NBitcoin.Altcoins. I am not having any issues connecting to the node, and everything appears to be normal. I am generating a derivation using 
`var userExtKey = new ExtKey(Recieved.ByteArray);
                var userDerivationScheme = network.DerivationStrategyFactory.CreateDirectDerivationStrategy(userExtKey.Neuter(), new DerivationStrategyOptions()
                {
                    // Use non-segwit
                    Legacy = true
                });` I am able to sucessfully track, and generate valid addresses using NBXplorer.Client, but for some reason when I send coins to the generated address the wallet confirms that the transaction has multiple validations, while the UTXO from the NBXplorer.Client query shows that it is still unconfirmed with 0 confirmations. I tried sending a second transaction, which also had multiple confirmations, and the same thing occured. The first transaction was evicted from local mem pool in NBXplorer, but was never shown as confirmed by NBXplorer and disapeared from `                var utxos = client.GetUTXOs(userDerivation);` entirely only showing the second transaction. Not sure what the issue is, I also tried runing NBXplorer with --rescan and --startheight which didn't fix the issue.

**Comment by NicolasDorier** [comment]
wow that's very strange. Will take a look now.

**Comment by NicolasDorier** [comment]
Just to be sure, you say you have custom modification, but does the tests still pass?

**Comment by NicolasDorier** [comment]
` The first transaction was evicted from local mem pool in NBXplorer, but was never shown as confirmed by NBXplorer and disapeared from var utxos = client.GetUTXOs(userDerivation);`

Note that this is normal as you spent the UTXO.

**Comment by Silverwizard80** [comment]
Sorry for the delayed response, but I tried to run the tests, but was experiencing issues since I don't yet have the testnet, and regnet setup propperly for the coin. Is there a way that I can run the tests only on the mainnet?

**Comment by NicolasDorier** [comment]
@Silverwizard80 you don't need testnet nor any setup. Running the test are starting bitcoin core behind the hood.

**Comment by Silverwizard80** [comment]
Hi, I tried tracing back the issue from NBitcoin.Altcoins to ensure that I was working from a solid foundation. Running the modified tests for my altcoins daemon I got results that 6 tests passed and 4 failed. The failures were Has correctGenesisBlock, CanSyncWithPoW, CanSyncWithoughtPoW, and DoesRPCCapabilitiesWellAdvertised. I am confused about the genesis block because I am certain that I have imported the correct genesis block as a hex, and as for the PoW tests I get the error "The node is not in a connected state". This seems odd to me since I believe I correctly configured the test setup. I am not using a cookie file, but do have a conf file in .vimee configued that seems to work. `public class VimeeCoinNodeDownloadData
		{
			public NodeDownloadData v0_18_1 = new NodeDownloadData()
			{
				Version = "0.18.1",
				Linux = new NodeOSDownloadData()
				{
					Archive = "vimee-wallet.tar.gz",
					DownloadLink = "https://vimee.io/DownloadFiles/NBitcoin-Download/vimee-wallet.tar.gz",
					Executable = "vimee-wallet/bin/vimeed",
					Hash = "8c2a58fe9730955f42779248232ea5e5400fa6d8840a9399cb37906f0c6b524b"
				},
				SupportCookieFile = false,
				UseSectionInConfigFile = true,
			};
		}`. As for NBXplorer I tried to build a new modified version since the one I previously used was a clone from Aug 2nd, and this new version will not Track my derivation scheme when I call `client.Track(userDerivation);` in my application although my client is connecting to the NBXplorer server. Also when I try to run the NBXplorer tests, the test freezes after downloading the node despite that I am testing on a system that should have enough hardware bandwith for the test. Not quite sure where to begin here I would really appreciate some insight on what I can do to start addressing these issues or what you think the problem might be.

**Comment by NicolasDorier** [comment]
@Silverwizard80 I can't help you, you first need to fix the NBitcoin Altcoin tests, you can debug step by step to understand what is going on. Until this is fixed, NBxplorer will not work with your coin.

**Comment by Silverwizard80** [comment]
Ok no problem thanks for the help, I'll try to spend some more time working with the NBitcoin library. Btw im trying to configure the tests for mainnet instead of regtest, and am having trouble with establishing rpc connection to the node. Do I need to place the .conf file somewhere other than the default coin location for NBitcoin to see the RPC user/password?

**Comment by NicolasDorier** [comment]
With NBitcoin you can configure the default folder of your coin so it can use cookiefile to connect to local RPC. This allow NBXplorer to connect to RPC without any configuration if you use default parameters.

Else you need to setup configuration either via nbxplorer `.conf` or command line arguments.
