### ISSUE TITLE
Bitcoin Core pruned

### ISSUE THREAD

**Issue by BuggeringHell** [dgarage/NBXplorer#18]
Hello, is it possible to use a pruned instance of Bitcoin Core?

**Comment by NicolasDorier** [comment]
Since 0.16 it should be possible but I have not tested it. (thanks to BIP159)

**Comment by NicolasDorier** [comment]
@BuggeringHell why not connecting by P2P to your full node with the hot wallet, while connecting the RPC to the pruned node?

I don't think the REST API expose everything that I need to have a good enough experience.

**Comment by NicolasDorier** [comment]
I am closing this, I got report on the Slack of someone who told me it worked!
