### ISSUE TITLE
How can I track large of addresses that would exceed gap limit?

### ISSUE THREAD

**Issue by chaoyebugao** [dgarage/NBXplorer#181]
I have numbers of users to deposit, so I will give different address to every user. In this way i have to track my derivations with big minAddresses/maxAddresses(Gap size). And this is a slow operation, becuse it will generate a lot of addresses in NBXplorer right?
Is it a good idea? Do we have a better way to do this?

**Comment by NicolasDorier** [comment]
You can use https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#track-a-derivation-scheme to generate addresses as soon as you track without having to change the gap limit.

**Comment by chaoyebugao** [comment]
> You can use https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#track-a-derivation-scheme to generate addresses as soon as you track without having to change the gap limit.

I am using this to do the tracking. But by default this only track unused 20 addresses at the beginning because minAddresses is 20 default. The problom is I can not user the gap limit mechanism because it is one address for one user to deposite. So I change the post body - minAddresses like below:

` {
  "derivationOptions": [
    {
      "feature": "Deposit",
      "minAddresses": 470000,
      "maxAddresses": 470001
    },
    {
      "feature": "Change",
      "minAddresses": 1,
      "maxAddresses": 2
    },
    {
      "feature": "Direct",
      "minAddresses": 1,
      "maxAddresses": 2
    }
  ],
  "wait": false
}`

After this the tracking works. But This is slow operation cuz the addresses generation, so I am going to find whether there is another way to track large of address of a derivation.

**Comment by NicolasDorier** [comment]
@chaoyebugao if you want to generate lots of addresses why are you using `minAddresses`: 1 and `maxAddresses`: 2 ?

**Comment by NicolasDorier** [comment]
> because it is one address for one user to deposite

You mean you use 1 derivation scheme per customer?

**Comment by chaoyebugao** [comment]
> > because it is one address for one user to deposite
> 
> You mean you use 1 derivation scheme per customer? Why would you do this? If you own the funds, just use 1 derivation scheme for all deposits of all customers.

No. Sorry I did not explain clearly. Just 1 derivation, and thousands address for deposits. So I have to set minAddresses to a large number.

**Comment by NicolasDorier** [comment]
@chaoyebugao but why? You just have to reserve an address everytime a user is asking for a deposit, that's it.

**Comment by chaoyebugao** [comment]
> @chaoyebugao but why? You just have to reserve an address everytime a user is asking for a deposit, that's it.
Do you mean use ["Get a new unused address"](https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#get-a-new-unused-address) and it's reserve parameter ? Fine, I will take a look, thx ^_^

**Comment by NicolasDorier** [comment]
yes
