### ISSUE TITLE
Bug: Legacy Wallet PSBT has witnessUtxo instead of nonWitnessUtxo

### ISSUE THREAD

**Issue by junderw** [dgarage/NBXplorer#185]
Recreation steps:

1. Create legacy wallet with xpub-[legacy]
2. Deposit coins
3. Create PSBT
4. View contents to see the input has witnessUtxo but no nonWitnessUtxo

Expected outcome:

- The PSBT should give nonWitnessUtxo (full TX binary) for non-segwit inputs and witnessUtxo for segwit inputs.

(Note for altcoins: Many forkcoins of Bitcoin commit the value of the input in the sighash, so even if they don't support segwit, using a witnessUtxo for them for all types of input is OK.)

**Comment by junderw** [comment]
So this bug is actually expected behavior for forkcoins.

But for bitcoin, it is not expected behavior.

**Comment by NicolasDorier** [comment]
@junderw did you either scantxoutset this xpub?

**Comment by junderw** [comment]
probably, but in this case you should go get tx with txindex, or throw an error, since Bitcoin legacy wallet needs nonWitnessUtxo to sign PSBT according to BIP174.

**Comment by NicolasDorier** [comment]
I will not send exception, because it gives the option to the user to update his PSBT elsewhere.

Though I am pushing a commit checking in bitcoin core.

**Comment by NicolasDorier** [comment]
also bitcoin cash does not need non witness right.

**Comment by junderw** [comment]
yes, Bitcoin forks using Sighash_forkid commit to value, so witnessUtxo is fine.

**Comment by NicolasDorier** [comment]
@junderw meh I don't want to make a special case for bcash, I just made a push, can you test it?

**Comment by NicolasDorier** [comment]
ah test fail... checking

**Comment by NicolasDorier** [comment]
fixed the test

**Comment by junderw** [comment]
will check tomorrow.

does it require txindex?

**Comment by NicolasDorier** [comment]
@junderw maybe, maybe not. I saw that there might have been a bug where even if nbx knows the transaction, it would not fill out properly the WitnessUTXO.

But on top of fixing this bug, I added a check if txindex is activated.

**Comment by junderw** [comment]
Fixed
