### ISSUE TITLE
Feature Request: Ignore small amounts (configurable)

### ISSUE THREAD

**Issue by junderw** [dgarage/NBXplorer#186]
Tracking and scanutxoset should remove UTXOs below a specified threshold.

Default is none.

Could be an environment/runtime parameter.

Use case: Do not want to accidentally spend those spammy 1 satoshi inputs or recognize utxos that are below minimum deposit limit.

This is a very common metric for keeping spam from clogging up our systems.

**Comment by junderw** [comment]
When I say "remove" I mean "ignore" so they don't even look at them as "my wallet has received this UTXO" they will view it as "this UTXO is unrelated to my wallet"

**Comment by NicolasDorier** [comment]
@junderw I can add this as a server wide configuration.

**Comment by junderw** [comment]
How simple would this be to implement?

If you could maybe point out which files and in which way you would need to change it in order to add this feature we could do it on our end.

**Comment by NicolasDorier** [comment]
Search for `availableCoinsByOutpoint` and filter with your own criteria as I did for `IncludeOnlyOutpoints` and `ExcludeOutpoints`

**Comment by NicolasDorier** [comment]
Doing it now.

**Comment by NicolasDorier** [comment]
https://github.com/dgarage/NBXplorer/commit/e443dad84271165d5b0c2688d5a93238da8766e7

**Comment by junderw** [comment]
> Tracking and scanutxoset should remove UTXOs below a specified threshold.

I was not talking about PSBT creation...

I was talking about ignoring UTXO spam completely so that our DB isn't filled with spam. (even if we prune, many people send hundreds of spam UTXO which will slow down any calls to `/unspent` or something like that.

I was thinking something like this:

- Add environment variable `NBXPLORER_BTCMINUTXOAMT=10000` will mean that if a UTXO has a value of 9999 or less, the tracking wallet will not add that UTXO to the db, and will not add the transaction to the db at all. It will act as if the scriptPubkey was of different unknown key.

**Comment by NicolasDorier** [comment]
Why not using the manual pruning ? Just spend this spam then manual prune every day. (there is a call in the API for that)

**Comment by junderw** [comment]
> Just spend this spam

We can't.

**Comment by NicolasDorier** [comment]
In this case, you need to modify `Repository.GetMatches`.
The repository has access to the `ExplorerConfiguration`, so you should have everything in scope there.
