### ISSUE TITLE
Feature Request: Add healthcheck endpoint

### ISSUE THREAD

**Issue by junderw** [dgarage/NBXplorer#187]
1. This endpoint should be simple healthcheck
2. It should always be noauth (so it will be the only endpoint to not need cookie file)
3. Maybe it should return non-200 code if any of the coins are broken (RPC not responding etc)

I was thinking the existing get status endpoint was OK, but realized it requires auth unless noauth is used.

**Comment by Kukks** [comment]
I would not do point 3, as it leaks info on what coins you are connecting to?

**Comment by NicolasDorier** [comment]
meh, NBXplorer is not meant to be exposed externally

**Comment by junderw** [comment]
well. many people run jobs using AWS Lambda and Azure Functions.

also AWS and Azure have special setting to set a "healthcheck" where they will periodically ping for you and give alerts when non-200 comes...

I would hope you reconsider.

**Comment by NicolasDorier** [comment]
I was replying to kuksk on point 3

**Comment by Kukks** [comment]
Yeah but it circumvents the auth mechanism and you find out what nbx has access to.

**Comment by NicolasDorier** [comment]
ah I missed `but realized it requires auth unless noauth is used.`

**Comment by junderw** [comment]
I would be fine with an all or nothing.

`GET /health 200 OK` if everything is working

`GET /health 500 Server Error` if anything is broken (RPC for any coin is down, etc.)

We don't have to use status endpoint, it can be a new one that is just 200 for OK and 500 for NOPE.
