### ISSUE TITLE
Suggestion: broadcast should return non-200 code when success == false

### ISSUE THREAD

**Issue by junderw** [dgarage/NBXplorer#188]
After wondering why transactions were disappearing on testnet, found the issue.

We assumed that `await cli.broadcast(txBuffer)` would throw if an error occurred and our regtest tx (for testing) had an insane fee, and bitcoind rejected it. NBX returned 200 OK response with success == false in the JSON object.

If success == false, broadcast should return a non-2xx response.

**Comment by NicolasDorier** [comment]
I don't think changing this:

1. It is a breaking change, purely for aesthetic reasons
2. I plan to add a `verifyonly` parameter for the broadcast which do not broadcast, and prefer not having to make a different route

**Comment by junderw** [comment]
I think anyone using this will not check success and assume error is non-200.

You should make this in bold and big letters in the docs.
