### ISSUE TITLE
How to control keys that were registered with ExplorerClient.Track()?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#19]
```
var strategy = CreateDerivationStrategy(extPubKey);            
...
client.Track(strategy);
```
After a lot of tests I have a bit of Keys garbage which I need to clean up.

- How can I delete/unregister  All / Specific xpub key(s) that were previously registered via `ExplorerClient.Track(strategy)` ?
- Can this be done programmatically with the client without restarting the server?

**Comment by NicolasDorier** [comment]
You can't. But why would you? This does not take lot's of space.

**Comment by bazooka70** [comment]
> This does not take lot's of space.

This might be true. but I hate junk :)
I imagine the server is periodically querying the registered wallets, and that _might_ cost in performance.
We are expected to manage thousands of wallets this might become an issue. I'm not sure.
I think for now, while not in production, I will simply delete the DB files and restart the server?

**Comment by NicolasDorier** [comment]
Yes you can do this.
The server is not querying anything periodically, so there is no performance hit to have lot's of address to track.

**Comment by bazooka70** [comment]
OK, thanks :+1:
