### ISSUE TITLE
Transaction is not listed

### ISSUE THREAD

**Issue by andrasfuchs** [dgarage/NBXplorer#190]
I run NBXplorer with the following parameters while running a local Bitcoin node on Mainnet:
'--btcrpcuser=myuser --btcrpcpassword=mypassword --btcstartheight=556452 --btcrescan=1'

This rescanned the Mainnet since the very end of 2018 without any errors.

Then I use [Postman](https://www.getpostman.com/) to run queries. Authentication works fine and NBXlporer looks synced, because I get back this while getting `http://localhost:4774/v1/cryptos/btc/status`

> {
>     "bitcoinStatus": {
>         "blocks": 592280,
>         "headers": 592280,
>         "verificationProgress": 0.999996599640577,
>         "isSynched": true,
>         "incrementalRelayFee": 1,
>         "minRelayTxFee": 1,
>         "externalAddresses": [
>             "2001:4c4e:2a11:2e00::806:8333",
>             "2001:4c4e:2a11:2e00:d44:5de0:ae2f:70d:8333",
>             "2001:4c4e:2a11:2e00:ac9c:6946:2f31:c729:8333"
>         ],
>         "capabilities": {
>             "canScanTxoutSet": true,
>             "canSupportSegwit": true
>         }
>     },
>     "repositoryPingTime": 0.00029,
>     "isFullySynched": true,
>     "chainHeight": 592280,
>     "syncHeight": 592280,
>     "networkType": "Mainnet",
>     "cryptoCode": "BTC",
>     "supportedCryptoCodes": [
>         "BTC"
>     ],
>     "version": "2.0.0.56"
> }

I'd like to get some information about one particular transaction trying these two methods:

#A
GET `http://localhost:4774/v1/cryptos/btc/transactions/86394fa887bc615919e5c945d8e7977f64d77e7d7d4871683d0470120aaa82d9`

It returns a 404 Not found error (although if I debug the code it enters the `GetTransaction` method on the `MainController`).

#B
GET `http://localhost:4774/v1/cryptos/btc/addresses/3BXnQJd46uRCNBq9YjxBroWeGyd9zqnoXN/transactions`

It returns this:

> {
>     "height": 592280,
>     "confirmedTransactions": {
>         "transactions": []
>     },
>     "unconfirmedTransactions": {
>         "transactions": []
>     },
>     "replacedTransactions": {
>         "transactions": []
>     }
> }

If you look at the transaction in [a public explorer here](https://www.blockchain.com/btc/tx/86394fa887bc615919e5c945d8e7977f64d77e7d7d4871683d0470120aaa82d9), you can see that it's there and valid.

What do I miss here?

**Comment by NicolasDorier** [comment]
@andrasfuchs NBXplorer is not a public block explorer, it won't try to save every transaction, but only the one that are related to a wallet you are tracking.

**Comment by andrasfuchs** [comment]
@NicolasDorier Is it possible to track only one address or a list of addresses (even if they are not in a wallet that I own)?

**Comment by NicolasDorier** [comment]
Yes it is. Check the doc https://github.com/dgarage/NBXplorer/blob/master/docs/API.md

You don't need to "own" the wallet, as long as you have the xpub, you can track a wallet. You can also track individual scriptPubKeys but I advise you against it as this is not very maintainable.

**Comment by andrasfuchs** [comment]
Just for reference I list here the APIs that made the trick for me:

1. `/v1/cryptos/btc/status` - I checked if my connection to the node is good, and the node is running and synced.
2. `/v1/cryptos/btc/addresses/<address to track>` - Added the address to the tracked address list
3. `/v1/cryptos/btc/rescan` (with blockId and transactionId) - I rescanned an old transaction so that NBXplorer knows about it
4. `/v1/cryptos/btc/transactions/<transaction id>` - I double checked that the transaction was registered by NBXplorer
5. `/v1/cryptos/btc/addresses/<address to track>/transactions` - I confirmed that the transaction is properly listed under the address

**Comment by NicolasDorier** [comment]
If possible I would advise you rather:

1. Track a Derivation Scheme instead of individual addresses
2. Use https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#scan-utxo-set
3. Profit.

**Comment by andrasfuchs** [comment]
To be honest, I still don't understand fully how to use the derivation schemes. 
For my use case I need to check separate transactions only (for the InstantSend tests) so it's alright.
Do you have a documentation with actual samples of derivation scheme values?

**Comment by NicolasDorier** [comment]
@andrasfuchs It is documented in `docs/API.md`. Basically it tells NBXplorer how to derive all addresses so you don't have to track them individually and can have your whole wallet UTXOs/Transactions with one call instead of N call where N is the number of different address.

**Comment by andrasfuchs** [comment]
I read the API docs, and it's surely my lack of knowledge, but I still don't know how to use derivation schemes without seeing actual samples. It would be great to have same basic (maybe Postman) samples with the GET/POST requests and their typical responses there, so that we could imagine its workings better.
For example I first thought that I need to paste the actual `xpub1` or `xpub-[legacy]` string into the {dericationScheme} section of the URL. Later I realized that it must be some kind of identifier instead generated somewhere, but in the end I still couldn't use that API.
I'm still not sure if it would work with a non-HD wallet or an altcoin? Some clarification would be great in the documentation ;)

**Comment by NicolasDorier** [comment]
This is long story that requires you to understand BIP-32 (https://programmingblockchain.gitbook.io/programmingblockchain/)
