### ISSUE TITLE
Feature Request: keep previous cookie for authentication (for testing)

### ISSUE THREAD

**Issue by andrasfuchs** [dgarage/NBXplorer#191]
Cookie authentication is nice, but it can be a pain when testing NBXplorer with an API Development Environment (like Postman), because NBXplorer generates a new cookie every time it runs and the new cookie information must be transferred to Postman manually ([as described in the readme](https://github.com/dgarage/NBXplorer#using-postman)).

It would be great if we could have a `--keepoldcookie` parameter for NBXplorer to indicate that we would prefer to keep the old cookie, so that we don't need to do the extra copy-paste again.

**Comment by NicolasDorier** [comment]
@andrasfuchs then we do you use cookie? you can just use username and password instead.

**Comment by andrasfuchs** [comment]
@NicolasDorier Ah, ok, I didn't know it's possible to set username and password! 
Could you help me find the documentation for those parameters? There was no mention about them in the [readme](https://github.com/dgarage/NBXplorer).

**Comment by NicolasDorier** [comment]
@andrasfuchs ah yes it is not possible actually! I thought it was, well then why not running `--noauth`  which remove the cookie verification?

**Comment by andrasfuchs** [comment]
@NicolasDorier Hmm, I didn't know about the `--noauth` flag. Thanks for the tip, I have just tested it, and it works like a charm :)
Would you mind if I changed the README.md to recommend developers/testers to use `--noauth` with Postman for testing? 
It would make it much easier than looking for the cookie file and copy-paste data every time.

**Comment by NicolasDorier** [comment]
Yep, I merged your PR so closing this.
