### ISSUE TITLE
Is the 'getrawtransaction' RPC call deprecated?

### ISSUE THREAD

**Issue by andrasfuchs** [dgarage/NBXplorer#192]
I run Bitcoin Core v0.18.0, Litecoin Core v0.17.1 and Dash Core v0.14.0.1 locally, all on testnet, they are not pruned.

I call the `/v1/cryptos/dash/rescan` API with the `blockId` and `transactionId` in the POST body as described here: https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#rescan-a-transaction

At the following line I get an exception from the RPC call:
> [var getTx = rpc.GetRawTransactionAsync(transaction.TransactionId, transaction.BlockId, false);](https://github.com/dgarage/NBXplorer/blob/c97f807c177bd29d37d73f4da17ada74d3f4c63c/NBXplorer/Controllers/MainController.cs#L651)

Exception details:
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
> NBitcoin.RPC.RPCException: getrawtransaction "txid" ( verbose )
> 
> NOTE: By default this function only works for mempool transactions. If the -txindex option is
> enabled, it also works for blockchain transactions.
> DEPRECATED: for now, it also works for transactions with unspent outputs.
...
> 
>    at NBitcoin.RPC.RPCResponse.ThrowIfError()
>    at NBitcoin.RPC.RPCClient.GetRawTransactionAsync(uint256 txid, uint256 blockId, Boolean throwIfNotFound)
>    at NBXplorer.Controllers.MainController.FetchTransaction(RPCClient rpc, TransactionToRescan transaction) in C:\Work\BTCPayServer\NBXplorer\NBXplorer\Controllers\MainController.cs:line 655
>    at NBXplorer.Controllers.MainController.Rescan(String cryptoCode, RescanRequest rescanRequest) in C:\Work\BTCPayServer\NBXplorer\NBXplorer\Controllers\MainController.cs:line 616
>    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
...

I also tried to run my Dash node with the `-txindex` parameter, but I got the same results.

There is a discussion about this breaking change in v0.18 here: https://github.com/bitcoin/bitcoin/issues/16142

EDIT: I also tried it with BTC and LTC, and they work. 
It also works with DASH, but only if I remove the `blockId` from the the POST body, leaving only the `transactionId` there.

**Comment by NicolasDorier** [comment]
@andrasfuchs this is strange. I don't think this is deprecated if I supply the blockid (which I do). Will check.

**Comment by NicolasDorier** [comment]
@andrasfuchs checked with regtest, this should work as I am passing the `blockid`.

**Comment by NicolasDorier** [comment]
Might it be a Dash only problem because they don't accept the blockId in parameter?

**Comment by NicolasDorier** [comment]
I double checked with my node on 0.18.0 and NBitcoin class. It behaves as it should. Does this error happen on bitcoin?

**Comment by andrasfuchs** [comment]
I checked it too: BTC and LTC both work fine with `blockId`, but DASH 0.14 throws the exception. 
It's not critical for me, but it's just strange.

**Comment by NicolasDorier** [comment]
@andrasfuchs welcome in shitcoin land.

**Comment by andrasfuchs** [comment]
I updated my DASH node to v0.14.0.3, same results. 
Oh well, I'm going to use it without the `blockId` then.
Thanks for looking into it, @NicolasDorier!

**Comment by NicolasDorier** [comment]
let me know if I can make something so it works at least with -txindex.

**Comment by andrasfuchs** [comment]
Thanks, it looks like working fine without the `blockId` and strangely even without the `-txindex` switch with Dash Core v0.14.0.3.

**Comment by NicolasDorier** [comment]
@andrasfuchs I think it works only if the tx is in the utxoset.
