### ISSUE TITLE
Why are you using .NET?

### ISSUE THREAD

**Issue by amir3code** [dgarage/NBXplorer#195]
I am just curious with so much goodness available to python / java / javascript, Why would you guys used .NET to build this?

We all know .NET is a MICROSoft thing, We all hate the Mice.
There are so many libraries available for those 3 languages that I mentioned why would you use a new born Mice baby that just have an `open` word in its name?

Lets get honest...

**Comment by bdangh** [comment]
Honestly I think better education needed before writing issues to someone’s repo.

**Comment by NicolasDorier** [comment]
Python / Java / Javascript are year behind dotnet in term of productivity.
