### ISSUE TITLE
gapLimit parameters seems ignored when calling /utxos/scan

### ISSUE THREAD

**Issue by ang-st** [dgarage/NBXplorer#196]
Hi, 
I try to scan UTXOS from a wallet having a quite large set of change addresses (more than 45000 .. )

i issue this call with curl
```
curl 'http://localhost:32838/v1/cryptos/BTC/derivations/xpub6C3....AM-\[legacy\]/utxos/scan' -v  -H "Content-Type: application/json" -X POST -d '{"gapLimit":"50000"}' 
``` 

the log show 
```
info: Explorer:       BTC: Start scanning xpub6C3...AM-[legacy] from index 0 with gap limit 10000, batch size 1000 
```

I also tried passing number instead of string (ie : ` {"gapLimit":50000}` with the same result.
Do I miss something ?

**Comment by NicolasDorier** [comment]
You need to pass it as a query string (eg `?gapLimit=50000`)

**Comment by ang-st** [comment]
@NicolasDorier thanks :)

for the records as some users might want to use curl to query  `NBXplorer`
```
curl 'http://localhost:32838/v1/cryptos/BTC/derivations/xpub-\[legacy\]/utxos/scan?gapLimit=50000' \
-v  -H "Content-Type: application/json"  \
-X POST -d "" #need an empty body otherwise Content-Length header is not sent and we get an error 
```
