### ISSUE TITLE
Unhelpful Error: Psbt Create when no utxos

### ISSUE THREAD

**Issue by junderw** [dgarage/NBXplorer#197]
https://github.com/dgarage/NBXplorer/blob/3a44058c60da60ebf95b558bccdb1668831d056b/NBXplorer/Controllers/MainController.PSBT.cs#L49

Error response of "500 - undefined" is returned, but it would be nice to know "no utxos available" etc.

**Comment by NicolasDorier** [comment]
it should send no-enough-funds do you have a stacktrace with the error?

**Comment by junderw** [comment]
Closing this issue, it seems we are having an issue with Base58Check...........
