### ISSUE TITLE
USE on an Altcoin

### ISSUE THREAD

**Issue by izakhearn** [dgarage/NBXplorer#2]
Is there anyway to use this on a litecoin based altcoin

**Comment by NicolasDorier** [comment]
How Litecoin work: https://youtu.be/liOUTqBUi_g

For crypto using same transaction format as BTC and LTC, please look at the repo how I implemented LTC and do the same for your altcoin, then submit a PR.

**Comment by izakhearn** [comment]
Okay so i created the altcoins file in the Altcoin folder where do i add it as a chain i cant seem to find it

**Comment by NicolasDorier** [comment]
If you are .NET developer you can figure out easily, if not I sadly don't have enough time to guide you how to do it. :/

**Comment by izakhearn** [comment]
Okay no problem man Thanks for the help anyway will keep browsing to find it
