### ISSUE TITLE
ExplorerClient.CreateNotificationSession() with ListenDerivationSchemes

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#20]
I have 2 related questions:

1)
Is it possible to to `CreateNotificationSession` with `ListenDerivationSchemes` without specifying the `DerivationStrategyBase[]` in front and get notification for **ALL** derivation schemes which where previously registered via `client.Track(strategy)`.

I have tried using `null`  with `ListenDerivationSchemes`:
```
var events = client.CreateNotificationSession();
events.ListenDerivationSchemes(null);
```
But this is not allowed.

2) What would be the correct code to run such listener utility? (in a console application)
Is this the correct approach?

```
var events = client.CreateNotificationSession();            
events.ListenDerivationSchemes(new[] { strategy });
while (true)
{
    var txEvent = (NBXplorer.Models.NewTransactionEvent)events.NextEvent();
    Console.WriteLine(txEvent.TransactionData.Transaction.ToString());
    // update my DB here or do other useful stuff...
}

```

**Comment by NicolasDorier** [comment]
It is not possible right now, but I don't mind having this feature. Can you do a PR for it ?

**Comment by bazooka70** [comment]
> Can you do a PR for it ?
I'm really lost at how to do a PR  :/ 
The "Create pull request" is disabled for me. I created a fork  but can not create a PR either. i have been over the githubs dos,  and simply cannot grasp on how to do it <errrg>.

**Comment by NicolasDorier** [comment]
I added it, NBXplorer.Client 1.0.1.14 you need to update the server to 1.0.1.18. `ExplorerClient.ListenAllDerivationSchemes`.

**Comment by bazooka70** [comment]
Thank you so much! you are the god of bitcoin :100:
