### ISSUE TITLE
NBXplorer run testnet error

### ISSUE THREAD

**Issue by sean208208** [dgarage/NBXplorer#206]
ubuntu 16.04
NBXplorer-2.0.0.58
dotnet 2.1.802
btcpayserver the newest
bitcoin core the newest
testnet fullnode already
bitcoin.conf
testnet=1
listen=1
rpcuser=bitcoinrpc
rpcpassword=password
server=1
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

I refer to this article
[BTCPayServer Installation on Ubuntu 16.04](https://medium.com/@citlayik/btcpayserver-installation-on-ubuntu-16-04-19ba0e811ef6)

I have two question

1.How can I generate cookie file in bitcoin testnet.
2.When I input "./run.sh -testnet" in NBXplorer,will show 
`Unhandled Exception: DBriize.Exceptions.DBriizeException: Creation of the database folder failed! ---> DBriize.Exceptions.DBriizeException: Database is not operable, please find out the problem and restart the engine! FSR INIT FAILED: /home/seanchen/.nbxplorer/TestNet/db/_DBreezeSchema ---> System.IO.IOException: The process cannot access the file '/home/seanchen/.nbxplorer/TestNet/db/_DBreezeSchema' because it is being used by another process.
`
Dose anyone can tell me the answer?
Thanks

**Comment by NicolasDorier** [comment]
yes, close the already running nbxplorer instance.
