### ISSUE TITLE
How to tell if a transaction is invalid for double spend?

### ISSUE THREAD

**Issue by chaoyebugao** [dgarage/NBXplorer#211]
I am handling the double spend problem. I used a testnet faucet to create double spend, and two transactions were broadcasted at the same time below:

[d32e355859cbf8b82ccdb0d9087035f66641c0c14dc33ee9f1533d7d511dae87](https://www.blockchain.com/btctest/tx/d32e355859cbf8b82ccdb0d9087035f66641c0c14dc33ee9f1533d7d511dae87), short as `d3`, marked with `RBF`
[d4a1214e8b4ea68c4d754f27b1c954d3e446cedf1cdb1dc949548af295966c75](https://www.blockchain.com/btctest/tx/d4a1214e8b4ea68c4d754f27b1c954d3e446cedf1cdb1dc949548af295966c75), short as `d4`

And here things that happended: NBXplorer received transaction `d3` because one adress of outputs had matched my derivation, `d4 `had not(No problem here). But later transaction `d4` was accepted and confirmed by testnet. So transaction `d3` remained `Unconfirmed` status(confirmations 0), and I couldn't query or tell the transaction as invalid. So, how?

**Comment by chaoyebugao** [comment]
There is the transaction d3 query result from API 'v1/cryptos/btc/transactions/d32e355859cbf8b82ccdb0d9087035f66641c0c14dc33ee9f1533d7d511dae87':
`{
    "confirmations": 0,
    "blockId": null,
    "transactionHash": "d32e355859cbf8b82ccdb0d9087035f66641c0c14dc33ee9f1533d7d511dae87",
    "transaction": "01000000000101af3f0e96d42ad460d06c028476a33aea8d3cb3d985b51157cf846ed07bfe66450100000000f0ffffff0340420f0000000000160014435e4fa8e93a10aef7bbbb1368aa34ceeca942444dff17000000000017a914c1111170ab7fd9b02e6c96eda3a0a6b45a0795da8700000000000000002b6a2968747470733a2f2f746274632e6269746170732e636f6d20646f75626c65207370656e6420746573740247304402204c062a0d2e01a028aa0a16ec8c1b100ad75a2f4baba4a890ecc77414b9b16ec702203f2df04b4786e0b0b09a8a0ab0546b5bdbd1cfeb3fd8380294b38a77a8575b9d0121034af5f37bee2cb7749be1215f08a0cf04d92774ff89ae2f80a0a983ce3caefa9500000000",
    "height": null,
    "timestamp": 1575021455
}`

**Comment by NicolasDorier** [comment]
so normally here is what happen, and this is actually in the unit tests:

If d3 and d4 conflict, the `GetTransactions` will show the last one received in `Unconfirmed` transaction list, and the other in the `Replaced` transaction list.
When `Unconfirmed` get confirmed, the transaction in `Replaced` disappear.

Due to the inherent design of NBXplorer, I can only tell if a transaction has been replaced if you call

`v1/cryptos/{cryptoCode}/derivations/{derivationScheme}/transactions/{txId}`, but not if you call `v1/cryptos/btc/transactions/d32e355859cbf8b82ccdb0d9087035f66641c0c14dc33ee9f1533d7d511dae87`

**Comment by chaoyebugao** [comment]
> so normally here is what happen, and this is actually in the unit tests:
> 
> If d3 and d4 conflict, the `GetTransactions` will show the last one received in `Unconfirmed` transaction list, and the other in the `Replaced` transaction list.
> When `Unconfirmed` get confirmed, the transaction in `Replaced` disappear.
> 
> Due to the inherent design of NBXplorer, I can only tell if a transaction has been replaced if you call
> 
> `v1/cryptos/{cryptoCode}/derivations/{derivationScheme}/transactions/{txId}`, but not if you call `v1/cryptos/btc/transactions/{txId}`
> 
> Because I know a transaction is replaced only when I "replay" all the transactions belonging to the `derivationScheme`.

Sorry for replay so late, cuz what I met was the other situation, I think. It took me a while to figure it out.
What you said above is both transactions matching `derivationScheme`, but in my test it wasn't.`d3` matched my `derivationScheme` but `d4` did not. So It won't appear in `Replaced`.

I called `d3` with `v1/cryptos/{cryptoCode}/derivations/{derivationScheme}/transactions/{txId}`, and got `Unconfirmed`  result, moments nothing, It 404, because `d3` IS noting. So I use this API to query and mark transactions like `d3` as `Invalid`.  problem solved, so far so good.

By the way I used [https://tbtc.bitaps.com/](https://tbtc.bitaps.com/) to create double spend.

**Comment by NicolasDorier** [comment]
@chaoyebugao so another thing that happen with NBXplorer:

If I detect a transaction broadcasted impacting a derivation scheme, I will try to rebroadcast periodically.

If I see it is double spent (ie, the full node says "Missing inputs") then I will delete this transaction from the list in `v1/cryptos/{cryptoCode}/derivations/{derivationScheme}/transactions/{txId}` but NOT in `v1/cryptos/btc/transactions/{txId}` as I don't know if somebody will need it later.
