### ISSUE TITLE
Issue with Azure queue after upgrade nuget from 2.0.0.26 to 3.0.1

### ISSUE THREAD

**Issue by MoleDJ** [dgarage/NBXplorer#213]
I have working a nbxplorer installation with newtransaction messages sent to azure queue. I updated nuget from 2.0.0.26 to 3.0.1, updated the nbxplorer installation and now when i receive a message from the queue, it cannot be deserialized with the following error.
NBitcoin.JsonConverters.JsonObjectException: 'Invalid TrackedSource'

This works perfectly on 2.0.0.26, anyone had this problem?

My relevant pieze of code:
`  var network = new NBXplorer.NBXplorerNetwork(NBitcoin.Bitcoin.Instance, _currentBTCNetworkType);
            var serializer = new NBXplorer.Serializer(network);
            var newTransactionEvent = serializer.ToObject<NewTransactionEvent>(Encoding.UTF8.GetString(message.Body));`

**Comment by farukterzioglu** [comment]
For the right way to serialize, you can check the unit tests: https://github.com/dgarage/NBXplorer/blob/master/NBXplorer.Tests/UnitTest1.cs#L1105
It looks like you need to configure your serializer like;

```
NBXplorerNetwork networkForDeserializion = new NBXplorerNetworkProvider(NetworkType.Regtest).GetFromCryptoCode((string)cryptoCode); 
JsonSerializerSettings settings = new JsonSerializerSettings();
new Serializer(networkForDeserializion).ConfigureSerializer(settings);
```

**Comment by NicolasDorier** [comment]
@MoleDJ yes, now I basically need the network to properly deserialize the message.

You can get the `cryptoCode` @farukterzioglu is talking about in the message property (added here https://github.com/dgarage/NBXplorer/commit/ca9fa2117bc3503c310ad31981d3747da791807f)

**Comment by MoleDJ** [comment]
Cool It works now, i was hable to update my project to latest nugget versions successfully, thanks!
