### ISSUE TITLE
API "Get current balance" was removed?

### ISSUE THREAD

**Issue by chaoyebugao** [dgarage/NBXplorer#214]
Just for sure, API [` v1/cryptos/{cryptoCode}/derivations/{derivationScheme}/balance`](https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#get-current-balance) was removd?
I can not request it or find it in source.

**Comment by farukterzioglu** [comment]
It added recently with: https://github.com/dgarage/NBXplorer/commit/5ee8b32a560d45f4722642a0fef5960a78e6453e
Are you sure you have the recent version?
