### ISSUE TITLE
What could cause a transaction conflict?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#22]
I  have  tried to spend some coins via `var result = client.Broadcast(tx);` and got an `RPC_TRANSACTION_REJECTED`.

The NBXplorer reported:

`info: Explorer:       BTC: Transaction 04bfb179dd54e402a4a51197eb23364c24331e40127710521597b4b0d69c2390 failed to broadcast (Code: RPC_TRANSACTION_REJECTED, Message: Transaction was rejected by network rules, Details: 18: txn-mempool-conflict )`

What could cause such conflict? the tx was built successfully with enough funds.

**Comment by bazooka70** [comment]
Ah, I might be getting it now...
The thing is, I had **0.18** BTC confirmed in my wallet.

I sent **0.1** BTC via:

```
var coins = utxos.GetUnspentCoins(onlyConfirmed: true);
var keys = utxos.GetKeys(userExtKey, onlyConfirmed: true);
...
```
Note  the  `onlyConfirmed == true`

Then I sent again immediately another **0.1** BTC, and got that error: `RPC_TRANSACTION_REJECTED`

When I switched to 
```
var coins = utxos.GetUnspentCoins(onlyConfirmed: false);
var keys = utxos.GetKeys(userExtKey, onlyConfirmed: false);
...
```

builder.SendEstimatedFees(feeRate); reported `Not enough fund to cover the target with missing amount 0.01396678`
Which is correct.

So my question now, Do I always need to use `onlyConfirmed: false` when **SENDING** funds?

**Comment by NicolasDorier** [comment]
> At this point the confirmed balance was 0.18 and the unconfirmed was -0.1

Your unconfirmed balance should be `0.08`.

> Then I sent again immediately another 0.1 BTC, and got that error: RPC_TRANSACTION_REJECTED

Yes it is normal, because `onlyConfirmed` ignore any unconfirmed transaction (including the one which spent your 0.18 coin), so you are effectively double spending the `0.18` coin.

> Do I always need to use onlyConfirmed: false when SENDING funds

What really seems to want is to not filter out unconfirmed spent, but filter out unconfirmed UTXOs.
I will change the API to be better.

**Comment by NicolasDorier** [comment]
I just renamed `onlyConfirmed` to `excludeUnconfirmedUTXOs` and changed the behavior to better reflect what you were expecting. Update the client library to 1.0.1.15.

Test and close if it fix your issue.

**Comment by bazooka70** [comment]
Shouldnt you change the same for 

It seems I'm lost again...
My goal is to **not allow** any unconfirmed funds. (and definitely not spent funds).
When I send fund and I'm short (negative balance), and try to spend funds again, I got the correct behaviour I wanted: the `builder.SendEstimatedFees` rejected my transaction, which is OK and what I want.

But then I **received** 0.1 BTC, I could spend them right away, although they were still unconfirmed.

How do I void spending unconfirmed funds?

**Comment by bazooka70** [comment]
I think there is a problem with the `GetUnspentCoins`.

I received 2 BTC when I had zero.
The 2 BTC confirmed.

I then sent 1 BTC. while the 1 BTC I sent was not confirmed, checking:

var coinsConfirmed = utxos.GetUnspentCoins(excludeUnconfirmedUTXOs: true);
var balanceConfirmed = coinsConfirmed.Sum(x => x.Amount.ToDecimal(MoneyUnit.BTC));            

balanceConfirmed reported 0.
When i was expecting to see ~1 BTC.

**Comment by bazooka70** [comment]
BTW, i think you have wrong calculation for:
```
var coinsConfirmed = utxos.GetUnspentCoins(excludeUnconfirmedUTXOs: true);
var balanceConfirmed = coinsConfirmed.Sum(x => x.Amount.ToDecimal(MoneyUnit.BTC));   
```
You are missing unspent **confirmed** txs.

If I use
var coins = utxos.GetUnspentCoins(excludeUnconfirmedUTXOs: false); // get all
            List<Coin> _coinsConfirmed = new List<Coin>();            
            var utxoConfirmed = utxos.Confirmed.UTXOs;
            foreach (var utx in utxoConfirmed)
            {                
                _coinsConfirmed.Add(utx.AsCoin());                            
            }
            var _balanceConfirmed = _coinsConfirmed.Sum(x => x.Amount.ToDecimal(MoneyUnit.BTC));
            Console.WriteLine($"_balanceConfirmed: {_balanceConfirmed}");

I get different result for `balanceConfirmed ` and  `_balanceConfirmed`

**Comment by NicolasDorier** [comment]
> You are missing unspent confirmed txs.

Those confirmed UTXOs got spent by an unconf tx so you don't want them to appear here.
