### ISSUE TITLE
After upgrade to bitcoin 19.0.1 cannot rpc auth any more

### ISSUE THREAD

**Issue by neocogent** [dgarage/NBXplorer#223]
On Linux Mint 19 (Ubuntu 18.04) server (headless).

Just upgraded my bitcoin node. Tested and works fine with bitcoin-cli using same user/pwd as before. But NBXplorer (being used with btcpayserver) stopped working. Went in and checked and decided to upgrade all that. This involved updating dotnet to 3.0 as I guess I was on a pretty old version. That all went fine and ran the ./build.sh. No errors.

Still same issue. Trying to start NBXplorer with ./run.sh and get line:

`fail: Configuration:  BTC: Error connecting to RPC server Response status code does not indicate success: 401 (Unauthorized).`

Tested user/pwd again. I'm using btc.rpc.auth but tried with user and passowrd separate. Also tried using cookiefile path instead. All attempts still give me same error msg. Cannot get my btcpay node up again until I resolve why it suddenly stopped authorizing. I didn't change any auth values when updating to bitcoind 19.0.1 - simply replaced the binary and started again.

Does 19.0.1 respond differently to your auth test now?

Any ideas? Thx.

**Comment by neocogent** [comment]
Resolved. Doesn't seem to work when using run.sh but after editing my systemd service file to correctly use /netcoreapp3.0/ path it auth'd fine upon service start. So my mistake there and then confused by not getting valid auth with run script.

**Comment by NicolasDorier** [comment]
hey careful, next version of nbx is `netcoreapp3.1` (should not change for a while)
