### ISSUE TITLE
Does NBXplorer support OMNI-USDT?

### ISSUE THREAD

**Issue by chaoyebugao** [dgarage/NBXplorer#228]
I had full implementation with `NBXplorer` + `Bitcoincore` full node. Now I am searching a way to use `OMNI-USDT` easily, especially [Notifications via websocket](Notifications ) api-like. As `Omnicore` is a fork of `Bitcoincore`, shall it be easy to make it compatible with `Omnicore`? 
Yep, I am suggesting the combination of `NBXplorer` + `Omnicore`. Then I think this project could support `OMNI-USDT`.

**Comment by NicolasDorier** [comment]
No and it probably won't. Colored coins implementation requires full indexing and NBXplorer is not fully indexing. Though Liquid-USDT is soon supported.

**Comment by chaoyebugao** [comment]
Alright, thx for the reply.
