### ISSUE TITLE
How to get a list of transactions per derivation key?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#23]
How do I get a list of transactions in the NBXplorer client per xpub key?
Both **IN** and **OUT**? same as the Bitcoin Core shows in the `Transactions `tab.
Correct me if I'm wrong but the NBXplorer handles only outputs?

I also noticed that the server will only notify about "Money received". what about "Money sent"?
I mean if I _deliberately_ set the change address to some address not in my wallet (or spend my entire wallet), and send funds, the NBXplorer  won't capture this event/transaction. See this tx for example:
https://live.blockcypher.com/btc-testnet/tx/d74d4f8649e883c6a5b05227badd07cdd67bc017cbc9c69161dbc372839de9ff/
Where I did not create any output back for myself.

**Comment by NicolasDorier** [comment]
NBXplorer should notify your properly of funds going out of your wallet.  I will add a test though just to be sure.

**Comment by NicolasDorier** [comment]
You can use the transactions route as explained here https://github.com/dgarage/NBXplorer/blob/master/docs/API.md NBXplorer.Client has a call for this as well.

**Comment by bazooka70** [comment]
Cool, I used `client.GetTransactions(userDerivationScheme, null);`
Is there any (easy) way to distinguish between a "sent" vs. "received" transaction like Bitcoin Core shows?

**Comment by NicolasDorier** [comment]
well in TransactionInformation you can know what input or output got matched.
Send vs Received is not easy to know as some can be both.

**Comment by bazooka70** [comment]
What do you mean by "got matched"?

This is what i did for testing if the Tx **input** was made by my wallet - meaning it is a "Send":

```
var pubKey = userExtKey.Neuter().Derive(new KeyPath("0/0")).PubKey;
foreach (var tx in allTransactions.OrderByDescending(x => x.Timestamp))
{
  var inputs = tx.Transaction.Inputs;
  Console.WriteLine($"IsFrom PubKey: {inputs[0].IsFrom(pubKey)}");
}
```

It did gave accurate results. What do you think?

**Comment by NicolasDorier** [comment]
It turns out I am not including enough info in the call to know what is belonging to you.

I advise you against doing the above as you are using a single address.

**Comment by bazooka70** [comment]
Shouldn't the `var isFromPubKey = inputs.Where(u => u.IsFrom(pubKey)).Count() > 0;`
return correct results for all addresses in my wallet?

**Comment by NicolasDorier** [comment]
So I just updated [GetTransactions](https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#query-transactions) and added more information about what got matched in the transaction. Notice the `balanceChange` field as well as `inputs` and `outputs`.

You need to update the server and the client (1.0.1.22 and 1.0.1.16 respectively)

Close if it solves your problem.

Again, try not to use address reuse. It will make your code more complicated than it should be while hurting privacy of yourself and others.

**Comment by bazooka70** [comment]
This is really awesome! :+1: 

I have a few observations:

1. 
The transaction **Size** reported in Bitcoin Core and on blockchain.info are different for transactions that were **received** from Bitcoin Core to my wallet. I used `tx.Transaction.GetVirtualSize()` as you suggested previously in one of our discussions.

2. 
A `tx.Transaction.TotalIn` would be nice too (there is a `tx.Transaction.TotalOut` which is great). It would also help extract the final fees.

**Comment by NicolasDorier** [comment]
Use `GetVirtualSize()` for fee calculation and `GetSerializedSize()` for thereal size.

`tx.Transaction.TotalIn` is impossible, the information about input values are unknown at the Transaction level.

**Comment by bazooka70** [comment]
> Use GetVirtualSize() for fee calculation and GetSerializedSize() for the real size.

My bad. I forgot about `GetSerializedSize`.

> tx.Transaction.TotalIn is impossible

Block chain info manages to get `Total Input`:

https://testnet.blockchain.info/tx/53f7b1f3fc729e0ed12d6d06a1ece91efd4467cd461acf6f79e844b043c53f28

I guess it  lookup the the outs Txs of the inputs.

How can I get the Fees of the transaction?

**Comment by NicolasDorier** [comment]
It is not possible with NBXplorer because it requires the indexing of all transaction in the blockchain.

I may be able to do it if all inputs belong to the queried wallet. But not all transactions.

**Comment by bazooka70** [comment]
OK, I think I got it (maybe). I could not get the Fee for a **received** tx.
But for transactions sent from my wallet I could do:
```

if (txInputs.Count > 0) // Sent from my wallet
{
  var TotalIn = tx.Inputs.Sum(x => x.Value.ToDecimal(MoneyUnit.BTC));
  var fee = TotalIn - tx.Transaction.TotalOut.ToDecimal(MoneyUnit.BTC);
}

```

**Comment by NicolasDorier** [comment]
Yes you can do that, but it will work only for the transactions you send.

**Comment by bazooka70** [comment]
Yes, that's good enough for me. Bitcoin Core does not display Fee of a received tx either. I don't really care about what the sender Fee was.

**Comment by bazooka70** [comment]
BTW, `if (tx.Inputs.Count > 0)` 
Is this the correct check for determining if the funds were absolutely sent from my wallet (i.e. a "Sent" tx)?
Or maybe check `tx.BalanceChange < 0`?

**Comment by NicolasDorier** [comment]
Yes I think you should check `BalanceChange`.
