### ISSUE TITLE
Can NBXplorer be used for Non HD Wallets

### ISSUE THREAD

**Issue by Grey007** [dgarage/NBXplorer#234]
Hi,

Can NBXplorer be used for non HD Wallets? 

Thanks!

**Comment by NicolasDorier** [comment]
no

**Comment by NicolasDorier** [comment]
It can for some operations (see https://github.com/dgarage/NBXplorer/blob/master/docs/API.md)

Those operation are mainly for supporting some layer 2 scenarios.
The design of NBXplorer is made for HD, doing otherwise, while possible will make your life harder.
