### ISSUE TITLE
Liquid GetBalance Example

### ISSUE THREAD

**Issue by nharmon9** [dgarage/NBXplorer#237]
I have been testing Liquid and Liquid Asset things, but as there is no regtest option I made my own Elements Regtest and stuck it into NBitcoin and NBXplorer locally. How exactly do I deal with `AssetMoney`? Right now when I print to the console it only displays a 0.0000000.

**Comment by nharmon9** [comment]
Update if I Unblind the addresses NBX will return the balance but when the GenerateWallet contains multiple types of assets it returns the total of all of them.

**Comment by NicolasDorier** [comment]
have you read https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#liquid

**Comment by nharmon9** [comment]
Thank you, I have read that. I have also looked at the elements unit tests and in BTCPay. I am still confused and apologize as I am sure it is my fault. I have tried three methods so far:

1. To get the asset Id's from the transactions
```
var Txs = client.GetTransactions(userDerivationScheme).ConfirmedTransactions.Transactions;
            foreach (var tx in Txs)
            {
                var txid = tx.Transaction;
                var elementstxid = (ElementsTransaction)txid;
                MoneyBag bag = (MoneyBag)tx.BalanceChange;
                foreach (var asset in bag)
                {
                    var e = (AssetMoney)asset;
                    var f = e.Id;
                    var g = e.Quantity;
                    Console.WriteLine(f + ":  " + g);
                }
            }
```
2. To get them from  `GetUTXOs` and `GetUnspentCoins`
```
var utxos = client.GetUTXOs(userDerivationScheme);
            var coins = utxos.GetUnspentCoins();

            foreach (Coin coin in coins)
            {
                var y = coin.Amount;
                var txout = (ElementsTxOut)coin.TxOut;
                var z = coin.TxOut;
                
                Console.WriteLine(y.ToString());
            }
```

3. From `GetBalance`
```
var balance = (MoneyBag)client.GetBalance(userDerivationScheme).Total;

foreach( var s in balance)
            {
                var a = (AssetMoney)s;
                var b = a.AssetId;
                var c = a.Quantity;
                Console.WriteLine("{0}:  {1}" , b, c);

            }
```
I have tried using both NBitcoin.OpenAsset and NBXplorer `AssetBalance`.

**Comment by NicolasDorier** [comment]
You need to use NBXplorer `AssetMoney`.

Can you write me a test or a simple code of what you do and what you expect?

**Comment by nharmon9** [comment]
Ok, after playing around I think the problem was with the unblinded flag. When I would `Generate Wallet` and then add the `-[unblinded]` flag to the to the `Dervivation Scheme` both `GetBalance` and `GetTransactions` showed `null` for quantity and value.

**Comment by NicolasDorier** [comment]
@nharmon9 seems like a bug, ping @Kukks

**Comment by Kukks** [comment]
This is as expected based on the discussion while adding the unblinded flag at https://github.com/dgarage/NBXplorer/pull/230

When adding the unblinded flag to an existing wallet, it is treated as a completely new wallet

**Comment by NicolasDorier** [comment]
@Kukks I think this is a different issue.
He generated an unblinded wallet, sent money there, and get null.

**Comment by Kukks** [comment]
No he is using the Generate Wallet api, then adding the unblinded flag afterwards. 
If he received money to  before adding the unblinded flag, the unblinded deriv would not know about it as it is a separate wallet in the eyes of NBX

**Comment by nharmon9** [comment]
Yes I use the Generate Wallet api then immediately add the unblinding flag. Then send AssetMoney to the wallet. The unblinded flag does show the transaction with 4 outputs all show null value except for the fee one.

On a completely separate note, it is stated not to expose NBX on the internet. I am building a Liquid mobile app using NBitcoin and NBX should I put the whole NBX in the phone or just the NBX.Client?

**Comment by NicolasDorier** [comment]
@nharmon9 don't mix unblinded and blinded, we don't support it, and we can't fix it. (it would need too much refactoring that I don't want to do for a shitcoin)

**Comment by NicolasDorier** [comment]
You would put just NBX.Client on the phone... You should protect access of your NBXplorer, if anybody get access to it, there is many way to DDoS your server.

**Comment by nharmon9** [comment]
Ok, thank you @NicolasDorier and @Kukks you are the best. Sidechains are better shitcoins than a Bcash  or Eth though, at least sidechains are additive.

**Comment by nharmon9** [comment]
@Kukks How do you build an ElementsTransaction?

**Comment by NicolasDorier** [comment]
@nharmon9 if you use L-BTC, you can follow examples on https://programmingblockchain.gitbook.io/programmingblockchain/ that I used for Bitcoin, but instead using Liquid network. It does not support multi asset at the moment though.

**Comment by nharmon9** [comment]
Yes I loved the book and thank you very much for your contributions to everything Bitcoin. I have been going by the Spend Your Coin chapter, but I am having trouble with Asset Coin signing. Is it possible to craft and sign an Elements based transaction using NBitcoin at the moment. Of course I understand that Liquid is shitcoin and building on Bitcoin is far more pressing, but I feel layer 2 tech is important to at least explore.

**Comment by NicolasDorier** [comment]
@nharmon9 AssetCoin inside NBitcoin is a concept for OpenAsset.
AssetCoin in NBXplorer is a concept for Liquid.

The transaction builder does not support AssetCoin for liquid. If you want to spend L-BTC though, you can use plain old Coin.

**Comment by nharmon9** [comment]
Ok that's what I thought, thanks. And just to clarify Coin does not work with liquid assets?

**Comment by NicolasDorier** [comment]
Coin works for L-BTC only. Not any other assets.

**Comment by nharmon9** [comment]
Gotcha. Does it have to do with the blinding sig, what about getting it to work with unblinded tx

**Comment by NicolasDorier** [comment]
It only work for unblinded sig,it works like bitcoin.

**Comment by nharmon9** [comment]
Oh. I would like to help to add in elements/liquid based assets. What would be the best way to help?

**Comment by NicolasDorier** [comment]
I don't know myself where I would start, that's for you to find out :p

**Comment by nharmon9** [comment]
haha thx

**Comment by stefan52a** [comment]
I'm not aware of a real Elements mobile client, therefore I am interested in building one myself too. @nharmon9 how far did you get?

FYI:
I have prototyped an app based upon [https://github.com/btcontract/lnwallet](https://github.com/btcontract/lnwallet) , see [https://www.zoof-it.com/app-1](https://www.zoof-it.com/app-1). And now this prototype has been modified to use 3 assets using an Elements-project blockchain. But the app is terribly insecure.
Given that I am somewhat versed in C#, and experimented with NBitcoin, I thought wasabi would be good candidate to explore a desktop and eventually mobile Elements wallet.

So @nharmon9 I am very much interested in your work. Care to share somewhat more?

**Comment by nharmon9** [comment]
Sure but I will have to get back to you on monday

**Comment by nharmon9** [comment]
So where I have been playing with https://github.com/Simplexum/python-elementstx and blockstreams gdk they have a branch working on electrum calls, https://github.com/Blockstream/gdk, to their electrs fork. Check it out

**Comment by stefan52a** [comment]
Thank you! 
Frankly, although working/programming for a long time and with Btc for 2 years, I am a bit overwhelmed. I will digest and get back to you ASAP (might be a week), with a reaction.
