### ISSUE TITLE
Bug: NBXplorer depends on non-essential calls to bitcoin RPC

### ISSUE THREAD

**Issue by Kixunil** [dgarage/NBXplorer#239]
Problem
-----------

I use [`btc-rpc-proxy`](https://github.com/Kixunil/btc-rpc-proxy) to improve the security and I've found out that NBXplorer makes some strange calls that clearly aren't needed for the fucntion of UTXO tracking. So far I've found these calls weird:

* `generatetoaddress` - Is it trying to mine bitcoins?!
* `setban`
* `signrawtransactionwithkey` - harmless, but NBXplorer should have no keys to use for signing
* there might be others, sadly, instead of continuing, NBXplorer fails, so I'm unable to determine other fail attempts (so far each means manual whitelisting, I ended at setban, as I really don't want to whitelist that one)

Expected behavior
------------------------
NBXplorer only accesses public calls and doesn't attempt to mine, reconfigure bitcoind or spend bitcoins

What actually happens
-----------------------------
NBXplorer is issuing unnecessary calls.

Version: latest

**Comment by Kixunil** [comment]
So I've figured it out pretty much completely. First calls are capability checks in NBitcoin. I'll file issue against that one to accept unauthorized responses as incapabilities.

Lastly, there's hard-coded banlist. I really don't understand why it's mandatory, hard-coded part of NBXplorer. Banning misbehaving peers is completely unrelated to address tracking. So I propose to remove it entirely. If someone still wants to ban those peers, he can trivially run `sh banlist` - it's a shell script!

I'll do the PR, if you want.

**Comment by NicolasDorier** [comment]
@Kixunil the calls are done by [this call] (https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/RPC/RPCClient.cs#L329).

This is done for two reasons: 
1. Our `RPCClient` class use this information to protect against breaking changes in Bitcoin Core RPC.
2. We expose the capabilities of the node in the `/status` route.

**Comment by NicolasDorier** [comment]
`setban` is loading a list from [gmaxwell](https://people.xiph.org/~greg/banlist.cli.txt) of suspicious node not following the protocol correctly (probably spy nodes)

**Comment by NicolasDorier** [comment]
I will relax the failure today or next week to make your stuff work out of the box.

**Comment by Kixunil** [comment]
Yeah, I figured it out and changed the title to better reflect the fundamental problem.

Thanks a lot for help!

**Comment by NicolasDorier** [comment]
The capability scan should normally not be a problem. Is there anything else to fix?

**Comment by Kixunil** [comment]
Thanks for that banlist fix! I didn't test yet, but I believe it should work. BTW, the name `LoadBanList` is a bit confusing, at first it seemed like only "load from file", but it also applies it. Maybe call it `LoadAndApplyBanList`? Or just `ApplyBanList`?

The most pressing issue is indeed fixed by that change, but it'd be really nice if https://github.com/MetacoSA/NBitcoin/issues/808 was implemented. I'd feel more confident with security, if I could block generatetoaddress too. Of course, if you don't have time for that, I can understand.

Is there any documentation on what exactly scantxoutset is used for in NBXplorer and BTCPayServer? I have suspicion that blocking that one too would be also meaningful for security, but I wnt to understand first if it's an essential or importnt part of one of these projects.

**Comment by NicolasDorier** [comment]
I made a new version of NBitcoin, 5.0.14. Please bump NBXplorer and let me know if it fix your issue.

**Comment by NicolasDorier** [comment]
`scantxoutset` is used by btcpayserver to restore a wallet.

**Comment by NicolasDorier** [comment]
This one https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#scanUtxoSet

**Comment by Kixunil** [comment]
It works, thanks! Could you tag the new version of NBXplorer, please?

**Comment by NicolasDorier** [comment]
I just bumped to v2.1.9

**Comment by Kixunil** [comment]
Awesome, thanks a lot!
