### ISSUE TITLE
What does "Transaction 098264...e62e27 is evicted from local mempool" means?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#24]
The server reports sometimes that

> "Transaction XXXXX is evicted from local mempool"

What does it mean exactly?
Thanks.

**Comment by NicolasDorier** [comment]
Nothing to be worried about. NBXplorer index everything twice, once TX A is unconfirmed and once TX A get confirmed. I am cleaning the database lazily when you query those transaction and notice I have two times the same information.

**Comment by bazooka70** [comment]
I see. that make sense. thank you!
