### ISSUE TITLE
RabbitMQ NewTransaction not firing

### ISSUE THREAD

**Issue by mr-e-** [dgarage/NBXplorer#240]
I am receiving the exchange for NewBlock but there is no exchange for NewTransaction even being added to the rabbitmq exchange list.

**Comment by NicolasDorier** [comment]
Ping @farukterzioglu . It is normally properly in the unit tests and run during the CI, but maybe it is a bug not covered?

**Comment by farukterzioglu** [comment]
@mr-e-  Can you send your settings related RabbitMq? Did you set 'rmqtranex' to your expected exchange name?

**Comment by NicolasDorier** [comment]
ping @mr-e-

**Comment by brandoncollins7** [comment]
I resolved the issue, I didn't realize I had to call track on an address before receiving the notification, I thought it should be firing for all blocks and transactions.

**Comment by mr-e-** [comment]
I resolved the issue, I didn't realize I had to call track on an address before receiving the notification, I thought it should be firing for all blocks and transactions.
