### ISSUE TITLE
How to tell an uxto is spent?

### ISSUE THREAD

**Issue by chaoyebugao** [dgarage/NBXplorer#250]
As title says, I have a transaction and I have to check it's outputs': spent or not, so what API can do this? I can not find out this.

**Comment by NicolasDorier** [comment]
Give your transaction to https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#broadcast with `testMempoolAccept` to `true` and check what is the errorif there is a double spend.

**Comment by chaoyebugao** [comment]
> Give your transaction to https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#broadcast with `testMempoolAccept` to `true` and check what is the errorif there is a double spend.

It looks so hacky and inconvenience.

I find a way, I can use the API [Get Unspent Transaction Outputs (UTXOs)](https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#get-unspent-transaction-outputs-utxos) and get all UXTOs, if the UXTO/Outpoint is included, is unspent, otherwise it is sopent. It's a right way?

**Comment by NicolasDorier** [comment]
There is no other way. NBXplorer does not track all UTXOs, only the utxo of wallets you are tracking.
Bitcoin Core does not expose the UTXO set to outside either.

You could query the UTXOs of the wallet and check if the utxo you have are inside as well, but I don't recommend as it is probably less performant than just doing the broadcast.

**Comment by chaoyebugao** [comment]
Understood.Thanks~(*￣︶￣)~
