### ISSUE TITLE
API "Get Unspent Transaction Outputs of a specific address" not found in NBXplorer.Client

### ISSUE THREAD

**Issue by chaoyebugao** [dgarage/NBXplorer#251]
Currently my `NBXplorer.Client` version is 3.0.6, and I could not find API [Get Unspent Transaction Outputs of a specific address](https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#get-unspent-transaction-outputs-of-a-specific-address) inside it. Did I miss sth?

**Comment by NicolasDorier** [comment]
You can't use balance for specific address if you use derivation strategy. The best way is to get the UTXOs, and filter on your side.
