### ISSUE TITLE
Can't get transactions from tracked address 

### ISSUE THREAD

**Issue by menavas** [dgarage/NBXplorer#253]
Hi, I'm trying to get an utxo from an specific address and the rest client return 0 transactions, the server status API works fine, and the -txindex parameter is used in the local btc node (testnet), I don't know what I am doing wrong.

In the other hand I don't know how to put the derivation path in the API call to trak it.

Best Regards.

**Comment by NicolasDorier** [comment]
you need to track the address first, then you can query.
Also, it will only see the transaction arriving AFTER it has been tracked from first time.

**Comment by menavas** [comment]
Very well, I could track the address in the Rest API, but in the code, still returning 0 utxos, this lead me to the next question, if I need to track by the "derivation scheme", this derivation scheme is the same thing as "derivation path"? where can I find some sample of this derivation scheme format, I saw it in the documentation but I'd like to see an example, but I couldn't find it.

Thank you so much for your help so far

Best Regards

**Comment by NicolasDorier** [comment]
Read https://programmingblockchain.gitbook.io/programmingblockchain/ so you understand what it is.
