### ISSUE TITLE
No address field returned by "new unused adddress" endpoint

### ISSUE THREAD

**Issue by WolvenSpirit** [dgarage/NBXplorer#255]
Hello,
I have a bitcoind and nbxplorer running in docker and while calling to get a new unused address with an xpub that i previously called track on i get the following response:

`{"feature":"Deposit","derivationStrategy":"xpub6DGuCMaS68qQtGhRnQnoriRYA7coZL5BaoTSqPgxbGp1S5oNnP7EXhE4fRXVtCoAnokhMcUnSYaZPAtR1rFFwqBAn4fvQwEp41mX5nrnN92-[legacy]","keyPath":"0/0","scriptPubKey":"76a914e76fda097e0fa03aba701ca92b37c500c4c11c0588ac","redeem":null}`

Calling without that `-[legacy]` returns:
`{"httpCode":404,"code":"strategy-not-found","message":"This strategy is not tracked, or you tried to skip too much unused addresses"}`

example constructed url that I call to:
`http://localhost:32838/v1/cryptos/BTC/derivations/xpub6DGuCMaS68qQtGhRnQnoriRYA7coZL5BaoTSqPgxbGp1S5oNnP7EXhE4fRXVtCoAnokhMcUnSYaZPAtR1rFFwqBAn4fvQwEp41mX5nrnN92-[legacy]/addresses/unused`

I would have hoped to at least return an error to give a hint of what is wrong.
I've searched for similar issues yet I did not find this particular case, any suggestions would be greatly appreciated, thanks.

**Comment by WolvenSpirit** [comment]
As an update, calling to track without the legacy flag and then new address returns the same response without the address field for about half a minute or so after which it returns 404.
I'm guessing that some routine that would need to generate the addresses silently fails or some process when attempting to track ultimately fails and the xpub is discarded. Hopefully im wrong.

**Comment by NicolasDorier** [comment]
This is strange, this never happened to me. We never delete anything from the database.
I would like a step by step way I can reproduce the issue.

**Comment by WolvenSpirit** [comment]
I'm running a stripped down version of the production docker-compose file with local folders mounted to containers because I already have the chain downloaded, much is left unmodified:

version: "3"
services:
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:1.0.2.31
    expose:
     - "32838"
    ports:
      - 32838:32838
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-mainnet}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
    - /home/mihai/datadir/Main:/datadir/Main
    - "/home/mihai/.bitcoin:/root/.bitcoin"
    links:
    - bitcoind
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: nicolasdorier/docker-bitcoin:0.16.3
    #entrypoint: /usr/local/bin/bitcoind
    volumes:
    - "/home/mihai/.bitcoin:/home/bitcoin/.bitcoin"
    ports:
      - 43782:43782
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcuser=bitcoin
        rpcpassword=12345
        ${NBITCOIN_NETWORK:-mainnet}=1
        port=39388
        whitelist=0.0.0.0/0
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
    expose:
    - "43782"
    - "39388"
    - "28332"
    - "28333"

Call to track the address via firefox RESTClient:
`curl -X POST -H 'Authorization: Basic X19jb29raWVfXzo4MGE0YTRmZWQ3MTA0Zjc3YmUwODNkNDQ0ZGZiY2ZkM2E4ZGQwODgwZWE3NDBhYjgxMGRiNjdmZDBiZDUyZDc5' -i http://localhost:32838/v1/cryptos/BTC/derivations/xpub6DGuCMaS68qQtGhRnQnoriRYA7coZL5BaoTSqPgxbGp1S5oNnP7EXhE4fRXVtCoAnokhMcUnSYaZPAtR1rFFwqBAn4fvQwEp41mX5nrnN92` of course the basic auth part needs to be replaced.
returns: 
    Status Code: 200 OK
    content-length: 0
    date: Wed, 22 Apr 2020 08:08:31 GMT
    server: Kestrel

Now, I call to get unused address:
`curl -X GET -H 'Authorization: Basic X19jb29raWVfXzo4MGE0YTRmZWQ3MTA0Zjc3YmUwODNkNDQ0ZGZiY2ZkM2E4ZGQwODgwZWE3NDBhYjgxMGRiNjdmZDBiZDUyZDc5' -i http://localhost:32838/v1/cryptos/BTC/derivations/xpub6DGuCMaS68qQtGhRnQnoriRYA7coZL5BaoTSqPgxbGp1S5oNnP7EXhE4fRXVtCoAnokhMcUnSYaZPAtR1rFFwqBAn4fvQwEp41mX5nrnN92/addresses/unused`
returns:

    Status Code: 200 OK
    content-type: application/json; charset=utf-8
    date: Wed, 22 Apr 2020 08:12:02 GMT
    server: Kestrel
    transfer-encoding: chunked

body:
`{"feature":"Deposit","derivationStrategy":"xpub6DGuCMaS68qQtGhRnQnoriRYA7coZL5BaoTSqPgxbGp1S5oNnP7EXhE4fRXVtCoAnokhMcUnSYaZPAtR1rFFwqBAn4fvQwEp41mX5nrnN92","keyPath":"0/0","scriptPubKey":"0014e76fda097e0fa03aba701ca92b37c500c4c11c05","redeem":null}`
Subsequent calls ultimately return:

    Status Code: 404 Not Found
    content-type: application/json; charset=utf-8
    date: Wed, 22 Apr 2020 08:15:14 GMT
    server: Kestrel
    transfer-encoding: chunked
with body:

`{"httpCode":404,"code":"strategy-not-found","message":"This strategy is not tracked, or you tried to skip too much unused addresses"}`

**Comment by NicolasDorier** [comment]
can you try without mapping `/home/mihai/datadir/Main:/datadir/Main` if you can reproduce?

**Comment by NicolasDorier** [comment]
Tried to reproduce on regtest, locally, I can't.

`Subsequent calls ultimately return:` what is "ultimately"? After 1H, 1min ?

**Comment by WolvenSpirit** [comment]
After 1 minute or less, thanks for the input i'll try a test without the mapping.

The thing is I am also interacting with bitcoind using an rpc library that requires authentication and I set auth credentials hence I need to change those in Main and TestNet for nbxplorer to still have access to bitcoind.

**Comment by NicolasDorier** [comment]
@WolvenSpirit remove just the mapping of NBXplorer datadir, not the bitcoind one.

**Comment by WolvenSpirit** [comment]
Without the mapping the same call returns:



    Status Code: 400 Bad Request
    content-type: application/json; charset=utf-8
    date: Wed, 22 Apr 2020 12:34:18 GMT
    server: Kestrel
    transfer-encoding: chunked

body: `{"httpCode":400,"code":"invalid-format","message":"Invalid derivation scheme"}`
why would an xpub be invalid, I don't know much about blockchain, I admit.

**Comment by NicolasDorier** [comment]
@WolvenSpirit give full logs.

**Comment by WolvenSpirit** [comment]
There are no relevant errors in the logs, even with `--verbose=true` it outputs only info level.

Attaching to btcpayserver_bitcoind, production_nbxplorer_1
btcpayserver_bitcoind | 2020-04-22 16:23:52 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 
btcpayserver_bitcoind | 2020-04-22 16:23:52 Bitcoin Core version v0.16.3 (release build)
btcpayserver_bitcoind | 2020-04-22 16:23:52 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
btcpayserver_bitcoind | 2020-04-22 16:23:52 Assuming ancestors of block 0000000002e9e7b00e1f6dc5123a04aad68dd0f0968d8c7aa45f6640795c37b1 have valid signatures.
btcpayserver_bitcoind | 2020-04-22 16:23:52 Setting nMinimumChainWork=00000000000000000000000000000000000000000000002830dab7f76dbb7d63
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using the 'sse4' SHA256 implementation
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using RdRand as an additional entropy source
btcpayserver_bitcoind | 2020-04-22 16:23:52 Default data directory /home/bitcoin/.bitcoin
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using data directory /home/bitcoin/.bitcoin/testnet3
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using config file /home/bitcoin/.bitcoin/bitcoin.conf
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using at most 125 automatic connections (1048576 file descriptors available)
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using 4 threads for script verification
btcpayserver_bitcoind | 2020-04-22 16:23:52 scheduler thread start
btcpayserver_bitcoind | 2020-04-22 16:23:52 libevent: getaddrinfo: address family for nodename not supported
btcpayserver_bitcoind | 2020-04-22 16:23:52 Binding RPC on address :: port 43782 failed.
btcpayserver_bitcoind | 2020-04-22 16:23:52 HTTP: creating work queue of depth 16
btcpayserver_bitcoind | 2020-04-22 16:23:52 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
btcpayserver_bitcoind | 2020-04-22 16:23:52 HTTP: starting 4 worker threads
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using wallet directory /home/bitcoin/.bitcoin/testnet3/wallets
btcpayserver_bitcoind | 2020-04-22 16:23:52 init message: Verifying wallet(s)...
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using wallet wallet.dat
btcpayserver_bitcoind | 2020-04-22 16:23:52 CDBEnv::Open: LogDir=/home/bitcoin/.bitcoin/testnet3/wallets/database ErrorFile=/home/bitcoin/.bitcoin/testnet3/wallets/db.log
btcpayserver_bitcoind | 2020-04-22 16:23:52 Cache configuration:
btcpayserver_bitcoind | 2020-04-22 16:23:52 * Using 2.0MiB for block index database
btcpayserver_bitcoind | 2020-04-22 16:23:52 * Using 8.0MiB for chain state database
btcpayserver_bitcoind | 2020-04-22 16:23:52 * Using 440.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
btcpayserver_bitcoind | 2020-04-22 16:23:52 init message: Loading block index...
btcpayserver_bitcoind | 2020-04-22 16:23:52 Opening LevelDB in /home/bitcoin/.bitcoin/testnet3/blocks/index
btcpayserver_bitcoind | 2020-04-22 16:23:52 Opened LevelDB successfully
btcpayserver_bitcoind | 2020-04-22 16:23:52 Using obfuscation key for /home/bitcoin/.bitcoin/testnet3/blocks/index: 0000000000000000
nbxplorer_1  | info: Configuration:  Data Directory: /datadir
nbxplorer_1  | info: Configuration:  Configuration File: /datadir/TestNet/settings.config
nbxplorer_1  | info: Configuration:  Network: Testnet
nbxplorer_1  | info: Configuration:  Supported chains: BTC
nbxplorer_1  | info: Configuration:  Network: Testnet
nbxplorer_1  | info: Configuration:  Supported chains: BTC
nbxplorer_1  | info: Configuration:  BTC: Testing RPC connection to http://bitcoind:43782/
nbxplorer_1  | Hosting environment: Production
nbxplorer_1  | Content root path: /app/
nbxplorer_1  | Now listening on: http://0.0.0.0:32838
nbxplorer_1  | Application started. Press Ctrl+C to shut down.
nbxplorer_1  | info: Configuration:  BTC: Transient error 'Loading block index...', retrying soon...
nbxplorer_1  | info: Configuration:  BTC: Transient error 'Loading block index...', retrying soon...
nbxplorer_1  | info: Configuration:  BTC: Transient error 'Loading block index...', retrying soon...
nbxplorer_1  | info: Configuration:  BTC: Transient error 'Loading block index...', retrying soon...
btcpayserver_bitcoind | 2020-04-22 16:24:00 LoadBlockIndexDB: last block file = 181
btcpayserver_bitcoind | 2020-04-22 16:24:00 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=2779, size=54285446, heights=1718554...1721332, time=2020-04-16...2020-04-22)
btcpayserver_bitcoind | 2020-04-22 16:24:00 Checking all blk files are present...
btcpayserver_bitcoind | 2020-04-22 16:24:00 LoadBlockIndexDB: transaction index disabled
btcpayserver_bitcoind | 2020-04-22 16:24:00 Opening LevelDB in /home/bitcoin/.bitcoin/testnet3/chainstate
btcpayserver_bitcoind | 2020-04-22 16:24:00 Opened LevelDB successfully
btcpayserver_bitcoind | 2020-04-22 16:24:00 Using obfuscation key for /home/bitcoin/.bitcoin/testnet3/chainstate: f5fd8594aea1ded6
btcpayserver_bitcoind | 2020-04-22 16:24:01 Loaded best chain: hashBestChain=00000000000001e119b6fc0c06899fbc4a7165eb597cb8cd4690a2f5ab528a77 height=1721332 date=2020-04-22 16:08:09 progress=0.999998
btcpayserver_bitcoind | 2020-04-22 16:24:01 init message: Rewinding blocks...
nbxplorer_1  | info: Configuration:  BTC: Transient error 'Rewinding blocks...', retrying soon...
btcpayserver_bitcoind | 2020-04-22 16:24:08 init message: Verifying blocks...
btcpayserver_bitcoind | 2020-04-22 16:24:08 Verifying last 6 blocks at level 3
btcpayserver_bitcoind | 2020-04-22 16:24:08 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
btcpayserver_bitcoind | 2020-04-22 16:24:08 No coin database inconsistencies in last 7 blocks (660 transactions)
btcpayserver_bitcoind | 2020-04-22 16:24:08  block index           15474ms
btcpayserver_bitcoind | 2020-04-22 16:24:08 init message: Loading wallet...
btcpayserver_bitcoind | 2020-04-22 16:24:08 nFileVersion = 160300
btcpayserver_bitcoind | 2020-04-22 16:24:08 Keys: 2001 plaintext, 0 encrypted, 2001 w/ metadata, 2001 total
btcpayserver_bitcoind | 2020-04-22 16:24:08  wallet                   22ms
btcpayserver_bitcoind | 2020-04-22 16:24:08 setKeyPool.size() = 2000
btcpayserver_bitcoind | 2020-04-22 16:24:08 mapWallet.size() = 0
btcpayserver_bitcoind | 2020-04-22 16:24:08 mapAddressBook.size() = 0
btcpayserver_bitcoind | 2020-04-22 16:24:08 mapBlockIndex.size() = 1721333
btcpayserver_bitcoind | 2020-04-22 16:24:08 nBestHeight = 1721332
btcpayserver_bitcoind | 2020-04-22 16:24:08 torcontrol thread start
btcpayserver_bitcoind | 2020-04-22 16:24:08 Bound to [::]:39388
btcpayserver_bitcoind | 2020-04-22 16:24:08 Bound to 0.0.0.0:39388
btcpayserver_bitcoind | 2020-04-22 16:24:08 init message: Loading P2P addresses...
btcpayserver_bitcoind | 2020-04-22 16:24:08 Leaving InitialBlockDownload (latching to false)
btcpayserver_bitcoind | 2020-04-22 16:24:08 Imported mempool transactions from disk: 68 succeeded, 0 failed, 0 expired, 0 already there
btcpayserver_bitcoind | 2020-04-22 16:24:08 Loaded 14369 addresses from peers.dat  31ms
btcpayserver_bitcoind | 2020-04-22 16:24:08 init message: Loading banlist...
btcpayserver_bitcoind | 2020-04-22 16:24:08 init message: Starting network threads...
btcpayserver_bitcoind | 2020-04-22 16:24:08 net thread start
btcpayserver_bitcoind | 2020-04-22 16:24:08 dnsseed thread start
btcpayserver_bitcoind | 2020-04-22 16:24:08 init message: Done loading
btcpayserver_bitcoind | 2020-04-22 16:24:08 opencon thread start
btcpayserver_bitcoind | 2020-04-22 16:24:08 msghand thread start
btcpayserver_bitcoind | 2020-04-22 16:24:08 addcon thread start
nbxplorer_1  | info: Configuration:  BTC: RPC connection successfull
nbxplorer_1  | info: Configuration:  BTC: Full node version detected: 160300
nbxplorer_1  | info: Configuration:  BTC: Loading chain from cache...
nbxplorer_1  | info: Configuration:  BTC: Height: 1721332
nbxplorer_1  | info: Configuration:  BTC: Loading chain from node...
nbxplorer_1  | info: Configuration:  BTC: Height: 1721332
nbxplorer_1  | info: Explorer:       BTC: Starting scan at block 1721332
nbxplorer_1  | info: Explorer:       BTC: Handshaked node
nbxplorer_1  | info: Events:         BTC: Node state changed: NotStarted => NBXplorerSynching
nbxplorer_1  | info: Events:         BTC: Node state changed: NBXplorerSynching => Ready
btcpayserver_bitcoind | 2020-04-22 16:24:10 New outbound peer connected: version: 70015, blocks=1721333, peer=1
btcpayserver_bitcoind | 2020-04-22 16:24:10 New outbound peer connected: version: 70015, blocks=1721333, peer=3
btcpayserver_bitcoind | 2020-04-22 16:24:17 UpdateTip: new best=0000000000000071b5ba4d00b7273b6c69f95c76e8ac3f303f8f6c54e8dbcfe9 height=1721333 version=0x3fff0000 log2_work=72.41856 tx=55686539 date='2020-04-22 16:23:10' progress=1.000000 cache=0.1MiB(425txo) warning='62 of last 100 blocks have unexpected version'
nbxplorer_1  | info: Events:         BTC: New block 0000000000000071b5ba4d00b7273b6c69f95c76e8ac3f303f8f6c54e8dbcfe9
btcpayserver_bitcoind | 2020-04-22 16:24:19 P2P peers available. Skipped DNS seeding.
btcpayserver_bitcoind | 2020-04-22 16:24:19 dnsseed thread exit
btcpayserver_bitcoind | 2020-04-22 16:24:22 New outbound peer connected: version: 70015, blocks=1721333, peer=4
btcpayserver_bitcoind | 2020-04-22 16:24:23 New outbound peer connected: version: 70015, blocks=1721333, peer=5
btcpayserver_bitcoind | 2020-04-22 16:24:24 connect() to 87.246.33.148:18333 failed after select(): Connection refused (111)
btcpayserver_bitcoind | 2020-04-22 16:24:24 New outbound peer connected: version: 70015, blocks=1721333, peer=6
btcpayserver_bitcoind | 2020-04-22 16:24:25 New outbound peer connected: version: 70015, blocks=1721333, peer=7
btcpayserver_bitcoind | 2020-04-22 16:24:26 New outbound peer connected: version: 70015, blocks=1721333, peer=8
btcpayserver_bitcoind | 2020-04-22 16:24:32 connect() to 185.220.101.197:18333 failed after select(): Connection refused (111)
btcpayserver_bitcoind | 2020-04-22 16:24:33 New outbound peer connected: version: 70015, blocks=1721333, peer=9
btcpayserver_bitcoind | 2020-04-22 16:24:44 New outbound peer connected: version: 70015, blocks=1721333, peer=10
btcpayserver_bitcoind | 2020-04-22 16:24:56 New outbound peer connected: version: 70015, blocks=1721333, peer=11
btcpayserver_bitcoind | 2020-04-22 16:24:56 connect() to [2001:16b8:1e5e:be00:7576:8bd5:53ed:71fc]:18333 failed: Cannot assign requested address (99)
btcpayserver_bitcoind | 2020-04-22 16:24:57 New outbound peer connected: version: 70015, blocks=1721333, peer=12

**Comment by NicolasDorier** [comment]
```
nbxplorer_1 | info: Configuration: Network: Testnet
```

You are running nbxplorer on testnet, but giving a mainnet derivation scheme.

**Comment by WolvenSpirit** [comment]
I changed that and now it gave 200 when tracking it, thanks, also it reverted to giving me no address and shortly after 404 when requesting a new address.
`{"feature":"Deposit","derivationStrategy":"xpub688jB86MyNWph3g3ueWsqSPFRDEjK8QJD1uJ8uBQSPP7WNp5MMx92CoxDdQbTt1QbhCLbX6C8LkU6kkRfatFGVhTzcPwT8ETNPSbBUBoiJy","keyPath":"0/0","scriptPubKey":"00147ce4de5d5baa050812c8065317f0f99c9b1370de","redeem":null}`

`{"httpCode":404,"code":"strategy-not-found","message":"This strategy is not tracked, or you tried to skip too much unused addresses"}`

Yet the xpub is probably tracked, when I call transactions it still tries to return a list as show below:
`{"height":627186,"confirmedTransactions":{"knownBookmark":null,"bookmark":"0000000000000000000000000000000000000000","transactions":[]},"unconfirmedTransactions":{"knownBookmark":null,"bookmark":"0000000000000000000000000000000000000000","transactions":[]},"replacedTransactions":{"knownBookmark":null,"bookmark":"0000000000000000000000000000000000000000","transactions":[]}}`

I will try with the bitcoinpay production docker-compose without modifying it to see if it is indeed my current configuration.

**Comment by NicolasDorier** [comment]
`"knownBookmark":null,"bookmark":"0000000000000000000000000000000000000000"`

wow wait this is a VERY old version.

**Comment by NicolasDorier** [comment]
Your problem is that you are using a very very old version. Should be v2.1.24

**Comment by WolvenSpirit** [comment]
`{"trackedSource":"DERIVATIONSCHEME:xpub688jB86MyNWph3g3ueWsqSPFRDEjK8QJD1uJ8uBQSPP7WNp5MMx92CoxDdQbTt1QbhCLbX6C8LkU6kkRfatFGVhTzcPwT8ETNPSbBUBoiJy","feature":"Deposit","derivationStrategy":"xpub688jB86MyNWph3g3ueWsqSPFRDEjK8QJD1uJ8uBQSPP7WNp5MMx92CoxDdQbTt1QbhCLbX6C8LkU6kkRfatFGVhTzcPwT8ETNPSbBUBoiJy","keyPath":"0/0","scriptPubKey":"00147ce4de5d5baa050812c8065317f0f99c9b1370de","address":"bc1q0njduh2m4gzssykgqef30u8enjd3xux7pvtugv"}` 

After changing the version it works, thank you.
