### ISSUE TITLE
Create PSBT endpoint errors when estimate fee fails with fallbackFeeRate

### ISSUE THREAD

**Issue by junderw** [dgarage/NBXplorer#258]
Expected: If fallbackFeeRate is set, failing to get fee estimate should not cause 500 response.

Actual: I passed fallbackFeeRate to create PSBT endpoint, watching the NBX logs as I did. Then I got an error log for estimate fee RPC error which bubbled up to a 500 reponse. Setting explicitFeeRate solved the problem and the Psbt was created.

Coin: BCash

Daemon: Bitcoin-ABC

**Comment by junderw** [comment]
The reason why I made this issue, is that the "if error, use fallbackFeeRate" logic is in NBX...

The reason why bitcoin-abc gave an error is irrelevant, but for debugging purposes I showed it.

**Comment by NicolasDorier** [comment]
well `fallbackFeeRate` is for when the fees are not ready to be estimated because of lack of data. I would have expected bitcoin-abc to work, what is the error 500?

**Comment by junderw** [comment]
I looked into it.

Reason: estimatefee is deprecated in the latest version.

Temporary Solution: It can be re-activated with `-deprecatedrpc=estimatefee`

Permanent Solution: RPC deprecated error or RPC command does not exist error should also use fallback feerate.

**Comment by junderw** [comment]
Bitcoin-ABC has no fee estimation RPC now. The reasoning is that if fees go over 1 spb consistently they'll just hardfork bigger blocks into the protocol.

**Comment by junderw** [comment]
Actually, it is not impossible to think BTC might deprecate estimatefee or estimatesmartfee some day, so maybe also checking if the error is deprecated error or RPC does not exist error could be good?

**Comment by NicolasDorier** [comment]
Can you give me the stack trace?

**Comment by junderw** [comment]
Fixed in 9db0bea

**Comment by junderw** [comment]
Reason was bitcoin-abc deprecated, then removed the nblocks arg for estimatefee.
