### ISSUE TITLE
DerivationScheme for altcoins differs from endpoint to event contents

### ISSUE THREAD

**Issue by junderw** [dgarage/NBXplorer#259]
Expected: If I GET events and there is an event for an LTC wallet, the derivationStrategy of the event should equal the derivationStrategy I use for the API endpoints.

Actual: endpoints for LTC use Ltub, but events for cryptoCode LTC newtransaction gives derivationStrategy with xpub instead of Ltub.

Note: event data has cryptoCode string, so it is aware of which ALT it is for, so it should convert back to Ltub for the event.

**Comment by NicolasDorier** [comment]
The won't be fixed, too much refactoring just to handle a single shitcoin case.

XPub is the official way or representing xpub in litecoin (see https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp)

**Comment by junderw** [comment]
Note: only Litecoin switches. All other altcoins only have one possible version for extended pubkeys.
