### ISSUE TITLE
Different blockchain

### ISSUE THREAD

**Issue by PiotrFerenc** [dgarage/NBXplorer#26]
i created own (local) implementation of altcoin (https://www.youtube.com/watch?v=mDGxGYvkDEE). After `./run.sh` a had error. Plz help me :)

`fail: Configuration:  The RPC Server is on a different blockchain than the one configured for tumbling`

**Comment by NicolasDorier** [comment]
Only BTC and LTC are supported for now. You need to figure out how to add support for your coin to NBXplorer by yourself.

**Comment by NicolasDorier** [comment]
I detailed the steps to take here https://github.com/dgarage/NBXplorer/#how-to-add-support-to-my-altcoin
