### ISSUE TITLE
Lightning Network support?

### ISSUE THREAD

**Issue by joemphilips** [dgarage/NBXplorer#267]
Hi.

I've been trying to build LN daemon by wrapping a rust-lightning in
https://github.com/joemphilips/NRustLightning

In there, i was using NBXplorer for tracking on-chain funds,
and I was also imitating many parts of NBXplorer implementation (e.g. I defined `NRustLightningNetwork` in the same way with `NBXplorerNetwork` )

Gradually there were many code duplication in between NRustLightning and NBXplorer, I realized that it will be much simpler if NBXplorer was the Lightning Network daemon in the first place.

So my question is
1. Is it acceptable if I create a PR to this repository in which uses rust-lightning inside so that the NBXplorer can work as a watchtower?
2. If so, Is it ok to keep FFI code as a separate project? Or should I also included into this repository?

**Comment by joemphilips** [comment]
It can also be full lightning network daemon rather than supporting only watchtower (in fact, I think that is more natual. since the spec for a watchtower is not fixed yet.)
In that case We have to delegate signing funding transaction to something else which has hot wallet feature (probably by telling it to sign through websocket).

**Comment by NicolasDorier** [comment]
@joemphilips why not just having RustLightning acts as a client of NBxplorer?

**Comment by joemphilips** [comment]
What do you mean?
I've been building it as an Independent server (which acts as a client of NBXplorer) as I mentioned above, and that is certainly possible.

Are you asking why shouldn't we keep it separated that way?
Well, it is just an idea,  and I honestly don't know which is better.

* Pro: It might be easier for users of NBXplorer (like us) to adapt LN.
* Con: There might be a dependency to my [own library](https://github.com/joemphilips/DotNetLightning) Which is prabably  unacceptable for a security reason. otherwise incorporating everything into this repository will bloat code.

ping @junderw any opinion?

**Comment by junderw** [comment]
create RustLightning (Server) and RustLightningClient (for controlling the server)

The RustLightning should take an instance of NBXplorerClient as a construction parameter.

Then later on if NBXplorer wants they could add support for setting up a RustLightning instance, passing it a Client of itself into it, then using RustLightningClient to control it.

@NicolasDorier You can finally get away from golang! :-DDDD

**Comment by NicolasDorier** [comment]
@joemphilips NBXplorer is focused on a single purpose: UTXO tracking for on chain payment.

I find it weird to have something related to lightning in this repo, and on top of it, in another language.

I also don't understand how that make things easier for you. Why are you duplicating things from NBXplorer into NRustLightning? Is the problem just that NBXplorer is missing some routes that I should expose? Or something I need to add to allow watchtower use case? (I did the track scriptPubKey for second layer need, but maybe need something else?)

btw, unrelated but why don't you use NBitcoin.Secp256k1 to escape hell of native bindings?

**Comment by joemphilips** [comment]
>  NBXplorer is focused on a single purpose: UTXO tracking for on chain payment.

> I find it weird to have something related to lightning in this repo, and on top of it, in another language.

Then it's fine. Yeah that makes since. I just thought you might be interested.

>  Is the problem just that NBXplorer is missing some routes that I should expose? Or something I need to add to allow watchtower use case?

Nothing particular so far. I will make a PR if I find it.

There were so many times I bumped into a issue while coding and ended up finding out that the issue was already solved in NBXplorer.
(e.g. "How should I get the repository by cryptoCode at runtime? .... Oh that is already done in NBX so I should just copy it")

> btw, unrelated but why don't you use NBitcoin.Secp256k1 to escape hell of native bindings?

I'm waiting for you to publish new version after [my PR](https://github.com/MetacoSA/NBitcoin/pull/860) (I did not mention because I had other works to do and I didn't want to push you.)

**Comment by NicolasDorier** [comment]
I just pushed a new version.

**Comment by joemphilips** [comment]
@NicolasDorier  Would you mind pushing a new version for NBitcoin itself? The change I have mentioned above is for NBitcoin.

**Comment by NicolasDorier** [comment]
done

**Comment by NicolasDorier** [comment]
.41

**Comment by veektorh** [comment]
Can we use NbXplorer to build for lightning?

**Comment by joemphilips** [comment]
@veektorh No. You might want to check out my works
* https://github.com/joemphilips/NRustLightning
* https://github.com/joemphilips/DotNetLightning

Which is still in its early stage though.

**Comment by NicolasDorier** [comment]
@veektorh and if you search a client API to lightning implementation https://github.com/btcpayserver/btcpayserver.lightning
