### ISSUE TITLE
Repository ping exceeded 30 seconds ([values > 30])

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#272]
Getting warnings time to time as 
`warn: Explorer:       Repository ping exceeded 30 seconds (100), please report the issue to NBXplorer developers`

It looks like this doesn't affect NBX instance but since it says 'please report the issue' it is better to have an issue for this.

Setup details;
One NBX instance is running for btc/ltc/dash.
RabbitMq publishing is active.

**Comment by NicolasDorier** [comment]
do you have lot's of transactions? How many ?

**Comment by farukterzioglu** [comment]
Total transactions from 3 chains: 18380

Coin A P2SH
UTXO - 317
Tx - 8800

Coin A Segwit
UTXO - 52
Tx - 2900


Coin B P2SH 
UTXO - 310
Tx - 3400

Coin B Segwit
UTXO - 80
Tx - 2400


Coin C Legacy - 173
Tx - 880

is this too many?

**Comment by NicolasDorier** [comment]
no, seems not too bad. What type of hard drive you have? Windows or linux?

**Comment by farukterzioglu** [comment]
it is non-ssd on linux server.

as an additional note, most of the times, getting utxo takes around 2 minutes.

**Comment by NicolasDorier** [comment]
You probably should use an SSD, there is a huge amount of request going to the database.

**Comment by farukterzioglu** [comment]
we expect these numbers to increase 5 times of the current one,
probably 5 times more than todays deposit/withdrawal counts.

with an ssd, do you think one nbx instance can handle this payload.

**Comment by NicolasDorier** [comment]
Should be ok. The current problem is not caused by the number of transaction count, but by the sheer number of request for every transactions coming in from bitcoin network (probably around 50 disk search per second, not counting what you may have with bitcoin core itself)
Don't use non-ssd.

**Comment by farukterzioglu** [comment]
Just checked with our devops and saw that we are using Azure standart ssd.

Do you think this is not enough too?
May the current latency of getUtxo (~2min) and warnings regarding to repository ping seconds
be because of disk IO performance?

**Comment by NicolasDorier** [comment]
@farukterzioglu can your devops check if there is no CPU issue? If not, then the problem is with the IO. I know Azure perf is shit specially if the drive is not the main one and an attached one.

You can confirm also by yourself by running NBXPlorer queries locally on your own laptop.
2min is huge for this number of UTXO, it should take less than 10s.

**Comment by farukterzioglu** [comment]
I tested on a new machine;
Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
4 cpu
8 GB ram 
Azure standart ssd (NBX directory is on OS disk)
bitcoin core on different machine

I run nbx only with BTC with existing data (BTC+LTC+DASH)

Query results are like;
P2SH
512 utxo (53 seconds) (sent the same request multiple times, all are ~53s )
9800 transactions (80 seconds)
SEGWIT
54 utxo (15 seconds)
3000 (30 seconds)

130K reserved addresses

No other query sent to this nbx, other than these;
/derivations/{{btc-strategy}}/utxos
/derivations/{{btc-strategy}}/transactions

I watched both cpu and ram while waiting for responses, both of them are below %25 usage.

response times still don't look like ok.

**Comment by NicolasDorier** [comment]
The time it takes is linear to the number of transactions.
80 seconds for 9800 transaction is way more than I would expect.

Are you using a recent build? I made parsing improvement with NBitcoin like a month ago.

For CPU 25%, this mean a core is fully used which mean it is likely the bottleneck. If you are using Azure, make sure your CPU is not being throttled. (some azure machine plans, while being cheap, are adapted for now CPU usage and only allow short burst of CPU but not continuous use)

You could use manual pruning, this will remove transactions from your history that do not impact the UTXO set anymore.

**Comment by NicolasDorier** [comment]
@farukterzioglu I will probably soon work on an "high RAM" parameter where NBX will cache a lot in RAM to make big wallet operations way faster.

**Comment by farukterzioglu** [comment]
It will be awesome since I am out of option. 

I have the latest commit and done a pruning at the weekend, but this is the result as best as I can;
For Btc P2SH, pruned over than 4K tx.

![image](https://user-images.githubusercontent.com/476514/85995392-d8515380-ba06-11ea-8564-b4e50269afff.png)

**Comment by farukterzioglu** [comment]
> @farukterzioglu I will probably soon work on an "high RAM" parameter where NBX will cache a lot in RAM to make big wallet operations way faster.

If this not a big deal, I would like to help. if it is doable my some one other than you

**Comment by NicolasDorier** [comment]
your number of UTXO is so small, it should not even be slow.

You can try on your own computer, you will see the response time is less than 10ms. Azure is shit.

**Comment by farukterzioglu** [comment]
I tested with 3 different machines, with and without node connection (syncing or not), and with multiple queries in a minute or a single query

I run this query at all of them (from terminal, to eleminate network issues)
`curl -s 'http://0.0.0.0:24446/v1/cryptos/btc/derivations/2-of-xpub...-[p2sh]/utxos'`

Results are as;

---
On my personel computer (MacOS, w/o node connection, no other query is coming)
Avarage : ~12s

---
VM-1 on Azure (Linux, no other query is coming)

(w/o node connection)
Avarage : ~45s

(w/ node connection, syncing w/ Btc/Ltc/Dash)
Avarage : ~50s

---
VM-2 on Azure (Linux, w/ node connection, syncing w/ Btc/Ltc/Dash, taking ~5 query in a minute)
Avarage : ~89s

___ 
All results;

Personel computer (MacOS)
 time_total:  12.947342s
 time_total:  13.189505s
 time_total:  12.055307s
 time_total:  12.208902s
 time_total:  12.732179s


VM-1 w/o node connection, no other query is coming
 time_total:  45.550659s
 time_total:  45.478183s
 time_total:  45.549801s
 time_total:  45.743368s
 time_total:  45.040315s

VM-1 w/ node connection, no other query is coming
 time_total:  52.192855s
 time_total:  52.221212s
 time_total:  52.722300s
 time_total:  45.392379s
 time_total:  51.771739s


VM-2 w/ node connection, taking ~5 query in a minute
 time_total:  94.633851s
 time_total:  103.767806s
 time_total:  85.571161s
 time_total:  82.053317s
 time_total:  84.178812s

**Comment by farukterzioglu** [comment]
With the result above, Azure is 3 times slower than personel computer, and under load (I mean 4-5 query in a minute) it becomes 6 times slower. 

How do you suggest me to proceed, is there a machine spec I can take as a reference, or some specific machine features I need to give more attention.

**Comment by NicolasDorier** [comment]
Thanks.
@farukterzioglu can you try `/balance`. At least it take out the cost of serializing/deserializing on client side.
This time it takes is proportional to the number of transactions.

The problem will be probably completely solved when I store everything in RAM. Though it will take more RAM (which I don't expect to be a problem if you have more than 2GB)

**Comment by NicolasDorier** [comment]
I am rewriting the database engine (DBreeze), as the code is really bad.
I am confident to solve completely this problem, but this will take maybe 1 or 2 weeks.

**Comment by farukterzioglu** [comment]
Good to hear that, 
If you need help and if there is anything I can do, would like to help.

**Comment by NicolasDorier** [comment]
@junderw @joemphilips btw by rewritting DBReeze, I found out the underlying reason of huge file handle opening.

It is because every single transaction I save in the DB, create one file...
I will fix that as well.

**Comment by NicolasDorier** [comment]
I rewrote DBriize, I need additional testing and porting to NBXplorer.

I go down from 2 second to 200 ms for query of 4000 transactions on my machine.
