### ISSUE TITLE
Stuck on "Loading chain..."

### ISSUE THREAD

**Issue by Dinglebarry9** [dgarage/NBXplorer#273]
NBXplorer is stuck on "Loading Chain..."

**Comment by Dinglebarry9** [comment]
Fixed: Had wrong Genesis block set.

Note: when using Liquid regtest make sure to set your own genesis block as every Elements Regtest chain has a different block

**Comment by NicolasDorier** [comment]
For our tests we use very specific settings for Elements, we don't allow people to use their own.

**Comment by NicolasDorier** [comment]
initialfreecoins=210000000000000\nvalidatepegin=0
