### ISSUE TITLE
Setting up a new clean NBXplorer with existing data

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#274]
I am looking for an appropriate way to setup a clean NBXplorer setup. 
Current one has lots of small transactions which we can't spend, lower than our business minimum. Spending these even for once currently not possible.
And at the first run, we didn't set minutxovalue and now 2/3 of utxos are never being spent (so their transactions can't be pruned.)

And I suspect we may have some missed transactions when we got exception as
`Current Index Progress not found, start syncing from the header's chain tip `
and I can't rescan as before as I want to be confident, because it takes too much time and requests to NBX while it rescanning being timed out. 

Is it enough to install a clean NBX, track all derivation schemes and rescan as before as I wish?
How about addresses generated with previous one? (some of them received tx, some of them never used before)

Should I generate the addresses which generated before, again with the newly setup NBX, without storing them on my db (since I already saved them)?

What else will be required to align with the existing one?

**Comment by NicolasDorier** [comment]
@farukterzioglu you can certainly start a new NBX, use scanutxoset, but this is not available in all shitcoins, so you need to test. Also, it may not work on non segwit address.

You can manually import transactions in NBX manually via some calls in the doc (check it out).
So you can do a script that take data out of your current NBX, and put it in the new NBX.

**Comment by farukterzioglu** [comment]
I have both segwit and p2sh schemes for btc/ltc, and legacy for dash.
isn't it enough to rescan these coins, or do I need to use scanutxoset.

I can import txs manually too, but rescanning will populate them, correct?

how about addresses already generated with nbx, how can I align them?

**Comment by NicolasDorier** [comment]
@farukterzioglu if you rescan, used address will not be reused.

**Comment by farukterzioglu** [comment]
In my application, when available address count gets lower than 1000, I generate 5000 more addresses (with reserve=true) and save them to my db. 

In NBX, If I set `mingapsize=1000` and `maxgapsize=5000` and rescan from my very first BTC transaction's block number, I guess I can populate the same data. 

Am I right? I don't want to miss something important.

**Comment by NicolasDorier** [comment]
Yes you are right. It is just it will take long time. NBXplorer is not optimized to rescan lot's of blocks.

**Comment by farukterzioglu** [comment]
Closing this because it is not required for me any more.
