### ISSUE TITLE
Unknown exception when broadcasting e7b... (bad-txns-inputs-missingorspent)

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#275]
Gettling lots of error as 
`Unknown exception when broadcasting e7b... (bad-txns-inputs-missingorspent)`

Some of them successfully sent on network (I can see from block explorer) but some of them rejected with message 
`Transaction invalid: some outputs that it attempts to spend have been already spent or are no longer valid.`

What is the reason for these and how can I get rid of them?

**Comment by NicolasDorier** [comment]
Have you updated to last version? This is not really problematic. This happen because NBXplorer is rebroadcasting automatically the transactions. If the transaction has been confirmed, it can get this "error" message. (I should be smarter about showing the error though)

The reason might also be a double spend attempt though.

**Comment by NicolasDorier** [comment]
Other question: `bad-txns-inputs-missingorspent` which crypto currency does it come from? this is not bitcoin.

**Comment by NicolasDorier** [comment]
seems to be bcash...

**Comment by NicolasDorier** [comment]
Sorry, this error came from a renamed error message from bcash, just fixed.

**Comment by farukterzioglu** [comment]
They are all from btc, I don't have bcash in my nbx. 
If they are not problematic, I can ignore the error logs. 
I suspected my transactions are being rejected because of using spent outputs. (and possible data corruption)

I may be behind 1-2 commit, will update and try again

Thanks a lot.

![image](https://user-images.githubusercontent.com/476514/85371635-40042c00-b539-11ea-96b0-2c23fcb13d93.png)

**Comment by NicolasDorier** [comment]
it was 1-2 commit ago. Did it fixed the issue?

**Comment by farukterzioglu** [comment]
Yes, thanks. After I updated I didn't see these messages again.
