### ISSUE TITLE
The RPC interface is currently not available

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#276]
Rpc connection is being disconnected very often with message `Block download seems to hang, let's reconnect to this node` and node state is being changed to `NotStarted`

This causes exception while I query NBX; `The RPC interface is currently not available`
I needed to check if rpc is available or not, every time I query nbx endpoints (like getUtxo, broadcastTransaction)

This occurs time to time;
![image](https://user-images.githubusercontent.com/476514/85333351-1bc93080-b4e2-11ea-9cc4-e5a40a236f80.png)

What can I do to eliminate these issues? May this be related to network issues?

Setup details;
One NBX instance with btc/ltc/dash, every nodes on different machines.

**Comment by NicolasDorier** [comment]
I  never had such issue. Does your nodes whitelist nbxplorer?

**Comment by farukterzioglu** [comment]
Yes, all of them is whitelisted. Generally it works, and logs say that "NBXplorer is correctly whitelisted"

This happens 5-6 times in an hour.

**Comment by farukterzioglu** [comment]
@NicolasDorier  You said that in another issue 
`My personal experience on running bitcoin node in azure has been that it was working only fine if I was using the OS drive, but on attached drive it was unusable.`

All of my nodes' data on attached drive, do you think this can cause rpc connection problems? When I check all nodes, I don't see a problem.

**Comment by NicolasDorier** [comment]
I don't know. This error is clearly a connection issue between NBX and nodes.

**Comment by farukterzioglu** [comment]
Haven't got this exception for a while, closing this.
