### ISSUE TITLE
BTC: Unhandled in Wiater Loop Error

### ISSUE THREAD

**Issue by rony4d** [dgarage/NBXplorer#278]
I restarted my server where my bitcoin and litecoin node runs. I tried to run bitcoin node again and started getting this error
https://imgur.com/a/ujugl4x

Litecoin node runs perfectly but bitcoin keeps failing. Please help.

**Comment by NicolasDorier** [comment]
Your bitcoin node seems down try `btcpay-up.sh` or `btcpay-restart.sh` if that does not work, check the logs of bitcoind with `docker logs`

**Comment by rony4d** [comment]
I am running a windows server.  Where can I find the btcpay-up.sh or btcpay-restart.sh. My bitcoind is showing a warning "62 of last 100 blocks have unexpected version' but the block height is not up to the current block height on the bitcoin blockchain.

**Comment by rony4d** [comment]
I have been able to resolve it. So what I did was to run the bitcoin core GUI version and it synced all the blocks. I turned it off and ran bitcoind. I now ran NBXplorer and like magic it started working. 
So I guess my blocks were not fully synced and hence bitcoind was not working properly for NBXplorer to connect.

**Comment by NicolasDorier** [comment]
if you were running bitcoin core gui, it is because you did not used `server=1`. In the GUI, by default RPC is off
