### ISSUE TITLE
INVALID CHAINS LTC, BTC

### ISSUE THREAD

**Issue by rony4d** [dgarage/NBXplorer#279]
I have Bitcoin and Litecoin Node running on a windows server. I can connect to both individually and it works fine on mainnet but when I try to connect both with command .\run.ps1 --chains=ltc,btc --network=mainnet --noauth
it returns error INVALID CHAINS LTC, BTC. 
I have been with this error for over 1 month.

**Comment by NicolasDorier** [comment]
It is because powershell is interpreting your string.

run 

```ps1
.\run.ps1 --chains="ltc,btc" --network=mainnet --noauth
```

**Comment by rony4d** [comment]
You are a genius. You have very good eyes. I can't believe I did not spot that. Thank you
