### ISSUE TITLE
Cannot Generate Hardened Addresses e.g Segwit (m/84'/0'/0'/0/0)

### ISSUE THREAD

**Issue by veektorh** [dgarage/NBXplorer#280]
Currently using nbxplorer to generate non harderned address for derivation scheme (xpub1) with KeyPath($"0/0")

But what im not able to do is  generate and track **Hardened** address that belongs to this format (m/84'/0'/0'/0/0).

trying to this with nbitcoin, it throws an error that says you cant derive **Hardened** child from **ExtPubKey**.

is there a way to pass the private key to nbxplorer in order for it go generate the hardened child or is there any other way. that can help me acheive this.

ill like to generate addresses in this format since thats the standard used in modern wallets ( Trust wallet, exodus etc)

**Comment by NicolasDorier** [comment]
Standard wallet are deriving `m/84'/0'/0'/0/0`.

If you want to track such wallet, you need to track the **account** xpub (path `m/84'/0'/0'`).

**Comment by veektorh** [comment]
trying to that throws an error  - A public key can't derivate an hardened child

`xPub.Derive(new KeyPath("m/84'/0'/0'"))`

**Comment by NicolasDorier** [comment]
you need private key to derive up to m/84'/0'/0'

**Comment by veektorh** [comment]
i have the private key and i can derive the xpriv of m/84'/0'0' , but i cant get  nbxplorer to track it?

i tried passing the xprive but it returns errror Invalid derivation scheme.

**Comment by NicolasDorier** [comment]
```csharp
var xpub = xpriv.Derive(new KeyPath("m/84'/0'0'")).Neuter();
// Use xpub in nbxplorer.Track
```

**Comment by veektorh** [comment]
Thanks , its working as expected

**Comment by veektorh** [comment]
can you help me out with this other issue. im trying to spend from a p2sh address

One or more errors occurred. 
(You need to provide P2WSH or P2SH redeem script with Coin.ToScriptCoin())




`            fromAdd = BitcoinAddress.Create(add1, network);
            var sender =  PayToScriptHashTemplate.Instance.GenerateScriptPubKey(fromAdd.ScriptPubKey);
            
            var init = network.CreateTransaction();
            init.Outputs.Add(Money.Coins(0.002m), sender.Hash);
            var coins = init.Outputs.AsCoins().ToArray();
            var scriptcoin = coins[0].ToScriptCoin(sender);

            builder.AddCoins(scriptcoin);
            builder.AddKeys(secret.PrivateKey);
            builder.Send(dest, amount);
            builder.SetChange(fromAdd);
            builder.SendEstimatedFees(new FeeRate(1m));
            var res = builder.BuildTransaction(true);
`

**Comment by NicolasDorier** [comment]
See the code here for an example of how to spend:

https://github.com/dgarage/NBXplorer/blob/master/NBXplorer.Tests/UnitTest1.cs#L284

`tester.Client` represent the NBXplorer client (`ExplorerClient`) from the client library.
