### ISSUE TITLE
Tracking testnet segwit addresses

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dgarage/NBXplorer#283]
Given the BIP39 Mnemonic : `august panther shoulder illness mansion lonely tank soon quick hollow you omit short cheese region`, produced the Account Extended Public Key `vpub5YF85yw97PhKvNt5LPL8c5b26Rdy7HippNa4fUKEADPJmDW6oJXSxsRwzJAijgKLv3mzk9PcF7ThLLdbXC1n4tUPHJDEVyEqGNs2H8KQKH6` on Testnet3,

That yields a BIP84 address `m/84'/1'/0'/0/0` : `tb1q6m6809peu64ujaz0ezjvf6k6ucufqtqqs036vf`

Should I be able to track it with the API call?

`https://mynode/v1/cryptos/BTC/derivations/vpub5YF85yw97PhKvNt5LPL8c5b26Rdy7HippNa4fUKEADPJmDW6oJXSxsRwzJAijgKLv3mzk9PcF7ThLLdbXC1n4tUPHJDEVyEqGNs2H8KQKH6-[p2sh]`

**Comment by NicolasDorier** [comment]
if you add `-[p2sh]` it will be not be segwit, you need to remove it.

**Comment by bitcoinbrisbane** [comment]
> if you add `-[p2sh]` it will be not be segwit, you need to remove it.

Dam, I meant `-[P2WPKH]`

**Comment by NicolasDorier** [comment]
this is P2WPKH if you don't specify -[blah]

**Comment by bitcoinbrisbane** [comment]
> this is P2WPKH if you don't specify -[blah]

Thanks for the fast reply.  But on a testnet setup, I get

```json
{
    "httpCode": 400,
    "code": "invalid-format",
    "message": "Invalid derivation scheme"
}
```

**Comment by NicolasDorier** [comment]
`vpub5YF85yw97PhKvNt5LPL8c5b26Rdy7HippNa4fUKEADPJmDW6oJXSxsRwzJAijgKLv3mzk9PcF7ThLLdbXC1n4tUPHJDEVyEqGNs2H8KQKH6` should be `tpub`

**Comment by bitcoinbrisbane** [comment]
> `vpub5YF85yw97PhKvNt5LPL8c5b26Rdy7HippNa4fUKEADPJmDW6oJXSxsRwzJAijgKLv3mzk9PcF7ThLLdbXC1n4tUPHJDEVyEqGNs2H8KQKH6` should be `tpub`.
> NBitcoin do not recognize the other way of presenting an xpub.

Even on testnet? I was using https://iancoleman.io/bip39 to generate.

**Comment by NicolasDorier** [comment]
xpub on testnet are tpub

**Comment by bitcoinbrisbane** [comment]
> xpub on testnet are tpub

Yeah I know, the Ian Coleman site said otherwise. Thanks for your help once again.
