### ISSUE TITLE
NBXplorer.Client: Make NBXplorerNetworkProvider.Add() public?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#29]
Trying to add support to BCH in `NBXplorer.Client`. 
Currently the `NBXplorerNetworkProvider` only has `GetBTC()` and `GetLTC()`. 
How can I add my own `NBXplorerNetwork`? (which I already implemented in a similar way like `NBXplorer.Altcoins.Litecoin`)

I think if the `Add()` was public it would be easier. also the `NBXplorerNetwork.MinRPCVersion`  and `DerivationStrategyFactory` could be public `set` not `internal` so we could do something similar to `InitLitecoin()`.

The `NBXplorer.Client` is used in our client service. 

For the NBXplorer **server** I use my own build to support only BCH. 

What do you think?
Thanks

**Comment by NicolasDorier** [comment]
why making it public ? adding Litecoin did not required it to be public.

**Comment by bazooka70** [comment]
So now I will need to use the compiled NBXplorer.Client.dll instead of the nuget I use?

**Comment by NicolasDorier** [comment]
what? no, you add BCH support as I did for LTC, then you submit pull request so I merge your code in the repo.

**Comment by bazooka70** [comment]
> what? no
LOL, I told you I'm totally lost with the GitHub stuff. I still need to test it more thoroughly  though. 
I will try to make a PR. although I never managed to...

I run it like:
`dotnet run --no-build -c Release -- --network=testnet --datadir="D:\Projects\NBXplorer-BCH\DataDir" --chains=bch`

At this point, the NBXplorer server connects to the the Bitcoin ABC Node, and gets new blocks just fine.
Now I wanted to test the client side. using `client.Track()`, making transactions, and getting notifications from the server. for now I will use the compiled dll, to test the client.
