### ISSUE TITLE
Unable to estimate fee

### ISSUE THREAD

**Issue by rony4d** [dgarage/NBXplorer#293]
I just started getting this error when trying to estimate fees from my bitcoin node connection in my windows server. I checked my second bitcoin node which is running on a different windows server and the fee estimation API works. 

**Request**: : http://127.0.0.1:24444/v1/cryptos/btc/fees/2

**Response**: 
{
"httpCode": 400,
"code": "fee-estimation-unavailable",
"message": "It is currently impossible to estimate fees, please try again later."
}

**Comment by rony4d** [comment]
I started rescanning the bitcoin blockchain from an old block and it started working. I really don't understand why it stopping working at first.

**Comment by NicolasDorier** [comment]
because fee estimation always take time to be available for new nodes.
