### ISSUE TITLE
Enable custom auth so BTCPayServer can reach NBX behind a reverse-proxy

### ISSUE THREAD

**Issue by Dinglebarry9** [dgarage/NBXplorer#296]
If this is a dumb question I apologize, but I see the custom auth from @KeyFiDennis got merged but how do you enable it for both NBX and BTCPay to allow BTCPay to reach NBX behind a reverse-proxy?

**Comment by NicolasDorier** [comment]
sorry I can't hand hold you on that, there is nothing specific to nbxplorer.

**Comment by Dinglebarry9** [comment]
No worries thanks, you're the man
