### ISSUE TITLE
Websocket connection doesn't work

### ISSUE THREAD

**Issue by CamposBruno** [dgarage/NBXplorer#298]
Hi everyone,

I'm having troubles trying to connect to the notification websocket. The documentantion over this topic is not clear, so I wonder if anyone have an example on how to connect and if any extra steps is needed to make it work.

I'm using nodejs and tried to do the following but I always get a `connection failed` as a result:

```
import * as Websocket from 'websocket';

const websocket =  new Websocket.w3cwebsocket(`ws://{NBXPLORER_HOST}/v1/cryptos/btc/connect`);
websocket.onopen = (event: Event) => console.log;
websocket.onclose = (event: CloseEvent) => console.log;
websocket.onmessage = (event: MessageEvent) => console.log;
websocket.onerror = (event: Event) => console.error;
```

Anyone?

**Comment by NicolasDorier** [comment]
are you sure the problem is websockets? `connection failed` seems like there is a firewall, or NBX is just listening on 127.0.0.1 instead of 0.0.0.0

**Comment by CamposBruno** [comment]
I think the problem is in authentication. 
I'm getting the following error now : `HTTP Authentication failed; no valid credentials available`.

Is there a right way to pass user and password to the websocket connection? Is this the same credentials in the .cookie file ?

**Comment by CamposBruno** [comment]
I was able to make this work using authentication credentials as following:

```
const websocket =  new WebSocket('ws://{NBXPLORER_HOST}/v1/cryptos/btc/connect', {
  auth:
    '__cookie__:9d8faf2a056cca2...',
});
```
