### ISSUE TITLE
Using the Explorer

### ISSUE THREAD

**Issue by aboimpinto** [dgarage/NBXplorer#306]
I'm trying to learn how to sync the Bitcoin network with C# and I found this project.
when I try to run this on my Linux I get this error

![image](https://user-images.githubusercontent.com/1231687/107889653-72252c80-6f14-11eb-8375-d963fb56655d.png)

and no sincronizaço is done ... What am I doing wrong?

**Comment by NicolasDorier** [comment]
you need to run bitcoin core,

**Comment by Spixmaster** [comment]
I packaged btcpayserver which uses nbxplorer for the AUR. Here are the instructions on how to set up btcpayserver. It includes the installation of nbxplorer: https://aur.archlinux.org/cgit/aur.git/tree/README.md?h=btcpayserver-git

**Comment by aboimpinto** [comment]
> you need to run bitcoin core,

where is this app?

**Comment by Spixmaster** [comment]
@aboimpinto Are you on GNU/Linux? The software is usually called `bitcoin-daemon` and should be in all repositories.

**Comment by aboimpinto** [comment]
> @aboimpinto Are you on GNU/Linux? The software is usually called `bitcoin-daemon` and should be in all repositories. I have no idea how it works for Windows.

Yes .. I'm on Linux and I would like to learn about the BTC network and sync the blockchain with software I develop (for fun and learning). 
I thought this software does that but looks like pick the sync information and organize, right?

**Comment by Spixmaster** [comment]
From my what I know, nbxplorer offers an HTTP service for inspecting different blockchains. I cannot help you with your problems except of the installation for which I wrote instructions at the link sent earlier.

**Comment by NicolasDorier** [comment]
thhe error is clear, it can't connect with RPC. There is many reason. If you run `bitcoind` without any argument, by default, NBX should be able to connect. And I say `bitcoind`, not `bitcoin-qt`. If that does not work, I don't know.
