### ISSUE TITLE
Support for receiving on Taproot

### ISSUE THREAD

**Issue by NicolasDorier** [dgarage/NBXplorer#325]
Currently NBXplorer can doesn't allow the creation of a wallet on taproot. (or if it allows, it won't work correctly)

Sadly, to support it ,we need a refactoring of NBXplorer that will also require a migration step for existing installs, (though we can tackle in two different PRs)

The `GetMatches` methods, which scan a bunch of transactions for transactions that interest us is doing a hack which was supported to save a database query: From the scriptSig of a transaction input, we attempt to "guess" the scriptPubKey, then we query on that.

The problem is that it is impossible to do this with taproot, since the scriptSig does contain only a signature of 64 bytes.

Instead, what should be done, is to not only save the mapping `scriptPubKey -> KeyInformation` (as we do now), but also an additional mapping `outpoint -> KeyInformation`.

In the first PR, the GetMatches should still attempt to guess the scriptSig, even if it also query on the outpoint. The reason is that existing deployment would not work properly if we stopped doing this (we would miss some spending). The downside is increased pressure on the DB queries.

In a second PR, we can attempt to make a migration where we build the index `outpoint -> KeyInformation` from the information we already saved in DB.

**Comment by sageprogrammer** [comment]
I would like to work in this.

**Comment by sageprogrammer** [comment]
Here is a draft PR #327 for first part.

**Comment by sageprogrammer** [comment]
Could you see this Draft PR #328

**Comment by sageprogrammer** [comment]
Could you see this Draft PR #329
