### ISSUE TITLE
Get a new unused address Best Practice ?

### ISSUE THREAD

**Issue by Bit-Shifts** [dgarage/NBXplorer#326]
NBXplorer is NOT suppose to be directly exposed to the web. 

What is the best practice for getting an unused address to an end user?

Having your publicly exposed API call the NBXplorer unused address endpoint ? 

This would potentially mean your NBXplorer service would be exposed to the web indirectly.

**Comment by NicolasDorier** [comment]
You can do your own service on top of NBXplorer which expose this and properly control access.

You can also use BTCPay, which does essentially this.
Store Wallet (On Chain)
https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Store-Wallet-(On-Chain)

**Comment by Bit-Shifts** [comment]
Yes, I was thinking of something a little more custom so I think building my own service overtop and exposing that will be best.

Thank you!
