### ISSUE TITLE
Ability to control the "New Transaction" termination trigger by confirmation numbers for Message Brokers 

### ISSUE THREAD

**Issue by Bit-Shifts** [dgarage/NBXplorer#331]
It appears the new transactions messages stop after 1 confirmation of said transaction. 

Is there a way to set the watch duration of a transaction by how many confirmations it has ?

**Comment by NicolasDorier** [comment]
no. But there is notification about new blocks.

**Comment by Bit-Shifts** [comment]
Ok , I just thought there could be a more elegant solution to tracking a transaction to lets say 3 confirmations. 

Having the reorg risk with orphaned blocks/transactions I would like to wait until 2 confirmations. 

essentially I will have to use the "New Transaction" message to track transaction confirmations up until 1 and after that I will have to call v1/cryptos/{cryptoCode}/transactions/{txId} to get the updated confirmations every time I get a new New Block notification.

**Comment by NicolasDorier** [comment]
How many block to wait is very dependent on your specific business/risk aversion/coin you are using.

I advise you to use a higher level API for this kind of thing such as BTCPayServer.

https://docs.btcpayserver.org/API/Greenfield/v1/

**Comment by Bit-Shifts** [comment]
You are correct that there is no way to pick a good choice suitable for everybody, that's why it would be a be to have that configurable within NBXplorer.

What is the main limitation that is holding NBXplorer back from having this configurable ? I would be more then happy to submit a pull request with that added feature.

**Comment by NicolasDorier** [comment]
@Bit-Shifts because it is trivial to implement for the client as you have the block confirmations.

If you start having logic about when to consider a payment settled, I think NBX is not the right abstraction layer and BTCPay is a better one.

And I don't really know how to implement that given NBX design, but you can try.
