### ISSUE TITLE
Create PSBT with or without rebaseKeyPath

### ISSUE THREAD

**Issue by Bit-Shifts** [dgarage/NBXplorer#341]
What is happening when you rebase the KeyPath of your wallet when you are creating a PSBT ?

What are the Pro's and Con's of during this ?

**Comment by NicolasDorier** [comment]
@Bit-Shifts you can read explanation here: https://github.com/dgarage/NBXplorer/blob/master/Examples/MultiSig/Program.cs#L151

In a nutshell, NBXplorer normally only know the path relative to the account xpub to the address (say `0/1`), but a wallet, to be able to sign, also need the path to the xpub (for example `49'/0'/0'`).

Rebasing means converting relative path `0/1` to the full path `49'/0'/0'/0/1` so the signer, who only know the root private key can sign.

**Comment by Bit-Shifts** [comment]
Ah ok thank you for this easy to understand explanation. I was thinking it was more complicated then just this.
