### ISSUE TITLE
I dont get any transactions for address (testnet)

### ISSUE THREAD

**Issue by goors** [dgarage/NBXplorer#355]
Hi,

I apologise if this is answered already (i did try to search in issues).
I call endpoint to get address information  `v1/cryptos/btc/addresses/{someTestAddressHere}/transactions`, but all i got is empty response.

```{"height":2159155,"confirmedTransactions":{"transactions":[]},"unconfirmedTransactions":{"transactions":[]},"immatureTransactions":{"transactions":[]},"replacedTransactions":{"transactions":[]}}```

This can not be since this is test address that I am using for months.
Btc core is synced and point to test net.
NBXplorer is runing with `./run.sh --chains=btc --network=testnet`

When i do `./bitcoin-cli getaddressinfo someTestAddressHere` i do get response.

Does it take some time to get information for this or I am doing something horrible wrong?

UPDATE

I did  call track endpoint with the address first ass specified in your api documentation? Don't tell me that this tracking thing is sort of "from now on", like if address get transactions from the moment of track to the future?

UPDATE

I did try as well to do this via code as well and still got empty response. `(_client.GetBalanceAsync)` for example.

UPDATE

I did try to send some BTC to this test address to test this theory of "future transactions", that does not work either. Still empty response, no matter what endpoint I call, Postman or in code.

Health check is:

{```
  "status": "Healthy",
  "results": {
    "NodesHealthCheck": {
      "status": "Healthy",
      "description": null,
      "data": {
        "BTC": "Ready"
      }
    }
  }
}```

**Comment by farukterzioglu** [comment]
I tried to reproduce this on regtest but looks like it works. Btw tracking transaction definitely working as "from now on".
NBXplorer will catch the transaction that only happens after you track the address. 

Are you sure the test BTC transfer you send is being accepted and reaches to the node nbxplorer connected?

steps I tried to reproduce;

`./run.sh --chains=btc --network=regtest --bind 0.0.0.0 --port=24446 --noauth`

`curl --location --request GET 'http://localhost:24446/v1/cryptos/btc/addresses/2Mu46jNqnPRtvhc175fyef5kYmZyVcyppjE/transactions'`
returns empty response   

Track the address   
`curl --location --request POST 'http://localhost:24446/v1/cryptos/btc/addresses/2Mu46jNqnPRtvhc175fyef5kYmZyVcyppjE'`

send funds  
`bitcoin-cli sendtoaddress 2Mu46jNqnPRtvhc175fyef5kYmZyVcyppjE 1`

logs  
`info: Events:         BTC: 2Mu46jNqnPRtvhc175fyef5kYmZyVcyppjE matching unconfirmed transaction debf79...82ced2`

query transactions  
`curl --location --request GET 'http://localhost:24446/v1/cryptos/btc/addresses/2Mu46jNqnPRtvhc175fyef5kYmZyVcyppjE/transactions'`

response 
```
{
    "height": 108,
    "confirmedTransactions": {
        "transactions": []
    },
    "unconfirmedTransactions": {
        "transactions": [
            {
                "blockHash": null,
                "confirmations": 0,
                "height": null,
                "isMature": true,
                "transactionId": "050008c64100331e02069612773acb2a982a77421d78ba6420c95f080936c98c",
                "transaction": "02000000000101757ebec2c9640c8afab837baf1208ff2279c17b2ac4b35254725b70d59ecbe470000000000feffffff0200e1f5050000000017a91413d59e3e808e4575c9141ba824857fede150038387e8051024010000001600144c0a49ff6059b2e0deca8abcae9798ad3bfe11bc02473044022017137a47636060da1913b0de7d9852e9d7285a3b9983afeea769158047b62e6402204d044c07c22a761002e7c806f6eba2b0fdbf8a5ef59251c8ebfef61e25e7f3fa0121029fec196a86f1fee35b5a03a58d2fc0918757593455eadfa33f0ed759391e4f9e6c000000",
                "outputs": [
                    {
                        "scriptPubKey": "a91413d59e3e808e4575c9141ba824857fede150038387",
                        "index": 0,
                        "value": 100000000
                    }
                ],
                "inputs": [],
                "timestamp": 1646684326,
                "balanceChange": 100000000,
                "replacedBy": null,
                "replacing": null,
                "replaceable": false
            }
        ]
    },
    "immatureTransactions": {
        "transactions": []
    },
    "replacedTransactions": {
        "transactions": []
    }
}
```

Generate a block  
`bitcoin-cli generatetoaddress 1 bcrt1qvt6muemzlex43cewfdksc89c6mxqz80a7c4f73`

Logs 
```
info: Events:         BTC: 2Mu46jNqnPRtvhc175fyef5kYmZyVcyppjE matching confirmed transaction 050008...36c98c
info: Events:         BTC: New block 31b14dfa92ff9fd5e0ca3a7f515d3e5c0b8a6cc2e52566207e018da731f65dfb (109)
```

Respons of `/transactions`
```
{
    "height": 109,
    "confirmedTransactions": {
        "transactions": [
            {
                "blockHash": "31b14dfa92ff9fd5e0ca3a7f515d3e5c0b8a6cc2e52566207e018da731f65dfb",
                "confirmations": 1,
                "height": 109,
                "isMature": true,
                "transactionId": "050008c64100331e02069612773acb2a982a77421d78ba6420c95f080936c98c",
                "transaction": "02000000000101757ebec2c9640c8afab837baf1208ff2279c17b2ac4b35254725b70d59ecbe470000000000feffffff0200e1f5050000000017a91413d59e3e808e4575c9141ba824857fede150038387e8051024010000001600144c0a49ff6059b2e0deca8abcae9798ad3bfe11bc02473044022017137a47636060da1913b0de7d9852e9d7285a3b9983afeea769158047b62e6402204d044c07c22a761002e7c806f6eba2b0fdbf8a5ef59251c8ebfef61e25e7f3fa0121029fec196a86f1fee35b5a03a58d2fc0918757593455eadfa33f0ed759391e4f9e6c000000",
                "outputs": [
                    {
                        "scriptPubKey": "a91413d59e3e808e4575c9141ba824857fede150038387",
                        "index": 0,
                        "value": 100000000
                    }
                ],
                "inputs": [],
                "timestamp": 1646684326,
                "balanceChange": 100000000,
                "replacedBy": null,
                "replacing": null,
                "replaceable": false
            }
        ]
    },
    "unconfirmedTransactions": {
        "transactions": []
    },
    "immatureTransactions": {
        "transactions": []
    },
    "replacedTransactions": {
        "transactions": []
    }
}
```

**Comment by NicolasDorier** [comment]
@goors NBXplorer only show tracked transaction happening after you tracked it.

If you want past transaction, you need to track, then to issue a scan utxo set. But I don't think it works for individual address, only with derivation schemes.
