### ISSUE TITLE
Understanding NBXplorer usage

### ISSUE THREAD

**Issue by replaysMike** [dgarage/NBXplorer#36]
I've read over the mandatory reading at [here](https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html) and after playing around with QBitNinja I'm still confused as to how to transition to NBXplorer.

Is this the correct way to build ExtKey's from Keys generated by NBitcoin?

```
var secret = new BitcoinSecret("aSLJvEhXC6FqQ7oAckmxsBVSfaXqPm379yjhXyThR1p9oDpUNQqP", Network.TestNet);
var extKey = new ExtKey();
var chainCode = extKey.ChainCode;
var myExtKey = new ExtKey(secret.PrivateKey, chainCode);

var masterPubKey = myExtKey.Neuter(); // create a public version of the master key
var userDerivationScheme = network.DerivationStrategyFactory
    .CreateDirectDerivationStrategy(mikesKey.Neuter(),
    new DerivationStrategyOptions() {
        // Use non-segwit
        Legacy = true
    });
```

and if my code is correct, should this not output all transactions on that key?
`var transactions = client.GetTransactions(userDerivationScheme, null, true);`

What I'm after is figuring out how to receive notifications when transactions occur on my addresses in the blockchain, as well as get a list of total transactions to get the coin balance to replace my need for QBitNinja. Do I have this even remotely right? 

A few real-world examples would go a long ways as there are some large gaps in the online book. I'd love to contribute once I understand the architecture and implementation further.

**Comment by NicolasDorier** [comment]
You don't need to manipulate `BitcoinSecret`. If you want to generate a new key use `new ExtKey()`.

Then you can pass `new ExtKey().Neuter()` to NBXplorer like you are doing then by calling `NBXplorerClient.Track`. 

From this NBXplorer can track the payments without knowing your private ExtKey.

Then you use the example in the book to spend.

**Comment by replaysMike** [comment]
Is this because you are generating a new key on each transaction? This is what confused me, because I already have a generated key, I’m not looking to generate new ones

**Comment by NicolasDorier** [comment]
Yes, in you should not reuse keys for privacy reason. NBXplorer make it easy to do the right thing.
