### ISSUE TITLE
Document postgres configuration string

### ISSUE THREAD

**Issue by EugZol** [dgarage/NBXplorer#360]
`--help` returns the following:

```
 --postgres                 Use PostgresSQL backend. Set the connection string of the postgres backend (see https://www.connectionstrings.com/postgresql/)
```

First code snippet on https://www.connectionstrings.com/postgresql/ is "Standard", which reads:

```
User ID=root;Password=myPassword;Host=localhost;Port=5432;Database=myDataBase;Pooling=true;Min Pool Size=0;Max Pool Size=100;Connection Lifetime=0;
```

This code snippet doesn't work and fails with exception about `Min Pool Size`. Removing pooling parameters from the connection string then works.

Would be nice to add working connection string example to the docs, including README and command line help.

**Comment by NicolasDorier** [comment]
Thanks!
