### ISSUE TITLE
LBTC - NullPointerException in ScanUTXOSetService.cs:line 172

### ISSUE THREAD

**Issue by hard-money** [dgarage/NBXplorer#373]
Hi,

When trying to trigger a LBTC wallet rescan from BTCPayserver, I get a NullPointerException in ScanUTXOSetService.cs:line 172.

Here's a snippet of my logs

> Sep 14 19:32:23 XXXXX nbxplorer[26340]: info: NBXplorer.Events: LBTC: Node state changed: NBXplorerSynching => Ready
> Sep 14 19:32:35 XXXXX nbxplorer[26340]: info: NBXplorer.Events: LBTC: New block a49688f1fe49ad6d6c95f28e64675ea68ec267115ad5ffa11664c55cfa39f362 (2008467)
> Sep 14 19:32:36 XXXXX nbxplorer[26340]: info: Explorer:       LBTC: Start scanning xpub6C5HXZ... from index 0 with gap limit 10000, batch size 3000
> Sep 14 19:32:45 XXXXX nbxplorer[26340]: info: Explorer:       LBTC: Start scanning batch 0 of xpub6C5HXZ... from index 0
> Sep 14 19:32:46 XXXXX nbxplorer[26340]: fail: Explorer:       LBTC: Error while scanning xpub6C5HXZ...oKnHZ4GwCcguy96SQFFp
> Sep 14 19:32:46 XXXXX nbxplorer[26340]: System.NullReferenceException: Object reference not set to an instance of an object.
> Sep 14 19:32:46 XXXXX nbxplorer[26340]:    at NBitcoin.RPC.RPCClient.StartScanTxoutSetAsync(ScanTxoutSetParameters parameters, CancellationToken cancellationToken)
> Sep 14 19:32:46 XXXXX nbxplorer[26340]:    at NBitcoin.Extensions.WithCancellation[T](Task`1 task, CancellationToken cancellationToken)
> Sep 14 19:32:46 XXXXX nbxplorer[26340]:    at NBXplorer.ScanUTXOSetService.Listen() in /build/source/NBXplorer/ScanUTXOSetService.cs:line 172
> Sep 14 19:33:35 XXXXX nbxplorer[26340]: info: NBXplorer.Events: LBTC: New block 8194c6e11e8ccb2471b5cebbb1e69dee56e137ea9e93b698977ad73924919b2c (2008468)

**Comment by hard-money** [comment]
I think the issues lies with the element node not returning an response to the rpc call. Closing this defect.

**Comment by NicolasDorier** [comment]
a better error message would be nice though

**Comment by NicolasDorier** [comment]
it's probably a bug in NBitcoin, will fix it

**Comment by NicolasDorier** [comment]
So the error seems to be that there was no descriptor in the call.

**Comment by NicolasDorier** [comment]
Other issue, is that indeed, it seems liquid doesn't support scanutxoset, but you don't seem to have an error while calling the route.

**Comment by NicolasDorier** [comment]
@hard-money I can't reproduce the problem.

I tried with liquid 3.14.1.23, and the call to start a scan fail early, at the HTTP route level, not deeper down. May I ask you how you managed to trigger this code with LBTC?
