### ISSUE TITLE
Impossible to save private key in a descriptor RPC wallet

### ISSUE THREAD

**Issue by anycolo** [dgarage/NBXplorer#378]
https://github.com/btcpayserver/btcpayserver/issues/4208

**Comment by NicolasDorier** [comment]
Note there is almost no reason to save private keys in the RPC wallet. Though I will fix this issue.

**Comment by anycolo** [comment]
I think this needs to work for payjoin to work...

**Comment by NicolasDorier** [comment]
@anycolo no you don't. You do not need to save private keys in the RPC wallet, just need of hotwallet.

**Comment by NicolasDorier** [comment]
From 2.3.40:

* NBXplorer now support descriptor (you can run btcpay-update.sh to pull the new version) 
* I do not fix old wallets that crashed on this error before. Instead, you need to create a new wallet.
Note that you mentioned that you wanted Payjoin. You do not need to import keys in RPC for using it.

I closed this, feel free to re-open if after update and creating a new wallet on btcpay you still have issues.

**Comment by anycolo** [comment]
This fix should be pushed to LTC as well. DOGE and DASH don't have this issue yet.

**Comment by NicolasDorier** [comment]
LTC has the issue?

**Comment by NicolasDorier** [comment]
@anycolo I just fixed for LTC, just `btcpay-update.sh`. It was different issue.
