### ISSUE TITLE
Is it possible to get back the ExPubKey from a bitcoin address?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#38]
After creating a HD ExPubKey and registering the derivation scheme via `ExplorerClient.Track(userDerivationScheme)` is it possible to get the derivation scheme back (i.e. xpubkey)  from a given key path (which derived a bitcoin address ) from the NBXplorer database?

To Be more clear, suppose I have a bitcoin address e.g. "mnWoi6RjtvwHHRCHYmzzr14fZFf61drfA4" which was derived from path "0/0" (or "0/1" etc) can I somehow get back the "tpubD6NzVbkrYhZ4XtRwac3285m5k23....."? so I can tell to which HD wallet the address belongs?

I know it's a long shot but maybe the data base can return this information?

An alternative is querying and returning all the `userDerivationScheme` that were registered via `ExplorerClient.Track()`.

Thanks.

**Comment by NicolasDorier** [comment]
The API does not expose this right now but I don't see any problem into adding a route for such feature.

**Comment by bazooka70** [comment]
Great. I think this could be a very usul feature!

**Comment by NicolasDorier** [comment]
no, you should submit a tested PR and then close :p

**Comment by bazooka70** [comment]
Baaaaaaahhh! How on earth should I know where to start dinging with this issue? can you please give me a lead?

**Comment by NicolasDorier** [comment]
need to update `MainController`, `NBXplorerClient` and then test it by adding a line somewhere in any Tests called `Track`.

**Comment by bazooka70** [comment]
I think this is way over my head. I'm not sure which table holds that information. 
After reading the code a thousand times, my guess was `HighestPath` where it stores 

In the `MainControler` I added:

```csharp
                [HttpGet]
                [Route("cryptos/{cryptoCode}/derivations/getderivations")] 
		public IActionResult GetDerivations(
			string cryptoCode)
		{
			var network = GetNetwork(cryptoCode);
			var repo = RepositoryProvider.GetRepository(network);
			var tracked = repo.GetTracked();
			return Json(tracked);
		}

```

In the `Repository.cs` I added to the `Index` class
```csharp
                        public IEnumerable<DBreeze.DataTypes.Row<string, T>> SelectForward<T>(DBreeze.Transactions.Transaction tx) 
			{
				return tx.SelectForward<string, T>(TableName);
			}
```

In the `Repository` class I added:

```csharp
                public KeyPathInformation[] GetTracked()
		{			
			_Engine.Do(tx =>
			{				
				tx.ValuesLazyLoadingIsOn = false;				
				var table = new Index($"{_Suffix}HighestPath", "");
                                // table.SelectForward<byte[]>(tx).Count() returns 18  
				var keyInfos = table.SelectForward<byte[]>(tx)
									.Select(r => ToObject<KeyPathInformation>(r.Value))
									.ToArray();
				return keyInfos;

			});
			return null;
		}
```

Then running:
http://127.0.0.1:24445/v1/cryptos/BCH/derivations/getderivations

Will throw an exception:

> InvalidDataException: The archive entry was compressed using an unsupported compression method

The same code with `AvailableKeys` table simply returns null. although Count() returns 540 rows.
Obviously I'm not sure what I'm doing, and basically guessing my way forward...

**Comment by bazooka70** [comment]
I think I managed to do something:
https://github.com/dgarage/NBXplorer/pull/44
