### ISSUE TITLE
Create PSBT with certain UTXOS

### ISSUE THREAD

**Issue by Bit-Shifts** [dgarage/NBXplorer#380]
Just wondering if there is a ways to create a PSBT that makes sure to use certain utxos before others ?

**Comment by NicolasDorier** [comment]
https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#create-partially-signed-bitcoin-transaction `includeOnlyOutpoints`

**Comment by Bit-Shifts** [comment]
Thanks
