### ISSUE TITLE
.nbxplorer directory missing 

### ISSUE THREAD

**Issue by hdlslm** [dgarage/NBXplorer#387]
after cloning repo, cd to .NBxplorer and running ./build.sh there is no  .nbxplorer dir present to get to ".nbxplorer/Main/settings.config" 
oh i am running the above commands as a non sudo user account i created if that helps.
thanks

**Comment by ericsupreme** [comment]
> I don't understand, why you want this folder?

hmmmm to access the settings.config file

**Comment by NicolasDorier** [comment]
the folder is created when you run for the first time.

**Comment by hdlslm** [comment]
ahhh ok now that makes sense. i was following an install guide and they have me editing the config file before running. i will let them know to change that, thank you for your help.
