### ISSUE TITLE
Dash Block parsing issue

### ISSUE THREAD

**Issue by NicolasDorier** [dgarage/NBXplorer#39]
@bdangh it seems the tests don't pass with DASH (CanTrack4 for example).

It seems the explorer does not receive blocks. Maybe different format or something?

**Comment by cronos-polis** [comment]
Yes, Polis is having the same issue.

**Comment by cronos-polis** [comment]
I think we must do a C# implementation of the X11 algorithm and parse the headers through it.

**Comment by bdangh** [comment]
@cronos-polis X11 [implemented](https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin.Altcoins/HashX11/X11.cs). I’m going to debug soon. I guess this is a bug somewhere in the code because of different header format/hash.

**Comment by NicolasDorier** [comment]
There is two kind of hashes. PoWHash and GetHash. One is for linking blocks, the other for checking the PoW. I am surprised it breaks to be honest, as the tests on regtest for NBitcoin.Altcoins seems to work.

**Comment by bdangh** [comment]
Found an issue, so https://github.com/playhub/NBXplorer/blob/db746fb38bd74f62e6d7a71d6af3e6fa240f158d/NBXplorer/ExplorerBehavior.cs#L204 Block Header is not one from ConsensusFactory but Bitcoin BlockHeader, this is why hashes not match. I guess Doge is not working too, on mainnet, this should be fixed at NBitcoin side.

**Comment by NicolasDorier** [comment]
@bdangh ok found several bugs in NBitcoin. Pushing now, fixed Dash and Doge and added better tests to catch this in the future.

**Comment by NicolasDorier** [comment]
yay! closing this it works now, will push soon.
