### ISSUE TITLE
Incorrect "Confirmations" value for newtransaction events

### ISSUE THREAD

**Issue by Bit-Shifts** [dgarage/NBXplorer#399]
[v2.3.58]
NBXPLORER_DBTRIE: 1

Getting the usual 2 newtransaction events for a given transaction but both have events are for 0 confirmation.

one event has the blockId and the other does not. Both have different time stamps so these are 2 different messages but both with 0 confirmations and the 1 confirmation never comes.

**Comment by Bit-Shifts** [comment]
I am even getting 0 confirmation in newtransaction events with routing key 

`transactions.*.confirmed`

**Comment by NicolasDorier** [comment]
It's a bug only in DBTRIE version, I will not fix it, please migrate to NBX as soon as you can.
The migration is easy https://github.com/dgarage/NBXplorer/blob/master/docs/Postgres-Migration.md

**Comment by Bit-Shifts** [comment]
Roger that.

Will go through the process of migration.
