### ISSUE TITLE
Make compatible with btcd

### ISSUE THREAD

**Issue by stevenroose** [dgarage/NBXplorer#4]
How hard would it be to provide an alternative RPC API? 

I would like to make btcpay compatible with [btcd](https://github.com/btcsuite/btcd). The RPC API of btcd is mostly similar to the one from bitcoind, but I don't know how much the usage of the RPC is spread around the code base? Or is it neatly abstracted behind an interface?

I've never written any C#, but if the RPC part is well-abstracted, I think I should be able to use the bitcoind-based code and port it to btcd.

**Comment by NicolasDorier** [comment]
NBXplorer depends only on RPC for broadcasting transaction, getting estimated fees, and checking if the node is synched so it should be easy to abstract only that.

**Comment by stevenroose** [comment]
Hmm, so how does it get block data? Over p2p?

Btw, btcd can run with full transaction and address index. Would that make
it possible to run btcpay directly on btcd?

On 29 Jan 2018 1:45 am, "Nicolas Dorier" <notifications@github.com> wrote:

NBXplorer depends only on RPC for broadcasting transaction, getting
estimated fees, and checking if the node is synched so it should be easy to
abstract only that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dgarage/NBXplorer/issues/4#issuecomment-361112420>, or mute
the thread

**Comment by NicolasDorier** [comment]
Yes it get blocks and tx over p2p.

> Btw, btcd can run with full transaction and address index. Would that make
it possible to run btcpay directly on btcd?

BTCPay is itself a address and transaction index, so it handles that itself.

**Comment by stevenroose** [comment]
If btcpay has the indexes itself, why does it use NBXplorer?

**Comment by NicolasDorier** [comment]
Sorry I meant NBXplorer, not BTCPay.

**Comment by stevenroose** [comment]
Any pointers you can give me to try and implement this? I see that the BTCPay Slack is not working; any chance I can find you in an IRC channel somewhere?

There must be a file somewhere that defines a C# interface for the blockchain backend that is then implemented using the bitcoind API, right? Or is the API more heavily blended in the codebase?

**Comment by NicolasDorier** [comment]
The slack is http://slack.forkbitpay.ninja/

I depends directly on `RPCClient` in different place in the code, you need to provide good abstraction if you want to make something different. I can't really point that to you where you should look without doing all the work myself, this is not necessarily obvious to do, and might be more complicated than I think. (For example you NBXplorer need to properly report some data through the GetStatus route which might only be available on Bitcoin Core)

Just for information, why are you trying to make it works with btcd?

**Comment by stevenroose** [comment]
@NicolasDorier It's always nice to support different implementations, no?

As for why I'm running btcd myself, I personally think it's not very healthy to heave so little diversity in the implementations people depend on. I run a btcd node and use it, so I prefer to not have to run bitcoind as well :)

I took a quick look and yeah you're right, it seems like the RPCClient is used in quite some places. You think it would be really hard to make a file with an interface that has all the

**Comment by NicolasDorier** [comment]
No I don't think it is hard to abstract.

**Comment by NicolasDorier** [comment]
Reopen when you feel like abstracting RPCClient. Though the best would be for btcd to implement the rpc methods.

**Comment by stevenroose** [comment]
Actually, now that you mention it, it couldn't be that hard to simply write a proxy in the middle. What file should I look into to see what calls are being used?

**Comment by NicolasDorier** [comment]
Yes a proxy might be a good idea. You just have to search for the string "rpcClient".
There is not so much used actually.

**Comment by stevenroose** [comment]
@NicolasDorier I've never used C# for real (hello world code, yes :D), so I'm not sure. I could give it a try though, the project I wanted btcpay for is moving forward, so at some point I'm either gonna have to do it, or run a bitcoind node alongside btcd :)

**Comment by adiack** [comment]
@stevenroose finally did you give up and use bitcoind instead :) ? I'm keen on trying btcpay with my fully synced btcd node.

**Comment by stevenroose** [comment]
I started working for Blockstream so yeah my involvement with btcd slowed
down in favor of Core.
