### ISSUE TITLE
BCH testnet is stuck on CoreSynching

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#40]
I could swear everything worked fine, but now on 2 machines (with latest NBXplorer version) the NBXplorer server is stuck in the state of `CoreSynching`, and won't go to the next step of HandsShake and so on...

Eventually there is a timeout followed by some exceptions, and it goes back to the CoreSynching state.

The testnet core itself is fully synced.

I looked at the `IsSynchingCore` and it looks like this:

```csharp
public bool IsSynchingCore(GetBlockchainInfoResponse blockchainInfo)
{
	// return false; // @@@
	if(blockchainInfo.InitialBlockDownload.HasValue)
		return blockchainInfo.InitialBlockDownload.Value;
	if(blockchainInfo.MedianTime.HasValue && _Network.DefaultSettings.ChainType != ChainType.Regtest)
	{
		var time = NBitcoin.Utils.UnixTimeToDateTime(blockchainInfo.MedianTime.Value);
		// 5 month diff? probably synching...
		if(DateTimeOffset.UtcNow - time > TimeSpan.FromDays(30 * 5))
		{
			return true;
		}
	}

	return blockchainInfo.Headers - blockchainInfo.Blocks > 6;
}
```
The `return false` comment is mine.
if I return `false` everything goes well and there is a handshake and NBXplorer  getting new blocks just fine.

What could cause this and how to fix? is the "probably synching" assumption accurate? there is no such problem with main net.

Can you please assist? Thanks in advanced.

**Comment by bazooka70** [comment]
After another test, the return value is returned from:

`return blockchainInfo.Headers - blockchainInfo.Blocks > 6;`

In my case `blockchainInfo.Headers= 1225583` and `blockchainInfo.Blocks = 1225531`

So this is a difference of 52 (blocks?) > 6 
And the return value is `true` of course.

**Comment by NicolasDorier** [comment]
check your BCH node. NBXplorer is not the culprit here, your node is really synching.

**Comment by bazooka70** [comment]
I have checked the BCH node, and I see no indication that the node is synching. this is why I asked for your insight. I also don't see any crashes in the core logs. I'm simply trying to figure out what could be the reason. maybe the BCH testnet Network is not properly configured (I double checked).

BTW, the `return blockchainInfo.Headers - blockchainInfo.Blocks` sometimes returns a negative values (e.g. -167 etc). is that normal?

**Comment by NicolasDorier** [comment]
Not normal. Can you run "getblockchaininfo" rpc command and your node and give me the value?

**Comment by bazooka70** [comment]
```
{
  "chain": "test",
  "blocks": 1225832,
  "headers": 1225583,
  "bestblockhash": "00000000792df21845d5910e735b894bd421d99920d90c909c1691265291f2e0",
  "difficulty": 1,
  "mediantime": 1523708739,
  "verificationprogress": 0.999956997713688,
  "chainwork": "000000000000000000000000000000000000000000000029e91e4fe146a44a8f",
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "active",
      "startTime": 1456790400,
      "timeout": 1493596800,
      "since": 770112
    }
  }
}
```

**Comment by NicolasDorier** [comment]
O_o can you post an issue there https://github.com/Bitcoin-ABC/bitcoin-abc ? seems like a bug.

**Comment by bazooka70** [comment]
Where do you see a bug? 
is it the fact that Blocks > Headers?

**Comment by bazooka70** [comment]
> O_o can you post an issue there https://github.com/Bitcoin-ABC/bitcoin-abc ? seems like a bug.

Done.

**Comment by NicolasDorier** [comment]
Their repo is a dead zone :D

**Comment by bazooka70** [comment]
Holly shit! I see you already added BitcoinGold to NBitcoin :) But you did not rename it to BGold like you did with BCash! LOL

**Comment by NicolasDorier** [comment]
Ah I have not even thought about it lol :p

**Comment by bazooka70** [comment]
Yeah... I remember well your lecture about not trashing Bitcoin name with other shit coins or whatever :-p

**Comment by bazooka70** [comment]
No need. Its fine as is :;

**Comment by NicolasDorier** [comment]
I just did ;)
I refactored things thanks to the new `NetworkType` there was some neat stuff to add in the lib.
Will update NBXplorer shortly.

**Comment by bazooka70** [comment]
Yes I had a look at it. Amazing job!

**Comment by NicolasDorier** [comment]
Closing this as it is not really a bug of NBXplorer. Reopen if you think we can do something at NBXplorer level.

**Comment by bazooka70** [comment]
Yes, you got a point here about closing.
