### ISSUE TITLE
substractFees removes the destination from outputs if amount is too low

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#422]
When we try to create a PSBT with a small amount (like 700) with the option `substractFees`, because the resulting amount (700 - fee) will be less than dust, it removes this output and transaction ends up with only change output. 

E.g.: 

Request;
```
{
    "Destinations": [
        {
            "Destination": "2N4mzNV2....",
            "Amount": 700,
            "SubstractFees": true
        }
    ]
}
```
Response; 
```
{
    "spentCoins": [
        {
            "keyPath": "0/0",
            "value": 612,
            "outpoint": {
                "hash": ".....b202f58b3451c8b4416....",
                "index": 1
            }
        },
        {
            "keyPath": "0/0",
            "value": 564,
            "outpoint": {
                "hash": "....a4ba9004117a7478e195a....",
                "index": 1
            }
        }
    ],
    "changeInformation": {
        "keyPath": "1/17",
        "value": 951
    },
    "transaction": "0100000002088826b4....08700000000",
    "fee": 225,
    "vSize": 225
}
```

Decoded tx;
```
{
    "addresses": [
        "2NAdn4bW53....",
        "2NDyGnkbTY...."
    ],
    "block_height": -1,
    "block_index": -1,
    "confirmations": 0,
    "double_spend": false,
    "fees": 225,
    "hash": "624eaaa823a13b2cd20cc906c7570cfd1f11dfc5db324f47a50175f9648229b4",
    "inputs": [
        {
            "addresses": [
                "2NAdn4bW53..."
            ],
            "age": 2475275,
            "output_index": 1,
            "output_value": 612,
            "prev_hash": "a933a3c4508e4add3....",
            "script": "16001481e8ce7654b0c....",
            "script_type": "pay-to-script-hash",
            "sequence": 4294967295
        },
        {
            "addresses": [
                "2NAdn4bW53...."
            ],
            "age": 2475280,
            "output_index": 1,
            "output_value": 564,
            "prev_hash": "b7ca36c949fc0b206bc....",
            "script": "16001481e8ce7654....",
            "script_type": "pay-to-script-hash",
            "sequence": 4294967295
        }
    ],
    "outputs": [
        {
            "addresses": [
                "2NDyGnkbTYn9Kn...."
            ],
            "script": "a914e356530a7b378.....",
            "script_type": "pay-to-script-hash",
            "value": 951
        }
    ],
    "preference": "low",
    "received": "2023-08-29T12:42:56.125388391Z",
    "relayed_by": "34.205.225.3",
    "size": 170,
    "total": 951,
    "ver": 1,
    "vin_sz": 2,
    "vout_sz": 1,
    "vsize": 170
}
```

Receiver `2N4mzNV2...` isn't exist in the output. There is only a change address.   

If I set the change address explicitly, with `explicitChangeAddress`, the only output is still to this address.   

I tried with different input combinations: single small input, single big input, multiple inputs. With all of them, receiver is removed from the outputs. 

If I increase the amount that being sent (800), it works ok;
```
"outputs": [
        {
            "addresses": [
                "2N4mzNV2...."
            ],
            "script": "a9147e7ae94d5bb6ce681a939e00c7370affa577302187",
            "script_type": "pay-to-script-hash",
            "value": 575
        }
    ],
```

I suspect it is related to this code, but not sure %100:    https://github.com/MetacoSA/NBitcoin/blob/93ef4532b9f2ea52b2c910266eeb6684f3bd25de/NBitcoin/TransactionBuilder.cs#L1202

I am not sure this is the expected behaviour. If not, I am wondering if we can get some kind of validation error when the ended up with an output is less than dust.

**Comment by farukterzioglu** [comment]
Tried without `substractFees`  

Result is ok;
```
"outputs": [
        {
            "addresses": [
                "2N4mzNV2...."
            ],
            "script": "a9147e7ae94d5bb6ce681a939e00c7370affa577302187",
            "script_type": "pay-to-script-hash",
            "value": 700
        }
    ],
```

**Comment by NicolasDorier** [comment]
Can you try to reproduce this in a test?

Normally, you should get back an error `output-too-small`.

This is handled [here](https://github.com/dgarage/NBXplorer/blob/cfb9aa95060f1aea7f0ed3ad068a502cc50edd3f/NBXplorer/Controllers/MainController.PSBT.cs#L253)  and [here](https://github.com/dgarage/NBXplorer/blob/cfb9aa95060f1aea7f0ed3ad068a502cc50edd3f/NBXplorer/Controllers/MainController.PSBT.cs#L317).

And it is tested [here](https://github.com/dgarage/NBXplorer/blob/cfb9aa95060f1aea7f0ed3ad068a502cc50edd3f/NBXplorer.Tests/UnitTest1.cs#L978).

**Comment by farukterzioglu** [comment]
That exception seem to be thrown only when the output is below zero;  
<img width="885" alt="image" src="https://github.com/dgarage/NBXplorer/assets/476514/f5f120e0-d8f4-4093-b7c8-4427df335940">

Here https://github.com/MetacoSA/NBitcoin/blob/93ef4532b9f2ea52b2c910266eeb6684f3bd25de/NBitcoin/TransactionBuilder.cs#L1194

My case looks like more about here;
<img width="838" alt="image" src="https://github.com/dgarage/NBXplorer/assets/476514/64d82ad8-2403-49c3-936c-106cfc33e8f5">

Method returns without adding this output, and the amount that being removed is added to `DustPreventionTotalRemoved`. But I don't see where `DustPreventionTotalRemoved` exactly used. As far as I see it is only being set, no one reads it. 

Still checking to reproduce it in unit tests....

**Comment by NicolasDorier** [comment]
mmmh you seem right. Will take a deeper look tomorrow.

There might be a reason why I strip between 0 and dust and don't send an error. I will check.

**Comment by farukterzioglu** [comment]
@NicolasDorier to reflect the changes in NBitcoin to NBXplorer, does [this](https://github.com/farukterzioglu/NBXplorer/pull/7/files) seems correct?

CI in my fork is failing for some reason. I will check again if the tests are passing.
