### ISSUE TITLE
Calculated fee is lower then minimum expected fee by the network

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#423]
When I prepare a transaction both on bitcoin-regtest and bitcoin-testnet then try to broadcast it, time to time it throws `Transaction was rejected by network rules","rpcMessage":"min relay fee not met, 166 < 198`

The prepared transaction sets the fee as 166 but when we broadcast it just after, it gets rejected. 

Request sample;

```
{
  "destinations" : [
    {
      "destination" : "2N9xEnjM....",
      "amount" : 1529,
      "substractFees" : true,
      "sweepAll" : false
    },
    {
      "destination" : "2N9xEnjM...",
      "amount" : 2137,
      "substractFees" : false,
      "sweepAll" : false
    }
  ],
  "feeRate" : 1.0,
  "includeOnlyOutpoints" : null,
  "excludeOutpoints" : [
  ],
  "ignoreLocks" : true,
  "explicitChangeAddress" : "2MwmzFeqR2..."
}
```

Result;
```
{
  "spentCoins" : [
    {
      "keyPath" : "0/0",
      "value" : 6137,
      "outpoint" : {
        "hash" : "dbea141902715b56....",
        "index" : 0
      }
    }
  ],
  "changeInformation" : {
    "keyPath" : "1/0",
    "value" : 2471
  },
  "fee" : 166,
  "transaction" : "01000000010dd4200e39....ae7b15f62c8a2232c75fee263a048700000000",
  "vSize" : 166
}
```

**Comment by NicolasDorier** [comment]
You set feeRate to 1.0. This is what would happen if the min mempool fee would be 1.1 sat/vbyte.

If it's not this case, this is an important bug and I really need a repro.

**Comment by farukterzioglu** [comment]
We are getting the fee rate from fee endpoint and using it just after. 
This happens of regtest & testnet.

When we are getting this error, there are other succesful transactions almost at the same time.
