### ISSUE TITLE
Incorrect balance when NBXplorer is running on Linux s390x Server

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#428]
We are running NBXplorer and Postgres database on Linux s390x server. 
Balance data is correct in DB, and also when we get transactions with `/transactions` every thing is correct. But when we get the balance with `/balance`, it returns a very big number, hexadecimal presentation of actuall balance value.

If we run the same NBX in another place (non s390x) it works ok. 

Here are some data;

from `nbxv1_tracked_txs`;
`BTC  | e86117a46a211b2ccacadf22a1689d07a4946b4eb2c3e8dc6be221e4ae07ad15 |   1 | 1030678 | 2MvA9XerLqnRKj1UubEu8D5pnqJrNNtk8Nk`

`/transactions` response;

```
{
    "confirmedTransactions": {
        "transactions": [
            {
                "transactionId": "e86117a46a211b2ccacadf22a1689d07a4946b4eb2c3e8dc6be221e4ae07ad15",
                "outputs": [
                    {
                        "keyPath": "0/0",
                        "scriptPubKey": "a9141ff29342852c62943f72caac56bb22f5f08bb3a487",
                        "index": 1,
                        "value": 1030678,
                        "address": "2MvA9XerLqnRKj1UubEu8D5pnqJrNNtk8Nk"
                    }
                ],
                ...
            }
        ]
    }
    ...
}
```

balance request;  
`HTTP GET /v1/cryptos/BTC/derivations/tpubD6NzVbkrYhZ4XfMuYMcbbY2MS7gMksCntMajRsimXp9Zk7CPd1xNXRsMkqeiZBReuGNGPnspk6Tc7k2cJ3kHM8o9KTHdffhMHaEys4iKwtR-%5Bp2sh%5D/balance`
response;
```
{"unconfirmed":0,"confirmed":4426728302706688,"total":4426728302706688,"immature":0,"available":4426728302706688}
```

watch out for `4426728302706688` in balance. 

decimal value: `1030678`, hexadecimal equivalent: `FBA16`
also;
`4426728302706688` is **FBA16**00000000 in hexadecimal

I added some logs to understand when exactly it get wrong, it seems as soon as we get it from DB;
<img width="980" alt="image" src="https://github.com/dgarage/NBXplorer/assets/476514/4ef2abc0-e4f2-4a99-b991-0e592cd622d2">

<img width="723" alt="image" src="https://github.com/dgarage/NBXplorer/assets/476514/1312bfa6-fd8b-46cf-9a9a-5d2ad2c2725b">

**Comment by farukterzioglu** [comment]
Some progress on this one;
I created a simple .Net application that reads from wallets_balances. If I get the value as string from database, it gets the correct value.

<img width="1020" alt="image" src="https://github.com/dgarage/NBXplorer/assets/476514/481a0f89-2de7-47bf-8938-de97d88a11a6">

Result:
<img width="1006" alt="image" src="https://github.com/dgarage/NBXplorer/assets/476514/64f7438f-0b99-453d-89cd-beb137fe71d3">

**Comment by farukterzioglu** [comment]
I still couldn't find the root cause. It is probably about Linux s390x [is](https://docs.gitlab.com/omnibus/development/s390x.html) being big-endian. 

How about a workround as;
<img width="1318" alt="image" src="https://github.com/dgarage/NBXplorer/assets/476514/d2b079e4-8b9f-4f40-9022-a3f7d73ec6dc">

Although, there may be other places the numeric type is being used.

**Comment by farukterzioglu** [comment]
I tried with `wallets_utxos` inside Linux s390x, and we don't have a problem with it;
I ran the query ;`SELECT * FROM wallets_utxos` 

`value` in `wallets_utxos` is int8.  
But values in `wallets_balances` is all numeric.  

How about updating definition of this view;

<img width="1244" alt="image" src="https://github.com/dgarage/NBXplorer/assets/476514/8bb16f10-34c0-4685-b02b-d436806a2046">

**Comment by farukterzioglu** [comment]
As far as I see from codes of Npsql, it considers endianness, but maybe there is bug in Numeric converter. 

<img width="902" alt="image" src="https://github.com/dgarage/NBXplorer/assets/476514/a60cdb2d-b51f-4add-a429-c0431888286f">

**Comment by farukterzioglu** [comment]
for now I will continue will the work around;

```
var b = await conn.QueryAsync(@"SELECT 
	wallet_id, code, asset_id,
	CAST(confirmed_balance AS VARCHAR), 
	CAST(unconfirmed_balance AS VARCHAR),  
	CAST(available_balance AS VARCHAR),
	CAST(immature_balance AS VARCHAR)
	FROM wallets_balances WHERE code=@code AND wallet_id=@walletId", new { code = network.CryptoCode, walletId = repo.GetWalletKey(trackedSource).wid });
```

**Comment by NicolasDorier** [comment]
@farukterzioglu maybe you shouldn't fix it in the SQL request, but reverse the endianness in the C# code.
It seems to me a bug in npgsql, will check.

**Comment by farukterzioglu** [comment]
An issue on Npgsql is opened: https://github.com/npgsql/npgsql/issues/5308

**Comment by farukterzioglu** [comment]
I am closing this issue since it is not a bug of NBXplorer. 
But in case NBXplorer needs to be used in S390X, a workaround should be applied until https://github.com/npgsql/npgsql/issues/5308 gets fixed.

**Comment by farukterzioglu** [comment]
Npgsql [ 8.0.0-rc.2 ](https://www.nuget.org/packages/Npgsql/8.0.0-rc.2) has a fix for this issue.
