### ISSUE TITLE
NBXplorer internal exception when referencing Nuget packages in Microsoft.Extensions namespace

### ISSUE THREAD

**Issue by replaysMike** [dgarage/NBXplorer#43]
I've been working on an NBXplorer project and ran into a fairly significant snag.

I'm using .net core 2.1 and when referencing any nuget package in the Microsoft.Extensions namespace in any project referenced by the NBXplorer package I'm getting an exception and it's tough to get around. Pretty much everything from entity framework to configuration exists in that namespace. (Microsoft.Extensions.Configuration, Microsoft.Extensions.Logging, Microsoft.Extensions.Identity.Stores, etc)

```
var network = new NBXplorerNetworkProvider(ChainType.Test).GetBTC(); // throws exception

TypeLoadException: Could not load type 'System.MemoryExtensions' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

The exception is thrown in ChainTypeExtensions, ChainType.cs:30:
```
if(chainType == ChainType.Main)
    return Network.Main; // exception thrown from here
```

However the error seems to originate in NBitcoin according to the inner exception:
```
   at System.Net.IPAddress.Parse(String ipString)
   at NBitcoin.Utils.ParseIpEndpoint(String endpoint, Int32 defaultPort)
   at NBitcoin.Network.InitMain()
   at NBitcoin.Network..cctor()
```

I haven't been able to find out what exactly the problem is. I tried building NBitcoin but was unable to within VS2017.

**Comment by NicolasDorier** [comment]
Interesting thanks. Please use netcoreapp2.0 and not 2.1. 2.1 is still a preview so things might break.

**Comment by NicolasDorier** [comment]
Meanwhile can you tell me the steps to reproduce this? (command lines)

**Comment by replaysMike** [comment]
I'll build a sample project and upload it. Working on building it on another machine to rule out an installation/environment issue.

**Comment by replaysMike** [comment]
[Core21Test.zip](https://github.com/dgarage/NBXplorer/files/1910083/Core21Test.zip)

Attached is a simple console app in .net core 2.1 that demonstrates the problem (at least on my machine).
I've uninstalled and re-installed VS2017 and had no effect on the problem. I did try changing to .net core 2.0 and it works fine. Not sure if they screwed something up when they added the System.Memoryextensions for C# 7 or this is something really new.

**Comment by NicolasDorier** [comment]
Yes this is interesting.
My packages are normally targetting netstandard so it should have worked...

**Comment by NicolasDorier** [comment]
Will migrate to 2.1 as soon as it leave preview. Nevertheless it should have worked.

**Comment by PinpointTownes** [comment]
> I am using a fair bit of 2.1 for the web stuff as I'm working with the latest ASOS/Identity and OpenIddict which require it.

FYI, neither ASOS nor OpenIddict are supposed to depend on the pre-release 2.1 bits. If they do, that's a bug we should address.

**Comment by replaysMike** [comment]
hey how'd you get here so fast? lol ;) It could have been my misunderstanding, I thought OpenIddict with JWT required 2.1 but I'm probably wrong on this fact.

**Comment by PinpointTownes** [comment]
@replaysMike I built a tiny homemade bot that alerts me when GitHub issues mentioning OpenIddict are posted. This allows me to pro-actively fix bugs even if they are not reported at the right place :smile:

**Comment by NicolasDorier** [comment]
Closing this as I think it is not really an issue at NBXplorer lib. Would be interested to know what is going on though.

**Comment by NicolasDorier** [comment]
hey @replaysMike seems like it is indeed a .NET Core 2.1 bug (https://github.com/dotnet/corefx/issues/29149) and not OpenIddict @PinpointTownes
