### ISSUE TITLE
Can you release an NBXplorer that includes the latest NBitcoin to support the Qtum hard fork?

### ISSUE THREAD

**Issue by shu-kob** [dgarage/NBXplorer#433]
You have previously merged a pull request to raise Qtum's Protocol Version with NBitcoin in preparation for Qtum's hardfork.
<br>
https://github.com/MetacoSA/NBitcoin/pull/1184
<br>
Could you please release a NBXplorer that includes NBitcoin with this change?

**Comment by NicolasDorier** [comment]
closing, probably already done by now

**Comment by shu-kob** [comment]
Thank you!
