### ISSUE TITLE
Support RBF

### ISSUE THREAD

**Issue by Kukks** [dgarage/NBXplorer#434]
* Allow fetching utxos which have been spent, but only in the mempool
*  Allow constructing psbts mandating certain utxos are in it

**Comment by farukterzioglu** [comment]
I just came to see if there was any previous issues with RBF and saw this. 
I am having problem while creating replacement transaction. 

Right now I can create RBF activated transaction with NBXplorer, but whenever I create a transaction that replacing the previous one, I am getting not-enough-funds exception. 

I double checked that previous transaction is not confirmed. Actually I am testing in regtest and I am not creating any block at that moment. 

Is there any issue on PSBT endpoint that prevents creating replacement transaction.

**Comment by NicolasDorier** [comment]
on it

**Comment by NicolasDorier** [comment]
I think a potential later PR that might be useful: A simple command that allow to give which txid to replace, and then automatically make a new PSBT which bump the fees.
