### ISSUE TITLE
Network.ToChainType() supports only BTC network

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#45]
`NBitcoin` `Network.ToChainType()` supports only BTC network, but not the alt coins networks.
I'm not sure how to resolve this issue in a matter of the framework design, so I can't even propose a PR. 
It would be nice if the `Network` class could have this property/method (or it's own **common**  property that will indicate which chain the `Network` uses)

Maybe the `ChainType` property should belong to the `Network` class instead of the `NBXplorer` network...

What do you think?

**Comment by NicolasDorier** [comment]
This is intentional. `.ToChainType()` is here just because I am highjacking mainnet/testnet/regtest strings for the `chain=` parameter.

`ChainType` is rightfully a property of NBXplorer. Will think about to move it lower. But I don't think I will in short term.

**Comment by NicolasDorier** [comment]
Feel free to make a PR in NBitcoin for it, concept ACK! :)

**Comment by bazooka70** [comment]
OK, I will close this issue now, and might reopen if I will be capable of doing this task... :)

**Comment by bazooka70** [comment]
https://github.com/MetacoSA/NBitcoin/pull/398

**Comment by NicolasDorier** [comment]
Updated NBxplorer to use it all over the place instead of ChainType.
