### ISSUE TITLE
how to retrieve balance from tracked source correctly?

### ISSUE THREAD

**Issue by hparsafar** [dgarage/NBXplorer#471]
As I understand it, NBExplorer stores new blocks published on the network. Likewise, if a transaction is related to a tracked source, it stores it in its database. And it does not go to the previous transactions published in the network.

Considering this issue, how can it correctly return the balance of a tracked source if it does not look for transactions related to it in previous historical blocks?
For example, I imported an address of testNet Dogecoin whose balance is not zero, but when I got the balance, zero was returned.

address=https://sochain.com/address/DOGETEST/njXAPNFEjWSnVY8x3njF9sQ3KBTvVe4GQR
API = https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#get-balance-of-tracked-sources

**Comment by NicolasDorier** [comment]
You can use https://dgarage.github.io/NBXplorer/#tag/Derivations/paths/~1v1~1cryptos~1%7BcryptoCode%7D~1derivations~1%7BderivationScheme%7D~1utxos~1scan/post

This will fetch all the utxos from the set.
However, I am not sure if DOGE implement it or not. If it doesn't, then you can't.
