### ISSUE TITLE
Supporting multiple alt coin on the same machine?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#48]
I'm sorry I'm asking this here as an issue, but I don't know where else to ask. 
The chat room now is a big spam room, and there is no response there... :/

Ok, so NBXplorer suppose to support multiple alt coins (on the same machine?), how many daemons can I run on a **single** Windows production machine so both NBXplorer and the nodes stay stable?
Also, Which configuration would be appropriate for multi nodes?

**Comment by NicolasDorier** [comment]
depends on the number of supported coins and machine specs.

**Comment by bazooka70** [comment]
This is exactly my question. suppose I have a monster machine. how many coins can be supported?
from your experience....

**Comment by NicolasDorier** [comment]
Closing this, nobody can reasonably reply without testing.
