### ISSUE TITLE
Unspent coins fetch

### ISSUE THREAD

**Issue by Ashish81** [dgarage/NBXplorer#5]
ExplorerClient or BTCpayserver .,how to get unspent  outpoint as Coin. 
I was using qbitninja to send btc , looking fir alternative for "qbitninja/unspentonly ".

**Comment by Ashish81** [comment]
Was using transactionbuilder , grt help if you privide some cide snippet

**Comment by NicolasDorier** [comment]
It was actually quite complex. I just released a new version of the server and client so it is easy.

```
NBXplorer.ExplorerClient client =  ...;
txBuilder.AddCoins(client.GetUTXOs(...).GetUnspentCoins());
...
```

You need nuget package 1.0.1.4 and 1.0.1.7. (It is being upload on nuget now)

**Comment by NicolasDorier** [comment]
I added documentation here 

https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/block_explorers.html

**Comment by nopara73** [comment]
I didn't get GitHub notification about that. Strange.

**Comment by NicolasDorier** [comment]
@nopara73 I notified you on slack though :p I think another chapter on how HiddenWallet is implemented behind the hood would be very useful.

**Comment by Ashish81** [comment]
Nicely documented thanks :), I'd figured the same i had to remove the SpentOutpoints.
this documentation link is below i guess.
[https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html](https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html)

**Comment by Ashish81** [comment]
GetUnspentCoins() return all coins all the time. Confirmed.SpentOutpoints.Concat(Unconfirmed.SpentOutpoints))  is always empty even if i run it in a gap of 15 minutes.

**Comment by NicolasDorier** [comment]
Can you copy paste your code here ?

**Comment by Ashish81** [comment]
Owing to some legacy issue, made a small modification in NBxplorer code
Repository.cs :
```
private void RefillAvailable(DBreeze.Transactions.Transaction tx, DerivationStrategyBase strategy, DerivationFeature derivationFeature)
........
..
 var info = new KeyPathInformation()
                {
                    ScriptPubKey = derivation.ScriptPubKey,
                    Redeem = derivation.Redeem,
                    DerivationStrategy = strategy,
                    Feature = derivationFeature,
                    KeyPath = **new KeyPath(index.ToString())**//DerivationStrategyBase.GetKeyPath(derivationFeature).Derive(index, false)
				};
```
Now the tracking is fine for Keypath = 0,1,2,3,4,5..... so on.
MainController.cs
```
private UTXOChange SetUTXOChange(UTXOStates states, UTXOState substract = null)
		{ 
..........
...........
foreach(var outpoint in states.Actual.SpentUTXOs)
			{
			if(!states.Known.SpentUTXOs.Contains(outpoint) &&
				states.Known.UTXOByOutpoint.ContainsKey(outpoint) &&
			 	!substractedSpent.Contains(outpoint))
					change.SpentOutpoints.Add(outpoint);
			}
			return change;
```
change.SpentOutpoints in above code is never added, UTXOByOutpoint is empty.

my code ....
` var coins =  _Client.GetUTXOs(derivationStrategy, null, true).GetUnspentCoins();`

returns all coins.

Actually i want to bypass the DerivativeFeature limitation , dont want deposit/change line , want to track all line s of the Root extpubkey Stategy, due to some legacy limitation.

**Comment by NicolasDorier** [comment]
> Actually i want to bypass the DerivativeFeature limitation , dont want deposit/change line , want to track all line s of the Root extpubkey Stategy, due to some legacy limitation.

There is uint32.Max lines, so you certainly don't want to track it all.

**Comment by Ashish81** [comment]
Certainly not. 

I want to track 
Keypath(0) keypath(1) ...... So on
Curently nbxplorer tracks 
Keypath(0/0) keypath(0/1) ..keypath(1/0) ..i e second level derivations..
I want to track 1st level derivation of the Root extpubkey

**Comment by NicolasDorier** [comment]
Ah got it. Well in this case just add another feature.

**Comment by Ashish81** [comment]
Ok Thanks, i tried to manage this feature but its more complex for me :( . Waiting for this new feature.

**Comment by NicolasDorier** [comment]
@Ashish81 why do you want to use first level derivation for information ?

**Comment by Ashish81** [comment]
Its just for legacy compatibility. We have already various systems running with complex hierarchical  wallets where first level derived address is widely spread in blockchain and are monitored.

I agree the same can be achieved with second level derivation also but it requires not only the code change but the cumbersome overhead of holding BTC transfers to new wallet address.

We are using several lines ( deposit, change commission , reserve ..) 
Affliate programs where 1st level derivation is used.

**Comment by NicolasDorier** [comment]
I understand for the legacy compatibility. I will think about it.
However, why not using different wallet for deposit/change commission/reserve etc...

**Comment by Ashish81** [comment]
@NicolasDorier  Changing the wallet will change the address ( previous held money need to transfer,, quite ovehead).

Anyhow, I made certain changes and it seems that it solved my problem mostly.
```
public abstract class DerivationStrategyBase
	{
		internal DerivationStrategyBase()
		{

		}

		public DerivationStrategyBase GetLineFor(DerivationFeature derivationFeature)
		{
			return this;
		}

		public abstract DerivationStrategyBase GetLineFor(KeyPath keyPath);

		public Derivation Derive(uint i)
		{
			return Derive(new KeyPath(i));
		}
		public abstract Derivation Derive(KeyPath keyPath);

```
```
namespace NBXplorer.DerivationStrategy
{
...
----
public override Derivation Derive(KeyPath keyPath)
		{
			var pubKey = _Root.ExtPubKey.Derive(keyPath).PubKey;           
                        return new Derivation() { ScriptPubKey = Segwit ? pubKey.WitHash.ScriptPubKey : pubKey.Hash.ScriptPubKey };
		}

		public override DerivationStrategyBase GetLineFor(KeyPath keyPath)
		{
                       return new DirectDerivationStrategy(_Root.ExtPubKey.GetWif(_Root.Network)) { Segwit = Segwit };
              
		}
```

```
private void RefillAvailable(DBreeze.Transactions.Transaction tx, DerivationStrategyBase strategy, DerivationFeature derivationFeature)
		{
...
...
 var info = new KeyPathInformation()
                {
                    ScriptPubKey = derivation.ScriptPubKey,
                    Redeem = derivation.Redeem,
                    DerivationStrategy = strategy,
                    Feature = derivationFeature,
                    KeyPath = new KeyPath(index.ToString())
		};
```


also look the below function
```
private UTXOChange SetUTXOChange(UTXOStates states, UTXOState substract = null)
		{
...
...
foreach(var outpoint in states.Actual.SpentUTXOs)
	{
                if (!states.Known.SpentUTXOs.Contains(outpoint) &&                    
                     states.Known.UTXOByOutpoint.ContainsKey(outpoint) &&
                    !substractedSpent.Contains(outpoint))
                        change.SpentOutpoints.Add(outpoint);
	}
```

It should be negated , i guess, **``` !states.Known.UTXOByOutpoint.ContainsKey(outpoint)``` .**
so that **`change.SpentOutpoints`** is filled. Not sure.

So finally i passed Unit Tests for 1st level derivation, Enum DerivativeFeature is useless in this context.
for the time being it may work i hope,  
 

Thanks

**Comment by NicolasDorier** [comment]
Please pull the last NBXplorer commits. I see some code I removed here.
Anyway, the best is that you make a PR with a new `DerivationFeature` (`DerivationFeature.Direct`), this is not complicated and if I merge it you don't have to maintain your own fork.

**Comment by Ashish81** [comment]
Yes , sure it wd be better, I will try PR n to add direct feature.

**Comment by Ashish81** [comment]
Feature added and merged in master, thanks
