### ISSUE TITLE
i use postgres and newest version of nbxplorer and also newest version of btcpayserver but it show me "no chart" message

### ISSUE THREAD

**Issue by kosuodhmwa** [dgarage/NBXplorer#500]
Hi there :-)

![image](https://github.com/user-attachments/assets/eeccbdc3-164d-4252-be48-27a36f46b356)

Firstly, i was on the wrong github product site so it seems, but more infos HERE: https://github.com/btcpayserver/btcpayserver/issues/6486 

Thank you very very much in advance for your feedback(s)

With best regards
Jan

**Comment by kosuodhmwa** [comment]
FYI: i never used an earlier version that used that built-in, "embedded" other database called "DBTrie" 

![image](https://github.com/user-attachments/assets/b8a2aa8f-4c1e-4f40-803d-980c58ae6293)

**Comment by kosuodhmwa** [comment]
i do not really understand which product i need to start with which parameter (in combination with other parameters or alone`) described on that page here: https://github.com/dgarage/NBXplorer/blob/master/docs/Postgres-Migration.md

**Comment by kosuodhmwa** [comment]
Maybe it's really caused because there are 0 (zero) transactions on my system yet? (in that case, i would see it as a bug)

**Comment by kosuodhmwa** [comment]
https://github.com/dgarage/NBXplorer/issues/498

**Comment by kosuodhmwa** [comment]
Maybe the question is too complex?

**Comment by NicolasDorier** [comment]
hey @kosuodhmwa you need to configure `--explorerpostgres` (or env variable `BTCPAY_EXPLORERPOSTGRES`) with the connection string of NBXplorer.

**Comment by NicolasDorier** [comment]
If you plan to install BTCPay Server manually, please read this doc https://docs.btcpayserver.org/Deployment/ManualDeploymentExtended

**Comment by kosuodhmwa** [comment]
got it :-) 
![image](https://github.com/user-attachments/assets/b13b39eb-51f5-4691-9bda-ac175fb33ea1)
