### ISSUE TITLE
Broadcasting BCH Tx fails with Signature must use SIGHASH_FORKID

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#52]
```csharp
builder.SendEstimatedFees(feeRate);
var tx = builder.BuildTransaction(true);
Assert.True(tester.Client.Broadcast(tx).Success); // <- FAIL
```

This fails with:

> BCH: Transaction 3d13e1a11893ba832319eef1a0c77d397dc8cc7c8c8e7a22dd3c91552c277615 failed to broadcast (Code: RPC_TRANSACTION_REJECTED, Message: Transaction was rejected by network rules, Details: 16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID) )

Please, what could cause this, and how can I resolve this?

The same issue is true with BTG network.

Related:
https://github.com/dgarage/NBXplorer/pull/50

**Comment by NicolasDorier** [comment]
I don't think so, I think the signature process is quite different. I probably need to refactor NBitcoin to allow Network specified signature schemes.

**Comment by bazooka70** [comment]
I was  quite sure there should be another flag `FORKID`.  I tested it and obviously `TransactionBuilder` told me `Script error on input 0 (SigHashType)`.
Sorry, but  I know very little about this issue.

**Comment by NicolasDorier** [comment]
yeah I probably know why

**Comment by NicolasDorier** [comment]
trying to work on a simple solution

**Comment by bazooka70** [comment]
Did you have any luck with issue?

**Comment by NicolasDorier** [comment]
Yes, I started refactoring to make it possible, but still some things to do.

**Comment by NicolasDorier** [comment]
Closing this one.
Basically you need to call `TransactionBuilder.SetConsensusFactory(network)` and it will sign correctly without you having to change your code.

Will update the references soon.

**Comment by NicolasDorier** [comment]
Done, have fun.

**Comment by bazooka70** [comment]
Wow! thanks! I will run some tests asap.

**Comment by bazooka70** [comment]
I have install the latest NuGet packages.
`TransactionBuilder.Verify()` returns false and error:

> Script error on input 0 (SigHashType)

My code:
```csharp
            ...
            builder.SendEstimatedFees(feeRate);
            builder.SetConsensusFactory(network);
            Transaction tx = builder.BuildTransaction(true); // build and sign the transaction

            NBitcoin.Policy.TransactionPolicyError[] errors;
            bool builderVerify = builder.Verify(tx, out errors);
            if (!builderVerify)
            {
                Console.WriteLine($"Error builderVerify!");
                foreach (var e in errors)
                {
                    Console.WriteLine("builder error-> " + e.ToString());
                }                
                Console.ReadKey();
                return;
            }
            // broadcast Tx
           ...
```

I will double check gain...

**Comment by bazooka70** [comment]
OK, I double checked.
The `builder.Verify` returns false and an error as described above, but the transaction `Broadcast` is successful.

**Comment by NicolasDorier** [comment]
updated, it works now

**Comment by bazooka70** [comment]
great news! thanks. can you please answer my question:
Shouldn't the `TransactionBuilder` by default,  always call `SetConsensusFactory()` for any network?

**Comment by NicolasDorier** [comment]
Because if I don't know the specific network you are signing, I can't sign properly.

**Comment by bazooka70** [comment]
Ok, I had the assumption `TransactionBuilder` knows about the network at some point of the build...
