### ISSUE TITLE
Unable to parse IP EndPoint

### ISSUE THREAD

**Issue by sigHash** [dgarage/NBXplorer#54]
I'm trying to point NBXplorer to my own bitcoind (TestNet) endpoint in my docker compose file but it seems like it can't parse http endpoints of the following format:

      NBXPLORER_BTCRPCURL: http://12.24.210.10:18333/

and I keep getting this error:

```
Unhandled Exception: System.FormatException: Invalid IP Endpoint 
at StandardConfiguration.DefaultConfiguration.ConvertToEndpoint(String str, Int32 defaultPort)
 at NBXplorer.Configuration.ExplorerConfiguration.LoadArgs(IConfiguration config)
 at NBXplorer.Program.Main(String[] args) in /source/NBXplorer/Program.cs:line 41
```

**Comment by NicolasDorier** [comment]
ah this is indeed strange. Taking a look.

**Comment by NicolasDorier** [comment]
your issue is not `NBXPLORER_BTCRPCURL` but `NXPLORER_BTCNODEENDPOINT`. This need to be an IP or domain, not a url.

**Comment by sigHash** [comment]
Thank you so much! can't believe I didn't notice that. It's working now
