### ISSUE TITLE
Websocket doesn't track the derive 0/1

### ISSUE THREAD

**Issue by Duanthse03268** [dgarage/NBXplorer#65]
My issue is " i can only listen to the transaction on the address A and cannot listen deposit event on address B". Below is my code, can you take a look on this. And should we make a rest api call back (can retry when call back failed )instead of web socket ?

```
using System;
using NBitcoin;
using NBXplorer;
using NBXplorer.DerivationStrategy;
using NBXplorer.Models;

namespace BitcoinExplore
{
    class Program
    {
        static void Main(string[] args)
        {
            var network = Network.TestNet;
            var xnetwork = new NBXplorerNetworkProvider(NetworkType.Testnet).GetBTC();
            var extPubKey = new BitcoinExtPubKey("tpubD6NzVbkrYhZ4Yb671EeevaGoJ8u7LaMeJJu335AYCfxQqyLD2zvbKFeEwP2ukTFLon3K2WdgoauMiAENa6k4fkjgqNAQTMX2wL2Bsth7Au1", network);

            var client = new ExplorerClient(xnetwork);
            client.WaitServerStarted();
            Console.WriteLine("WaitServerStarted Ok");
            var derivationStrategyOptions = new DerivationStrategyOptions
            {
                Legacy = true // Use non-segwit
            };
            var userDerivationScheme = xnetwork.DerivationStrategyFactory.CreateDirectDerivationStrategy(extPubKey, derivationStrategyOptions);


            var publicAddressa = userDerivationScheme.Derive(new KeyPath("0/0")).ScriptPubKey.GetDestinationAddress(network);
            Console.WriteLine(publicAddressa); // mgXAUj824hjptHRavR9dCRisuuvrzC957Y 
            var publicAddressb = userDerivationScheme.Derive(new KeyPath("0/1")).ScriptPubKey.GetDestinationAddress(network);
            Console.WriteLine(publicAddressb); // mmECiRue3wqanikUEfeJkw6ReA9ZWA7e5U 

            client.Track(userDerivationScheme);
            var events = client.CreateNotificationSession();
            events.ListenAllDerivationSchemes();
            var txEvent = (NewTransactionEvent)events.NextEvent();
            Console.ReadLine();
        }
    }
}
```

**Comment by NicolasDorier** [comment]
@Duanthse03268 I will take a look, but normally you should receive during a deposit. Your code seems OK to me, looking it now.

**Comment by NicolasDorier** [comment]
Ok so I tried with `regtest` (you should use this for your tests, as you can send money and mine easily), and your code worked as expected when I send to the second address.

Are you sure the transaction you sent has enough fee to spread out on the network?

Why do you need reliable http callback? It seems to me that you can get your UTXOs at anytime, so should not care about missing events.

**Comment by Duanthse03268** [comment]
Yes i'm running with that warning and i sure that i send has enough fee. You can try to send to **mmECiRue3wqanikUEfeJkw6ReA9ZWA7e5U**  at network testnet and track on my derive scheme here [](https://testnet.blockchain.info/xpub/tpubD6NzVbkrYhZ4Yb671EeevaGoJ8u7LaMeJJu335AYCfxQqyLD2zvbKFeEwP2ukTFLon3K2WdgoauMiAENa6k4fkjgqNAQTMX2wL2Bsth7Au1) . If i send to **mmECiRue3wqanikUEfeJkw6ReA9ZWA7e5U**  i cannot get NewTransactionEvent.

The reason I need the reliable http call back because i scared the failed delivery notification and it can retry to call again in some amount of time like blockcypher webhook or coinbase payment services.

**Comment by NicolasDorier** [comment]
Can you give me your `tpub`?

**Comment by NicolasDorier** [comment]
ah sorry there is. Checking now.

**Comment by NicolasDorier** [comment]
Can you send some coins on mmECiRue3wqanikUEfeJkw6ReA9ZWA7e5U ?

**Comment by NicolasDorier** [comment]
If your transaction show on https://test2-btc-ltc.forkbitpay.ninja/invoices/Y4dwH58H73veAJ3t7md8fF then the event fired.

**Comment by Duanthse03268** [comment]
Ok i got this. But can you take a look on my request we use http request instead of web socket ?

**Comment by NicolasDorier** [comment]
What was your issue? Because your code was right, how did you fixed your problem?

For HTTP Requests, I am not opposed to it, but I don't have time to do it, so feel free to make a PR.

That said, again, I highly advise you against doing this. Using a websocket to get immediate notifications, and use polling on transactions by using the bookmark feature will make your code way more reliable.

**Comment by Duanthse03268** [comment]
Yes. I haven't figured out why i got this issue but today, i receive NewTransactionEvent. I will make a PR for a call back via http request thank you.

**Comment by NicolasDorier** [comment]
@Duanthse03268 I am almost sure that your issue was that the node was not sending the transaction due to the fact you are not whitelisted by your own node. Follow what the warning is telling you.

**Comment by Duanthse03268** [comment]
Another question: I have to run Full Node LTC, BTC, DASH ... to listen NewTransactionEvent of each coin right ?

**Comment by NicolasDorier** [comment]
No, be careful this is not `44/0/0` but `44'/0'/0'`. Note the prime is important.
NBXplorer has not idea about BIP44, it just takes the derivation scheme as is and derive `0/x` and `1/x` on top of it.

Read https://programmingblockchain.gitbooks.io/programmingblockchain/content/ for more detail about BIP32.
