### ISSUE TITLE
NBXplorer vs NBitcoin Indexer

### ISSUE THREAD

**Issue by ArtjomP** [dgarage/NBXplorer#66]
Hello there!
I'm creating my HD Wallet software with BIP44 support. I want to get balances of the derived addresses, transactions etc.
And I'm a little bit confused what is the best choice for me.
I think that NBitcoin Indexer is cheaper & scalable because it uses Azure Table Page Blob & with NBXplorer I need to use VPS with 160 GB HDD (for BTC core) for every scale unit.
But NBXplorer has pretty good REST interface.
Is it correct? 
What it the best choice in my case?

**Comment by NicolasDorier** [comment]
Nop, NBXplorer is cheaper. It stores only what you are tracking.

Use NBXplorer, there is zero reason to use NBitcoin.Indexer for your case.

**Comment by ArtjomP** [comment]
Thank you!
I'm trying 👍
