### ISSUE TITLE
Can't get new address

### ISSUE THREAD

**Issue by ArtjomP** [dgarage/NBXplorer#69]
Hello.
I have a full btc node & NBXplorer on it. I can't track my assets & even get new unused address.

`curl http://myserver.com:24444/v1/cryptos/BTC/derivations/xpub661MyMwAqRbcGkRerxKpAbcfU45DMAuLvubnWbPhkvGHJ6JRH5auB7NrKGRhq1zc6pM8ExYjvJj8vLboigBVpMiL7WqEFHDRfUzVKMxv3WQ-[legacy]/addresses/unused -v -g`

and get
`
{"httpCode":404,"code":"strategy-not-found","message":"This strategy is not tracked, or you tried to skip too much unused addresses"}
`
What did I do wrong?

**Comment by NicolasDorier** [comment]
You need to [Track](https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#track-a-derivation-scheme) first.

**Comment by NicolasDorier** [comment]
Can I close this?
