### ISSUE TITLE
fail: Configuration: BTC: RPC connection settings not configured

### ISSUE THREAD

**Issue by songproducer** [dgarage/NBXplorer#7]
Not sure what flags I should be using on bitcoind if any. Trying to get btcpay running.

**Comment by NicolasDorier** [comment]
Start `bitcoind` with default parameter, then run NBXplorer with default parameter.

**Comment by NicolasDorier** [comment]
this one show you how to host manually btc+ltc https://www.youtube.com/watch?v=liOUTqBUi_g

**Comment by songproducer** [comment]
I need to use this flag because the blockchain is so huge:
` -datadir=/media/6tb/.bitcoin/ `

I think this is affecting the RPC setting somehow?

**Comment by NicolasDorier** [comment]
yes use `--btcrpccookiefile` to configure nbxplorer to use different cookiefile.

**Comment by songproducer** [comment]
Passing btcrpcuser and btcrpcpassword also worked
