### ISSUE TITLE
Question: How to send a raw transaction with NBXplorer?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#71]
I want to send a **raw signed** transaction using NBXplorer. Is it possible?
I could have sworn there was an `RPC` property for `ExplorerClient`. but now I can't seem to find one?

When I tried:

```
NBitcoin.Transaction tx = new NBitcoin.Transaction(rawTransaction);
Client.Broadcast(tx);
```

I get a warning "You should instantiate Transaction from ConsensusFactory.CreateTransaction".

So I was thinking e.g.:

```
var factory = new ConsensusFactory();
var tx = factory.CreateTransaction();
// var tx = network.Consensus.ConsensusFactory.CreateTransaction(); // or this???
tx.FromBytes(NBitcoin.DataEncoders.Encoders.Hex.DecodeData(rawTransaction));                
BroadcastResult result = client.Broadcast(tx);
```
But I'm not sure.
What is the right way to send a raw TX via NBXplorer? please advice. Thanks!

**Comment by NicolasDorier** [comment]
Best is to use

```
var tx = Transaction.Create(network);
tx.ReadWrite(rawTransaction); // Assuming rawTransaction are bytes, instead convert to byte with Encoders.Hex
client.Broadcast(tx);
```

This ensure your code write for all shitcoins.

**Comment by bazooka70** [comment]
@NicolasDorier , There is no `Transaction.Create()` method. is this something new?

**Comment by NicolasDorier** [comment]
no `RPCClient` is not known by the client.

**Comment by bazooka70** [comment]
I thought it would make sense to query the node in RPC directly from the NBXplorer client -> NBXplorer server. which usually sits with the node core on the same server and already configured to "talk" to the node in RPC.

**Comment by NicolasDorier** [comment]
the RPC generally sit behind the server and the client does not have network access to it.

The broadcast of nbxplorer is broadcasting to the rpcclient so being direct allow more.
