### ISSUE TITLE
Tracking addresses that already have balance?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#73]
Hi @NicolasDorier , I am now facing a very hard issue. We stared working with Trezor wallets. the Trezor gives us an XPUB-key, and I register it with NBXplorer via `client.Track()`. All is well. 

The problem is with Trezor devices that already have balance **before** the `Track()` was called. 
No Balance and no transactions are returned.

Is there any way to re-sync the XPUB-key so that NBXplorer can give me the correct details for an address that had already a balance/transactions?

I know this is not the way NBXplorer suppose to work. but I really hate to switch to QBitNinja or other external indexers. (That is a real pain since the Trezor is an HD wallet and each wallet has multiple address).

Is there anything could be done?

**Comment by NicolasDorier** [comment]
Yes, NBXplorer does not scan anything from the before it was first run.

You can ask for rescan with `--btcrescan=1` and `--btcstartheight=x` or something like this. Check with `--help`.

That said it can take a while.

**Comment by bazooka70** [comment]
Yes, But even if that works I need to restart NBXplorer :/
Is this could be done (in theory) while the NBXplorer is running?

**Comment by NicolasDorier** [comment]
If you use an external block explorer to fetch the UTXOs of newly tracked address, it would works fine while running.

**Comment by bazooka70** [comment]
Can you please explain what you mean?

**Comment by bazooka70** [comment]
I need to digest what you just said... 
I presume you expect a PR? :-p

**Comment by NicolasDorier** [comment]
yes. You can hard code qbitninja for now if you want, I will cleanup later.

**Comment by bazooka70** [comment]
I still need to get my shit together with QBitNinja (or other block explorer maybe?). 
The Trezor wallets are HD, and it allows segwit addresses. getting all the transactions seems to be very slow with QBitNinja. I need to run more tests. *sigh*

Another options (I think) might be to create a route that will only insert the data into the Repository for such situation, so the block explorer could be external and not hard-coded into NBXplorer... maybe.

**Comment by NicolasDorier** [comment]
> Another options (I think) might be to create a route that will only insert the data into the Repository for such situation, so the block explorer could be external and not hard-coded into NBXplorer... maybe.

You are right this would be way better.

**Comment by NicolasDorier** [comment]
Getting all transactions should not be that slow if you parallelize properly with Tasks. Also it is one time operation.

**Comment by bazooka70** [comment]
Can please give me some leads as where to start? what table(s) should be updates? etc...

**Comment by NicolasDorier** [comment]
`Repository.SaveMatches` add entries to a derivationSchemes.
`Repository.SaveTransactions` saves transaction for querying from `/v1/cryptoCode/transactions`.

**Comment by Duanthse03268** [comment]
How can site blockchain.info can query my balance of xpub so fast like https://testnet.blockchain.info/xpub/tpubD6NzVbkrYhZ4Yb671EeevaGoJ8u7LaMeJJu335AYCfxQqyLD2zvbKFeEwP2ukTFLon3K2WdgoauMiAENa6k4fkjgqNAQTMX2wL2Bsth7Au1

**Comment by bazooka70** [comment]
@NicolasDorier, Do I need to call both methods to add new transactions for  a derivationScheme?
i.e. `Repository.SaveMatches` and `Repository.SaveTransactions`?

For now I use `blockchain.info` api (note it can accept multiple addresses separated with `|`):

The xbub is `xpub6DKPnAVbc1U6pD1zK8ybqimWWgLaEoqrCAsW3ykf7E7dRmvvDUT9Q4XR2zH38hnT6vQVHDfgLP3Lo2PsmdSMrr9MBbgoBPMujmRVaa1pC1L`

and the addresses are Segwit/P2SH. so I derived all addresses which has Txs (deposit and change).

https://blockchain.info/multiaddr?active=3MfGRBJhiAj55TD8JFYQZR1j7pb7T9Qyb9|3FrsCFirSaY1BfirLb747bz5wBz5yz9N2C

But, I seem to be totally lost at how to proceed from now and what to pass to these methods :/
Can you please assist?

**Comment by NicolasDorier** [comment]
I advise you to not use `blockchain.info` but `smartbit.com.au` blockchain info is a rotten company.

Yes you have to pass both. Both method tell you what to pass argument, what part you don't understand?

**Comment by bazooka70** [comment]
For start I'm not sure what is the **difference** between the two methods. 
And I don't understand why the `blockHash` should be passed as common to the `transactions[]`:

`Repository.SaveTransactions(DateTimeOffset now, NBitcoin.Transaction[] transactions, uint256 blockHash)`

Shouldn't each transaction in the array has its own `blockHash`?

**Comment by NicolasDorier** [comment]
`Repository.SaveTransactions` has been made for fast processing, and in current usage, a block get scanned and maybe 5 transactions need to be indexed. So I pass those 5 transactions with the block hash they belongs to.

In your case, most likely the transactions will be in different blocks. Which mean you would call `Reposiotry.SaveTransactions` once per transaction.

**Comment by bazooka70** [comment]
Thanks. And what is the `Repository.SaveMatches` used for?

**Comment by NicolasDorier** [comment]
SaveTransactions will make sure that call to [get-a-transaction](https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#get-a-transaction) works.

SaveMatches will make sure that [get-derivationScheme-transactions or get utxos](https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#query-transactions) works.

Save matches is basically a way to say to save the fact that a transaction with input a/b/c and output a/b/c belongs to a particular derivationScheme.

**Comment by NicolasDorier** [comment]
(Also, smartbit is using NBitcoin under the hood 😎 )

**Comment by NicolasDorier** [comment]
Don't forget, that you can make unit tests quite easily. Take example on the other tests. It is very useful for debugging.

**Comment by bazooka70** [comment]
BTW, Seems I spoke too soon about smartbit.com.au :(
Too many connection time-outs with their API... not good.

**Comment by NicolasDorier** [comment]
And api.qbit.ninja ?

**Comment by bazooka70** [comment]
I haven't noticed time-outs with api.qbit.ninja
But it is rather slow in  general as I already mentioned,

I'm am initially querying at-least 40 addresses (20 deposit  + 20 change) to determine which addresses has txs. while there is a certain gap I continue to query the next 20/20 addresses etc... 

both blockchain.info and smartbits allow me to query multiple address at once. they even allow to query an xpub address, but they only handle legacy address (not segwit/p2pkh) which is no use to me.

So, I'm not sure (not tested) how api.qbit.ninja will handle so many requests in parallel.
blockchain.info already returning "429 Too Many Requests" error. so I think game is over for blockchain.info :/

and smartbit (which has a super great api) works verrrryyy slow with connection time outs.
So, I'm still not even at the NBXplorer code yet.

My plan was to pass array of Transactions (serialized as hex) to the NBXplorer), then for each tx  query block hash via RPC given the block height (if any), and produce the matches. then call both methods, but I'm not there yet...

**Comment by NicolasDorier** [comment]
I think you should not care about it being slow. This is after all a one-time operation when the user is restoring a wallet.

**Comment by bazooka70** [comment]
a query of 20 addresses with QBitNinjaClient in **parallel**  takes about 10-15 sec in avg. but I had requests that took more than 1 min to return. Do you think this is a resalable time for the user to get a response when the user first restoring a wallet?

My strategy now is to pass only the Tx Ids array, for the xpubkey.
In the NBXplorer server side call the RCP `hex_tx=getrawtransaction` for each tx.  and instantiate each transaction with `NBitcoin.Transaction.Parse(hex_tx)`.

What do you think?

**Comment by NicolasDorier** [comment]
How do you get those Tx Ids? If you have Tx Ids from a public explorer, what not fetching the whole transaction? `txindex` sucks, as your node can't be pruned, and will take lot's of disk space.

**Comment by bazooka70** [comment]
Yes, I get the Tx Ids from a public explorer (several of them actually). I could swear `txindex=1` was one of the prerequisite for NBXplorer and my nodes are all configured with `txindex`. I don't think disk space should be an issue here.

I would really want to have that option where I pass only Tx ids, and let NBXplorer get all info needed directly from the node including the block height/hash.

There could be another method that won't depend on `txindex` which will require an array of `Transaction` as input, with the corresponding block hashes.

This is what I have so far (not tested yet):

```csharp

[HttpGet]
[Route("cryptos/{cryptoCode}/derivations/{strategy}/transactions/savetxids")] 
public async Task<IActionResult> SaveTransactionsIds(string cryptoCode,
	[ModelBinder(BinderType = typeof(DestinationModelBinder))]
	DerivationStrategyBase strategy,
	[ModelBinder(BinderType = typeof(UInts256ModelBinding))]
	HashSet<uint256> txIds)
{
	var network = GetNetwork(cryptoCode);
	var waiter = Waiters.GetWaiter(network);
	if (!waiter.RPCAvailable)
		throw RPCUnavailable();

	var repo = RepositoryProvider.GetRepository(network);
	var now = DateTimeOffset.UtcNow;
	foreach (var txid in txIds)
	{
		var txInfo = await waiter.RPC.GetRawTransactionInfoAsync(txid);
		if (txInfo != null)
		{
			var blockHash = txInfo.BlockHash;
			repo.SaveTransactions(now, new Transaction[] { txInfo.Transaction }, blockHash);
			var txMatches = repo.GetMatches(txInfo.Transaction);
			List<MatchedTransaction> matchedTxs = new List<MatchedTransaction>();					
			foreach (var txMatch in txMatches)
			{
				matchedTxs.Add(new MatchedTransaction() { BlockId = blockHash, Match = txMatch } );
			}
			repo.SaveMatches(now, matchedTxs.ToArray());
		}
	}
	return Ok();
}

```

**Comment by bazooka70** [comment]
Tested and this seems to work like a charm! man you a genius!

**Comment by NicolasDorier** [comment]
@bazooka70 no you don't have to check.

```
List<MatchedTransaction> matchedTxs = new List<MatchedTransaction>();					
			foreach (var txMatch in txMatches)
			{
				matchedTxs.Add(new MatchedTransaction() { BlockId = blockHash, Match = txMatch } );
			}
repo.SaveMatches(now, matchedTxs.ToArray());
```

Can be replaced in one readable line :

```
repo.SaveMatches(now, .Select(t=> new MatchedTransaction() { BlockId = blockHash, Match = txMatch } ).ToArray());
```

I think this is a good idea to rely on txindex. After all, if txindex is off, then we don't support this. I think this is OK.

**Comment by bazooka70** [comment]
PR:
https://github.com/dgarage/NBXplorer/pull/80
