### ISSUE TITLE
How to create a transaction? Can't get it verified

### ISSUE THREAD

**Issue by ArtjomP** [dgarage/NBXplorer#76]
I've got some unspentCoins to different addresses some to Root ExtPubKey and some to derived ExtPubKeys.
Now I want to spend it and can't verify the transaction. 
My code looks like this:
```cs
var privateKeys = new List<ExtKey>();
var rootPrivateKey = GetRootPubKey(...);
var extRootPubKey = privateKey.Neuter();

privateKeys.Add(extRootPubKey);

var unused = await nbxplorer.GetUnusedAsync(userDerivationScheme, DerivationFeature.Deposit);
var maxUnusedNumber = unused.KeyPath.Indexes.Max();
for (UInt32 i = 0; i <= maxUnusedNumber ; i++)
{
  extPrivateKeys.Add(privateKey.Derive(i));
}

var changeAddress = await = nbxplorer.GetUnusedAsync(userDerivationScheme, DerivationFeature.Change);

var builder = new TransactionBuilder();
builder = builder
                    .AddCoins(unspentCoins)
                    .AddKeys(extPrivateKeys.ToArray())
                    .Send(destinationPubKey, amountMoney);
                    .SetChange(changeAddress)
                    .SendFees(new Money(fee, MoneyUnit.BTC))
                    .BuildTransaction(true);

verified = builder.Verify(tx);
// unfortunately verified is false
```

What did I do wrong?

Thank you in advance.

**Comment by ArtjomP** [comment]
It seems I can't mix coins from the RootKey with the Derived and I should do it something like this:

`
var coins = utxos.GetUnspentCoins();
var keys = utxos.GetKeys(userExtKey);
`

Is it correct?

**Comment by NicolasDorier** [comment]
If you use `nxplorer.GetUTXOs` NBXplorer gives you the keypaths you need to use for spending each coin it returns.

[Can see an example here](https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html).

`var keys = utxos.GetKeys(userExtKey);` basically read those KeyPath and derive `userExtKey` to extract all the keys required to sign.

**Comment by ArtjomP** [comment]
Thank you the example works well. 
I mixed the example with root userExtKey something like this:
```cs
var coins = utxos.GetUnspentCoins();
var keys = utxos.GetKeys(userExtKey);

coins.Add(GetCoinsFromRootUserKey_With_QBitNinjaClient(...));
keys.Add(rootUserKey);

```

And it works!!!

Thank you!
Cheer up!

**Comment by NicolasDorier** [comment]
Great, normally you never send money from `rootUserKey` though, so you don't need any external dependency to QBitNinja.

**Comment by ArtjomP** [comment]
Yes it's correct. But I created a wallet with sending & receiving to root key only and now I want to migrate it to BIP44 without loosing existing assets.

Thank you again.

**Comment by ArtjomP** [comment]
And one more question if you don't mind.
You always use ScriptPubKey for change address & send to address. 
I use BitcoinAddress itself.

What is the right way?

**Comment by ArtjomP** [comment]
What is the difference? As far as I got it from your book it's the same.
Is it correct?

**Comment by NicolasDorier** [comment]
You can use BitcoinAddress or ScriptPubKey this is fine.

BitcoinAddress implement `IDestination` interface, which mean it can be converted into `ScriptPubKey`.

I think passing the BitcoinAddress is more readable, both are the same.

**Comment by sixjac** [comment]
Having issues getting a transaction verified also, error message 👍 
non-mandatory-script-verify-flag (Witness program hash mismatch) (code 64)

Could not find direct answer with code 64 on Google, code below looks ok to me:

    UTXOChanges utxos = NBXClient.GetUTXOs(NBXTrackingStrategy);

    if (utxos != null)
    {
        double spendable = GetCalculatedBalance(true);

         if (spendable >= amount)
         {
              var unspent = utxos.GetUnspentCoins(true);
              var sendAddr = BitcoinAddress.Create(address, NBXNetwork.NBitcoinNetwork);
              Key[] keys = utxos.GetKeys(sfe.ExtKey, true);

               FeeRate fallbackFeeRate = new FeeRate(Money.Satoshis(decimal.Parse(feesats.ToString())));
               Money sendAmount = Money.FromUnit(decimal.Parse(amount.ToString()), MoneyUnit.BTC);

               ConsensusFactory factory = new ConsensusFactory();
               TransactionBuilder builder = factory.CreateTransactionBuilder();
               Transaction tx = builder.AddCoins(unspent)
                .AddKeys(keys)
                .Send(sendAddr.ScriptPubKey, sendAmount)                                                   
  .SetChange(NBXTrackingStrategy.Root.PubKey.GetAddress(NBXNetwork.NBitcoinNetwork))
                .SendEstimatedFees(EstimateFees(1, fallbackFeeRate).FeeRate) // FallbackFee == 0.0001 sats
                .BuildTransaction(true);

                 bool verified = builder.Verify(tx); // FALSE

                  BroadcastResult result = NBXClient.BroadcastAsync(tx).GetAwaiter().GetResult();  
                 //  RPC_TRANSACTION_REJECTED

                  if (result.Success)
                  {
                       return true;
                   }
                   else if (result.RPCCode.HasValue && result.RPCCode.Value == RPCErrorCode.RPC_TRANSACTION_REJECTED)
                    {
                          goto failed;
                    }
                    else
                    {
                           goto failed;
                     }
               }
          }

Thanks in advance

**Comment by NicolasDorier** [comment]
Take a look at [this test](https://github.com/dgarage/NBXplorer/blob/master/NBXplorer.Tests/UnitTest1.cs#L215) to see how you are meant to use NBXplorer.

**Comment by sixjac** [comment]
@NicolasDorier thanks but I do not want to send my change back to a new unused address, I want it to go back to a pre existing receive address already generated by GetUnused.....

Thanks

**Comment by sixjac** [comment]
Fixed the issue, forgot to Neuter the ExtKey ;) derp

Thanks
