### ISSUE TITLE
fail: Configuration: BTC:Error connecting to RPC server

### ISSUE THREAD

**Issue by JorgeOrtegaHdz** [dgarage/NBXplorer#77]
I did all for run the application but it didn't work. The error is:
fail: Configuration: BTC:Error connecting to RPC server: An error ocurred while sending the request. The server returned an invalid or unrecognized response.

In my computer i have the btc core but isn't full, Would the application work anyway?

**Comment by NicolasDorier** [comment]
You run `bitcoind` (command line) or `bitcoin-qt` (user interface) ?

**Comment by JorgeOrtegaHdz** [comment]
yes i ran it:
      bitcoin-qt -bind=192.168.0.5 -port=8332
and
     ./run.ps1 -btcrpccookiefile C:\bitcoin\.cookie --port 8333
for configure the url to connect bitcoin core i wrote the senttings.config

**Comment by NicolasDorier** [comment]
if you use `bitcoin-qt` you need to add `-server=1`

**Comment by JorgeOrtegaHdz** [comment]
Yes, i ran it like:
    bitcoin-qt -bind=192.168.0.5 -port=8332
and
    ./run.ps1 --btcrpccookiefile C:\bitcoin\.cookie --port 8333
I wrote in the senttings.config file the url: btc.rpc.url=http://192.168.0.5:8332/
but it haven't worked.

**Comment by JorgeOrtegaHdz** [comment]
I ran the command:
    bitcoin-qt -bind=192.168.0.5 -port=8332 -server=1
but the application haven't worked and the error is the same

**Comment by NicolasDorier** [comment]
Can you run `bitcoind.exe` instead?

**Comment by JorgeOrtegaHdz** [comment]
yes, I did, but it doesn’t work. I tried communication with other BTC core, but the problem is the same.
I tried with 187.190.137.200:8333

**Comment by NicolasDorier** [comment]
port and bind are not for RPC connection but for P2P connection. YOu need to use `rpcport`.

**Comment by NicolasDorier** [comment]
I never tried with 0.17.0 but should be correct. I can't tell you why it goes like that.
I can only tell you that if you start both with `-regtest`, no parameter, empty config file. It should just work.

Maybe another process is listening the same port or I don't know.

**Comment by mstijak** [comment]
My node is configured to use non-default data directory. Setting the correct btc.rpc.cookiefile did the trick.
