### ISSUE TITLE
Connection with server could not be established

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#78]
Hi, I cannot seem to use NBXClient, getting a connection error exception:

System.Net.Http.HttpRequestException
  HResult=0x80072EFD
  Message=An error occurred while sending the request.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.HttpClientHandler.<SendAsync>d__111.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NBXplorer.ExplorerClient.<SendAsync>d__58`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NBXplorer.ExplorerClient.GetStatus(CancellationToken cancellation)
   at BTCLib.BTCCore.<ReceiveTransactions>d__12.MoveNext() in D:\InterkrankProjects\crypto-wallets\UWP\BitcoinWallet\btclib\BTCLib\BTCCore.cs:line 96

Inner Exception 1:
COMException: The text associated with this error code could not be found.

A connection with the server could not be established

I am using this in my wallet app NuGet version I cannot seem to find ordinary class documentation on how things work, I do not want to connect to the full bitcoin core and I do not want to use QBitNinja, how can I just get transaction information via the tracking strategy from the PubExtKey?

Do I connect to somewhere specific?

Thanks

**Comment by NicolasDorier** [comment]
Are you running a https://github.com/dgarage/NBXplorer server with bitcoin core synched?

**Comment by sixjac** [comment]
I have bitcoin core synced on an external drive, i have no nbxplorer server, where is it? Do i have to setup my own? With what method do i connect?

Some specific pointers or guide would be appreciated.

Sent from BlueMail<http://www.bluemail.me/r?b=13187>
On 30 Jul. 2018, at 4:56 am, Nicolas Dorier <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you running a https://github.com/dgarage/NBXplorer server with bitcoin core synched?

**Comment by NicolasDorier** [comment]
Yes you have to run it, please use the README, then just use `NBXplorer.Client` and it will connect.

**Comment by sixjac** [comment]
Ah so the readme is the server setup, ok ill give it a try. Cheers

Sent from BlueMail<http://www.bluemail.me/r?b=13187>
On 30 Jul. 2018, at 4:56 am, Nicolas Dorier <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you running a https://github.com/dgarage/NBXplorer server with bitcoin core synched?

**Comment by sixjac** [comment]
I want to mass distribute a wallet that has nbxplorer to get transaction information,  it is good for this use case yes?

Sent from BlueMail<http://www.bluemail.me/r?b=13187>
On 30 Jul. 2018, at 6:45 am, Nicolas Dorier <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes you have to run it, please use the README, then just use NBXplorer.Client and it will connect.

**Comment by sixjac** [comment]
Not wanting to pay for hosting I guess a network connected machine running an nginx server running bitcoin core and NBXplorer would be a good alternative?

**Comment by NicolasDorier** [comment]
Just run both locally and connect to it.

**Comment by sixjac** [comment]
I need it on a server , ie: someone from india as an example needs to use the wallet to send/receive transactions.

Sent from BlueMail<http://www.bluemail.me/r?b=13187>
On 30 Jul. 2018, at 9:38 am, Nicolas Dorier <notifications@github.com<mailto:notifications@github.com>> wrote:

Just run both locally and connect to it.

**Comment by sixjac** [comment]
Ok but there does not seem to be another option , I cannot have users install bitcoin core on their mobile as an example, lol. Cheers

**Comment by NicolasDorier** [comment]
Yeah, I can make a mode to block dangerous API call in public.

**Comment by sixjac** [comment]
Sorry what do you exactly mean? Yeah, I can make a mode to block dangerous API call in public.??

**Comment by sixjac** [comment]
"Yeah, I can make a mode to block dangerous API call in public." Can you please do this and push update to NuGet?

**Comment by NicolasDorier** [comment]
I don't have time to work on it, feel free to do it.

**Comment by sixjac** [comment]
Ok any idea where to start and how long it should take?

**Comment by NicolasDorier** [comment]
if it was me, less than an hour. For you, depends how fast you can analyze the codebase, which depends on your experience.

**Comment by sixjac** [comment]
7 years C++ / C# developer mainly in games and interactive entertainment, blockchain still quite new 6-12 months

**Comment by NicolasDorier** [comment]
You don't need crypto currency knowledge to make that work. You just need to add an additional option flag says (`--public`) which, if true, you disable some controller routes leaking privacy.

**Comment by NicolasDorier** [comment]
The routes you should disable are

https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#get-extpubkey-from-scriptpubkey

https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#notifications-via-websocket subscribetransactions for empty `derivationSchemes` array.

And https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#get-a-transaction

**Comment by sixjac** [comment]
Thanks so you just mean comment out thise particular methods is --public is true?

**Comment by NicolasDorier** [comment]
Rejecting calls to those methods if --public is true.

**Comment by sixjac** [comment]
Is this compatible with a lightning network node instead of plain bitcoin core?

**Comment by NicolasDorier** [comment]
NBXplorer is for on chain transaction only

**Comment by sixjac** [comment]
Yes i gathered that but it reads from Bitcoin Core chain correct? So can it read from lightning network chain?
