### ISSUE TITLE
Info : BTC mining source

### ISSUE THREAD

**Issue by Ashish81** [dgarage/NBXplorer#8]
Do you intend to code for mining CPU/GPU or suggest any ???

**Comment by nopara73** [comment]
I doubt it makes sense, but for reference I leave here this recent Java miner implementation: https://github.com/guerrerocarlos/bitcoin-miner

**Comment by Ashish81** [comment]
Thx , but doesnt there any c# implementation, basucally i want to achieve the following

To pick a particular transaction n confirm it which is due unconfirmed for several days.

**Comment by nopara73** [comment]
> Is it possible to ??

It's not. You may want to use Child Pay For Parents. Check out this article: [A Practical Guide To Accidental Low Fee Transactions](https://hackernoon.com/holy-cow-i-sent-a-bitcoin-transaction-with-too-low-fees-are-my-coins-lost-forever-7a865e2e45ba)

**Comment by NicolasDorier** [comment]
why is it relevent to NBxplorer?

**Comment by Ashish81** [comment]
Irrelevent.
