### ISSUE TITLE
Using ExplorerClient without having access to the underlying filesystem 

### ISSUE THREAD

**Issue by sigHash** [dgarage/NBXplorer#81]
Hi! I am trying to use the ExplorerClient on a VM without having access to the underlying file system and I am getting this error while initializing the client:

```
Could not find suitable datadir: DirectoryNotFoundException
at StandardConfiguration.DefaultDataDirectory.GetDirectory(String appDirectory, String subDirectory, Boolean createIfNotExists)
at NBXplorer.NBXplorerDefaultSettings..cctor()
```

Is there any way around this?
Thanks.

**Comment by NicolasDorier** [comment]
Have you updated the package to the latest version? It was a bug before that I fixed normally.

**Comment by sigHash** [comment]
I'm using NBXplorer.Client 1.0.2.15.

**Comment by NicolasDorier** [comment]
Ok this is strange, can you check that you run `NicolasDorier.StandardConfiguration` 1.0.0.16?

**Comment by NicolasDorier** [comment]
AH I found the bug, fixing it.

**Comment by sigHash** [comment]
Yeah, it's 1.0.0.16. Thank you!

**Comment by NicolasDorier** [comment]
NBXplorerClient 1.0.2.16  should fix the bug, it should be available under 10 min on nuget, let me know.

**Comment by sigHash** [comment]
It's working like a charm! Thank you for taking the time to fix it 👍
