### ISSUE TITLE
Feeding NBXplorer notifications to RabbitMQ

### ISSUE THREAD

**Issue by sigHash** [dgarage/NBXplorer#85]
Hi! I am building a worker (.net core console) that uses NBXplorer.Client to listen for NBXplorer notifications, process each event and send them over to RabbitMQ.  

Should I be worried about buffering those events while I am processing them, or the client will take care of that for me? The assumption is that I'm subscribing to thousands of newTransaction and NewBlock events. 

Thanks!

**Comment by NicolasDorier** [comment]
Are you sure you will process that much? Because it sends events only for transactions which match a xpub.

I don't know how buffering work as far as websocket are concerned. You would have to try and see what happen if events keep coming but the consumer does not process them.

**Comment by NicolasDorier** [comment]
Problably a better solution for you might be to change NBXplorer to publish notifications on RabbitMQ directly.

**Comment by NicolasDorier** [comment]
Well I am thinking merging it on this repo. 

Create a HostedService which listen the proper events on the Event Aggregator and forward it to RabbitMQ. (It is quite easy, check what I did for websocket in the MainController)

It is probably easier than websocket.

**Comment by sigHash** [comment]
Got it! Just checked the code on [Route("cryptos/{cryptoCode}/connect")].

Now I'm thinking if we have multiple instances of NBXplorer, we'll end up with many duplicate messages in RabbitMQ.

**Comment by chriswhellams** [comment]
Great idea. It would be really nice if this could be done either with AMQP 1.0 or as a generic interface that would allow others to extend. Reasons:

1. AMQP 1.0 is also supported by e.g. Azure Service Bus and is a standard. Negative - RabbitMQ is based on AMQP 0.9.1 and requires a plugin for AMQP 1.0 . https://www.rabbitmq.com/protocols.html

2. (And / or )abstract implementation with an interface , allowing others to add support for other brokers such as ZeroMq, Azure service bus, MQTT etc . 

@sigHash  you might know this already - but bitcoind already has ZeroMQ support  https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md but lacks the nice filtering in NBXplorer.

**Comment by sigHash** [comment]
@chriswhellams I agree. WS doesn't work for us either. De-duplication is a real issue if new messages trigger expensive updates, but you are right; It's a separate layer and I am not too worried about it because you can flush em out.

I'll create the HostedService and cout events for now. You can then use your cloud provider SDKs to send them wherever you want.

By the way, you might also be interested in [this](https://github.com/dgarage/NBXplorer/issues/82). Trying to allocate time to do it.

**Comment by NicolasDorier** [comment]
I am quite qgainst deduplication, it complicates the design while right now multiple instance of NBXplorer is not supported.

By experience, it is way more scalable and easy to design consumers to process messages in an idempotent way.

**Comment by NicolasDorier** [comment]
Except if the queue provider can take care of de-duplication. On azure for example messages can have an ID that azure will use to remove dups.

**Comment by chriswhellams** [comment]
@NicolasDorier I have implemented an IHostedService for Azure Service Bus following BitcoinDWaiter and MainController::ConnectWebSocket examples. I added my hosted service in Startup as a Singleton and used the unit tests to do some initial testing . The EventAggregator works fine and my code gets called. Great ! But - when I try to push a message to the Azure service bus it doesn't work - the Msft library is async so I do an `await myqueue.SendAsync(message)` - but the code immediately exits and returns up the call tree - also weird is that if I put a `try..catch` around it I get no error. I have no problem sending to my queue from a clean console app - so  my machine can talk to the queue in Azure.

I noticed you are using AutoResetEvents in BitcoinDWaiter - I'm not familiar with using those and have not used them in my HostedService - but I am wondering if this is some kind of threading issue. I can push code to my clone of the repo for you to look at tomorrow, but just wondering if you have any initial thoughts or suggestions ? 

Also - where would you prefer config settings for this to go ? Thnx

**Comment by NicolasDorier** [comment]
You don't need to touch the `AutoResetEvent` stuff, this is a code smell I need to fix and that is only needed for a particular purpose of my code.

I don't know, `await myqueue.SendAsync(message)` seems to be what need to be done. Maybe a bug in their lib?

**Comment by chriswhellams** [comment]
@NicolasDorier thanks for the info - I found the issue, just a simple scoping / timing issue in the end. As the unit test is running in its own thread it was already exiting before the EventAggregator had bubbled the call up to my HostedService - so the service was starting to shutdown ! 

I have a few more questions - maybe you can answer here or take offline to email if you prefer - this is assuming you are happy to take this feature as a PR. 

Where would you like the configuration for Azure Service Bus to go ?  This feature will need an on/off switch, the connection string and queue names.

Unit testing is rather challenging as it requires either an Azure subscription or there is a downloadable emulator of some sort - but maybe more trouble than its worth. Or then it will need mocking...or no unit test.

**Comment by NicolasDorier** [comment]
@chriswhellams just create a class "TestConfig.cs" with a const having the connection string to the Azure namespace/queue. Set it as empty when you commit. And make sure the test fails with "Please set TestConfig.AzureQueueConnectionString" or something like this.

Please simplify, and do not allow the user to configure queues individually. Just ask them to input the namespace connection string.

**Comment by chriswhellams** [comment]
ok, will do. What about config in NBXplorer itself - for production deployment . Can I just add to the existing config file , do you want command line options as well ?

**Comment by NicolasDorier** [comment]
yes you need to add command line and inside ExplorerConfiguration as well.

**Comment by chriswhellams** [comment]
@NicolasDorier sent a PR for Azure Service Bus. @sigHash you can probably copy most of what I have done to support RabbitMQ and just add another MessageBroker - assuming Nicolas is happy with the way this has been done.

**Comment by NicolasDorier** [comment]
Yep, @chriswhellams implementation is pretty much perfect.

**Comment by NicolasDorier** [comment]
Just for RabbitMQ: Depends on docker to setup the rabbitmq dependency when we run tests.

**Comment by NicolasDorier** [comment]
@sigHash you should take a look, with the last merge RabbitMQ implementation should be quite easy.

**Comment by Kukks** [comment]
Incomplete PR but almost there https://github.com/dgarage/NBXplorer/pull/89

Not a lot of time on my hands unfortunately so I welcome anyone to finish it. :)

**Comment by Kukks** [comment]
@sigHash  If you're willing to share the code I would like to add this to the codebase  after my pr is in :)
