### ISSUE TITLE
Dash and Polis InstantSend

### ISSUE THREAD

**Issue by eabz** [dgarage/NBXplorer#90]
Hello. 
We are looking towards creating a Copay fork using NBxplorer and BTCPayServer environment. 
But there is one think I am not seeing here. The broadcast transaction supports InstantSend protocol on Dash or Polis? 
If not, how can we implement it?

**Comment by NicolasDorier** [comment]
I have no idea

**Comment by eabz** [comment]
Ok. I'll check it.
