### ISSUE TITLE
Does NBXplorer support scanning Litecoin SegWit addresses ?

### ISSUE THREAD

**Issue by chriswhellams** [dgarage/NBXplorer#94]
I created a derivation strategy for LTC

```
var ntwrk = new NBXplorerNetworkProvider(NetworkType.Mainnet).GetLTC(); 
var s = ntwrk.DerivationStrategyFactory.CreateDirectDerivationStrategy(masterKey.Neuter(), new DerivationStrategyOptions()
            {
                Legacy = false
            });
client.Track(s); 
```
Wired a small amount of LTC to this address : [MWWecBMryJSGSaT7vQ9BqEqa6THudUP28D ](https://chainz.cryptoid.info/ltc/address.dws?MWWecBMryJSGSaT7vQ9BqEqa6THudUP28D.htm) but NBXplorer did not pick it up.

If I switch to Legacy = true and use a legacy address it works fine. I am creating my addresses using the following code

```
var n = NBitcoin.Altcoins.Litecoin.Instance.Mainnet;
var segwitAddr = masterKey.Neuter().Derive(1).PubKey.GetSegwitAddress(n).GetScriptAddress();
var legacyAddr = masterKey.Neuter().Derive(1).ScriptPubKey.GetDestinationAddress(n);
```
Have I done something wrong ? Any help appreciated.

**Comment by chriswhellams** [comment]
ok, I seem to have got it working but can anyone say what the P2SH switch in the options is for ? 

I set P2SH = true and tried another small transaction and it worked, but I'm not sure that it worked because of that flag

```
var s = ntwrk.DerivationStrategyFactory.CreateDirectDerivationStrategy(masterKey.Neuter(), new DerivationStrategyOptions()
            {
                Legacy = false,
                **P2SH=true**
            });
```

**Comment by NicolasDorier** [comment]
I advise you to `derivationFactory.Parse(string str)` with [this doc](https://github.com/dgarage/NBXplorer/blob/master/docs/API.md#derivation-scheme-format), it is more readable code I think.

Well P2SH = true and Legacy = false means P2SH - P2WPKH  which is defined by https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#P2WPKH_nested_in_BIP16_P2SH

**Comment by chriswhellams** [comment]
@NicolasDorier many thanks for the info, I'll have a read. I wish I had enough hours in the day to quietly sit and read through all these things before having to ask !
