### ISSUE TITLE
Unable to query ypub and zpub PublicKeys

### ISSUE THREAD

**Issue by eabz** [dgarage/NBXplorer#95]
Hello. 
I am testing the explorer with BIP49 and BIP84 using Bitcoin ypub and zpub based on slip132: https://github.com/satoshilabs/slips/blob/master/slip-0132.md

I am getting an
```
{
    "httpCode": 400,
    "code": "invalid-format",
    "message": "Invalid derivation scheme"
}
```

Seems that this API only uses xpub or am I wrong?

**Comment by NicolasDorier** [comment]
It does not support it, please convert it into a derivation scheme by using

https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/DerivationSchemeParser.cs

**Comment by eabz** [comment]
Got it. Thanks!
