### ISSUE TITLE
BTC: Error connecting to RPC server The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by rosdi** [dgarage/NBXplorer#96]
Hi,

I am testing this out today... and I couldn't find this in the wiki... so hopefully you can explain what did I do wrong.

This is how I run NBXplorer: `./run.ps1 --chains=btc --network=regtest`
This is how I start bitcoind: `.\bitcoind.exe -regtest -rest -rpcuser=bitcoinuser -rpcpassword=bitcoinpassword -debug -server`

But I keep getting '**BTC: Error connecting to RPC server The remote server returned an error: (401) Unauthorized.**' error:

`C:\Repos\NBXplorer [master ≡]> ./run.ps1 --chains=btc --network=regtest`

info: Configuration:  Data Directory: C:\Users\VC.VC-LP-207\.nbxplorer\RegTest
info: Configuration:  Configuration File: C:\Users\VC.VC-LP-207\.nbxplorer\RegTest\settings.config
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Testing RPC connection to http://localhost:18443/
Hosting environment: Production
infoContent root path: C:\Repos\NBXplorer\NBXplorer\bin\Release\netcoreapp2.1\
: Configuration:  Starting Azure Service Bus Message Broker
Now listening on: http://127.0.0.1:24446
Application started. Press Ctrl+C to shut down.
fail: Configuration:  BTC: Error connecting to RPC server The remote server returned an error: (401) Unauthorized.
fail: Configuration:  BTC: Unhandled in Waiter loop
NBXplorer.Configuration.ConfigException
   at NBXplorer.Configuration.RPCArgs.TestRPCAsync(NBXplorerNetwork networkInfo, RPCClient rpcClient, CancellationToken cancellation) in C:\Repos\NBXplorer\NBXplorer\Configuration\RPCArgs.cs:line 132
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in C:\Repos\NBXplorer\NBXplorer\BitcoinDWaiter.cs:line 260
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in C:\Repos\NBXplorer\NBXplorer\BitcoinDWaiter.cs:line 197

**Comment by NicolasDorier** [comment]
Remove `-rpcuser=bitcoinuser -rpcpassword=bitcoinpassword`

**Comment by rosdi** [comment]
That's actually my first attempt... here I attach a screenshot... of what I am seeing...

![image](https://user-images.githubusercontent.com/5094028/45263244-5de1c900-b458-11e8-83ed-b8c254c2d7c2.png)


Btw, do I need to sync any block for it to work? My laptop disk space is limited so I didn't sync any....

**Comment by rosdi** [comment]
If I run just NBXplorer without bitcoind, I will get:

`Error connecting to RPC server No connection could be made because the target machine actively refused it No connection could be made because the target machine actively refused it`

![image](https://user-images.githubusercontent.com/5094028/45264613-d012d780-b471-11e8-9d2e-05cd41e9a1cd.png)

**Comment by NicolasDorier** [comment]
those two runs are different one is using regtest and the other mainnet.

**Comment by rosdi** [comment]
I do not understand... I have run both NBXplorer and bitcoind in regtest... here are my commands:

`./run.ps1 --chains=btc --network=regtest`
and
` .\bitcoind.exe -server -regtest -debug=rpc -printtoconsole`

After I enabled the `-debug=rpc -printtoconsole` I am seeing logs by bitcoind about incorrect password attempt... here is the full bitcoind log... this proves both NBXplorer and bitcoind are on regtest.

![image](https://user-images.githubusercontent.com/5094028/45283234-deafcc00-b50f-11e8-8e03-2a1786af4601.png)

**Comment by NicolasDorier** [comment]
When I told you to stop bitcoind and start nbxplorer, you sent me this screenshot

![image](https://user-images.githubusercontent.com/3020646/45283322-7d402b00-b518-11e8-956b-51e0bc52146f.png)

which mean you started nbxplorer on mainnet, not regtest.
So please, shutdown bitcoind in regtest and run nbxplorer on **regtest** and send me the logs.

**Comment by rosdi** [comment]
I ran it on mainnet because you asked me too...

> If you close bitcoind and use `.\run.ps1` again, what error do you have?

I was puzzled at first... but I followed your instruction anyway... I thought what the heck but maybe you are debugging something...

Anyway... this is the screenshot I get when I run `./run.ps1 --chains=btc --network=regtest` without bitcoind.

![image](https://user-images.githubusercontent.com/5094028/45284979-7dd6c280-b514-11e8-8156-d2700b279976.png)

**Comment by NicolasDorier** [comment]
ok, can you run

`.\bitcoind.exe -regtest -printtoconsole -server` and give me the logs?

**Comment by NicolasDorier** [comment]
I tried, work fine.

![image](https://user-images.githubusercontent.com/3020646/45285780-f2166380-b51e-11e8-883f-9d99100bdb02.png)

Can you delete your `C:\Users\NicolasDorier\AppData\Roaming\NBXplorer\RegTest\settings.config` ?

**Comment by NicolasDorier** [comment]
Also try running bitcoind first and NBXplorer second. It should not be the problem, but let's check.

**Comment by rosdi** [comment]
I deleted the entire `.nbxplorer` folder... and then ran `./run.ps1 -regtest`, I am still getting the same `(401) Unauthorized` error.

I am running NBXplorer from master branch, could that be the cause?

**Comment by NicolasDorier** [comment]
@rosdi I am also using master branch. Can you open `C:\Users\VC.VC-LP-207\AppData\Roaming\Bitcoin\regtest\.cookie`, you should see something like `__cookiefile__:blahblah`

Can you use `./run.ps1 -regtest --btcrpcuser "__cookie__" --btcrpcpassword "blahblah"`

**Comment by rosdi** [comment]
Is it normal for the cookie file to change everytime I restart bitcoind? Here I tried twice... everytime I start bitcoind the cookie changes.... so here you can see I try to connect twice... both getting 401...

![image](https://user-images.githubusercontent.com/5094028/45295419-2e52bf80-b531-11e8-89f1-6b291c75ea1c.png)

I will retry from another computer now... let's see what comes up..

**Comment by NicolasDorier** [comment]
@rosdi yes it is normal. Start bitcoind first, then start with the cookie as rpcuser and rpcpassword as you are doing. Your error is very strange, I hope we find out what happen.

Also can you try `bitcoin-cli.exe -regtest getblockchaininfo` ?

**Comment by rosdi** [comment]
Here is a screenshot from my second PC, same error... build fresh from master branch... I didn't configure/tinker with any settings...

![image](https://user-images.githubusercontent.com/5094028/45304366-877b1d00-b54a-11e8-88ea-fb28c71465fc.png)

**Comment by rosdi** [comment]
Here is the result after running the command:

E:\Bitcoin\daemon> ./bitcoin-cli.exe -regtest getblockchaininfo
{
  "chain": "regtest",
  "blocks": 0,
  "headers": 0,
  "bestblockhash": "0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206",
  "difficulty": 4.656542373906925e-010,
  "mediantime": 1296688602,
  "verificationprogress": 1,
  "initialblockdownload": true,
  "chainwork": "0000000000000000000000000000000000000000000000000000000000000002",
  "size_on_disk": 293,
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": false
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": false
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": false
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "defined",
      "startTime": 0,
      "timeout": 9223372036854775807,
      "since": 0
    },
    "segwit": {
      "status": "active",
      "startTime": -1,
      "timeout": 9223372036854775807,
      "since": 0
    }
  },
  "warnings": ""
}
E:\Bitcoin\daemon>

**Comment by NicolasDorier** [comment]
That's really crazy. Can you try `.\run.ps1 --rpccookiefile "pathTo\.cookie"`

**Comment by rosdi** [comment]
Unfortunately..., same result... :-(

![image](https://user-images.githubusercontent.com/5094028/45306411-2bff5e00-b54f-11e8-9afa-98df80cf6bf8.png)

**Comment by NicolasDorier** [comment]
wrong path, it need to be path to the cookiefile of bitcoind

**Comment by NicolasDorier** [comment]
Wait a minute

**Comment by NicolasDorier** [comment]
The log you sent me, your user is `VC.VC-LP-207`, while the screenshot show `rosdi`

**Comment by rosdi** [comment]
Yes this is from my second computer... I can use the first computer if you want.

**Comment by NicolasDorier** [comment]
Wait, you are running both program on the same computer right?

**Comment by rosdi** [comment]
Yes... both bitcoind and nbxplorer on the same computer... I have a laptop
and a desktop... I just cloned again nbxplorer on my desktop and try to run
nbxplorer on the desktop as well to see if I can reproduce the issue...
both is showing the same error... 401 Unauthorized...

Sorry if that confuses you... I will use just my laptop from now on... to
avoid further confusion.

**Comment by NicolasDorier** [comment]
On the right computer try

`.\run.ps1 -regtest --btcrpccookiefile "C:\Users\VC.VC-LP-207\AppData\Roaming\Bitcoin\regtest\.cookie"`

**Comment by NicolasDorier** [comment]
I need to go to bed and take the plane tomorrow, I won't be able to look at it.

If you have time you can try to step by step in nbxplorer code with visual studio or visual studio code to see what is going on. This is the first time I see that happening though.

**Comment by rosdi** [comment]
Cheers!.. no worries... I will update if I found anything....

**Comment by rosdi** [comment]
This one seems to be working!... I still do not know what happened.

![image](https://user-images.githubusercontent.com/5094028/45307800-851cc100-b552-11e8-82e6-1b36b4cd3e88.png)

**Comment by NicolasDorier** [comment]
Ok so `C:\Users\VC.VC-LP-207\AppData\Roaming\Bitcoin\regtest\.cookie` should normally be the default value with normally no need to specify it.
Can you tell me what 
```powershell
$env:HOME
$env:APPDATA
```
print you in powershell before you run `.\run.ps1` ?

**Comment by NicolasDorier** [comment]
Ah actually I find the problem

![image](https://user-images.githubusercontent.com/3020646/45383779-208f5e00-b647-11e8-8c31-c23adaf06e22.png)

This is not normal. I think you have your `$env:HOME` environment variable set, which I don't expect on windows.

**Comment by NicolasDorier** [comment]
I think I found the issue here. Can you confirm  what

```
$env:HOME
$env:APPDATA
```

print?

**Comment by rosdi** [comment]
```
C:\Repos> $env:HOME
C:\Users\VC.VC-LP-207
C:\Repos> $env:APPDATA
C:\Users\VC.VC-LP-207\AppData\Roaming
C:\Repos>
```

![image](https://user-images.githubusercontent.com/5094028/45395271-f732fa00-b667-11e8-9f31-028592dbfa63.png)

**Comment by NicolasDorier** [comment]
sorry, I was in holiday. So yes I identified your issue. I need to stop looking at `$env:HOME` on windows.

**Comment by rosdi** [comment]
Great!... yup I know you were on holiday... I follows btcpayserver on twitter... I am building and installing this because I want to learn btcpayserver the hard way... I refuse to use azure installer or docker... *at least for now* ... great job btw!

**Comment by NicolasDorier** [comment]
@rosdi Ok so I fixed all libs where this bug might had an impact. Can you try again?

**Comment by rosdi** [comment]
Yep this latest version works!... thanks!
