### ISSUE TITLE
Unable to build and run NBXplorer Ubuntu

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#97]
Hi, cannot even get past the 1st step of you're instructions:

From cloned NBXplorer root folder
./run.sh
The application to execute does not exist '/root/NBXplorer/NBXplorer/bin/Release/netcoreapp2.1/NBXplorer.dll'

Also same message as above if I just execute command:
 dotnet run --no-launch-profile --no-build -c Release -p "NBXplorer/NBXplorer.csproj" -- $@ --chains=btc,ltc --network=testnet

**Comment by NicolasDorier** [comment]
the 1st step is `.\build.sh` not `.\run.sh`

**Comment by sixjac** [comment]
Issues with /.run.sh after building, please see below:

<img width="495" alt="untitled" src="https://user-images.githubusercontent.com/4453138/45266759-5de5c700-b460-11e8-9104-3776ec114c2f.png">

btcd, ltcd & dashd are installed and syncing

**Comment by NicolasDorier** [comment]
Yes this is configuration. I can't tell you what is going on without all the command line that you ran for each of the nodes, as well as their log for each of them.

**Comment by sixjac** [comment]
Bitcoind & Litecoind
Followed this: https://github.com/mmgen/mmgen/wiki/Install-Bitcoind-from-Source-on-Debian-or-Ubuntu-Linux
(Without optional ABC)

Dashd
git clone https://github.com/dashpay/dash.git
cd dash/
./autogen.sh
./configure --disable-wallet --without-gui --without-miniupnpc
make check

From: https://github.com/dashpay/dash/blob/master/doc/build-unix.md

Still looking for logs but did you mean logs from build or logs from NBXplorer ./Run.sh...?

**Comment by NicolasDorier** [comment]
This is not command line for starting dash, but for building dash. I need command line you used for starting dash as well as dash logs.

**Comment by sixjac** [comment]
I just started dash via command dashd and the process started, that is all. I am not sure where can find logs, I am mainly a Windows guy and my VPS is all Ubuntu commandline, no GUI

**Comment by NicolasDorier** [comment]
I need the logs to help you, and I don't know where dash put it.

**Comment by sixjac** [comment]
Ok I will find them, but also seems to be connection RPC error with BTC and LTC nodes as in the screenshot output images attached......

**Comment by NicolasDorier** [comment]
also, you are running network in testnet, so you need to run same on dash

**Comment by NicolasDorier** [comment]
so give me the logs.

**Comment by sixjac** [comment]
Could only find DASH Config.log, no idea where any NBXplorer or other Dash logs are, do not know what they are names either so It makes hard to search, this is all i could find from commandline search.

I appreciate this will not help, do you know of a compatible configuration that will work for NBXplorer?

[DASH_Config.log](https://github.com/dgarage/NBXplorer/files/2365396/DASH_Config.log)

**Comment by sixjac** [comment]
In that case I will forget about Dash support but can you see there are also issues with BTC and LTC when running NBXplorer, as in the images......

**Comment by NicolasDorier** [comment]
so give me debug logs in ~/.litecoin

**Comment by sixjac** [comment]
This is all in ~/.litecoin

aclocal.m4      configure        doc                        Makefile.am
autogen.sh      configure.ac     INSTALL.md                 Makefile.in
autom4te.cache  contrib          libbitcoinconsensus.pc     README.md
build-aux       CONTRIBUTING.md  libbitcoinconsensus.pc.in  share
config.log      COPYING          libtool                    src
config.status   depends          Makefile                   test

No logs except for Config.log

**Comment by NicolasDorier** [comment]
this is log files. Sorry I don't know why there is no litecoin `debug.log`, search for it.

**Comment by sixjac** [comment]
Coll that is all i needed the name of the actual logs to search ;)

Please see attached
[Uploading btc_debug.log…]()
[Uploading dash_debug.log…]()

**Comment by sixjac** [comment]
Cool that is all i needed the name of the actual logs to search ;)

Please see attached


[logs.zip](https://github.com/dgarage/NBXplorer/files/2365648/logs.zip)

**Comment by NicolasDorier** [comment]
I don't know. If you start bitcoind, litecoind and NBXplorer on same machine (either all using linux or all using windows), then it should connect. I don't see anything that can help in those file sadly.

**Comment by sixjac** [comment]
Ok thanks, will look into it more

**Comment by sixjac** [comment]
Seems i need to edit the following:

#btc.node.endpoint=127.0.0.1:BTC //Should be 0.0.0.0 for remote bind --bind=0.0.0.0 yes?

## startheight defines from which block you will start scanning, if -1 is set, it will use current blockchain height
#btc.startheight=-1
## rescan forces a rescan from startheight
#btc.rescan=0
## This is the RPC Connection to your node
#ltc.rpc.url=http://127.0.0.1:19332/       //Should be 0.0.0.0 for remote bind --bind=0.0.0.0 yes?
#By user name and password
#ltc.rpc.user=bitcoinuser
#ltc.rpc.password=bitcoinpassword
#By cookie file
#ltc.rpc.cookiefile=yourbitcoinfolder/.cookie   /usr/bin/litecoin/.cookie yes?

**Comment by NicolasDorier** [comment]
yes you use the configuration file.

**Comment by sixjac** [comment]
Yes but the settings.conf says at top of file:
"####If Bitcoin Core is running with default settings, you should not need to modify this file####"

**Comment by NicolasDorier** [comment]
every parameter documented by `./run.sh --help`  can be set either through configuration file or environment variables.

**Comment by sixjac** [comment]
Ok and how about here as per GitHub docs:

"If you are using Bitcoin core default settings:
On Linux:
./build.sh"

Does ./build.sh have anything configurable of look into settings.config file????

**Comment by NicolasDorier** [comment]
no

**Comment by sixjac** [comment]
Got it figured out

**Comment by sixjac** [comment]
Sorry have to reopen this I ran into some config issues again on VPS server with bitcoind and NBXplorer, what is the issue here? Config file issue or i have to wait for bitcoin node to fully sync? Thanks
![synching](https://user-images.githubusercontent.com/4453138/46609066-05f5bb00-cb07-11e8-8e6c-a055cee7e19d.jpg)

**Comment by sixjac** [comment]
Looks like needs to be Synced yes
